### ISSUE TITLE
CoverageValidator::isValid returns false for valid input

### ISSUE THREAD

**Issue by 0xh0b0** [libgeos/geos#1001]
CoverageValidator::isValid returns false for the following set of polygons
```
POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))
POLYGON ((0 1, 0 2, 2 2, 2 1, 0 1))
```
![Screenshot 2023-11-27 at 10 58 11](https://github.com/libgeos/geos/assets/10731778/09c74c97-809c-4b35-9dcb-d0fbd2c1494c)

Other similar sets of polygons (1x2 and 1x1 rectangle on 2x2 grid) pass the validity check

**Comment by dr-jts** [comment]
That is correct.  Polygon 2 does not contain the adjacent vertex (1, 1) in Polygon 1.
