### ISSUE TITLE
Prepared Contains mismatch with Contains

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#1007]
As reported at https://trac.osgeo.org/postgis/ticket/5634. The issue is in GEOS prepared geometry.

A test for `PreparedGeometryTest.cpp`:
```
template<>
template<>
void object::test<3>
()
{
    g1 = reader.read( "MULTIPOLYGON(((-60 -50,-70 -50,-60 -40,-60 -50)))" );
    g2 = reader.read( "GEOMETRYCOLLECTION(MULTIPOINT((-60 -50),(-63 -49)))" );

    pg1 = prep::PreparedGeometryFactory::prepare(g1.get());

    ensure(  g1->contains(g2.get()) );
    ensure( pg1->contains(g2.get()) );
}
```

**Comment by pramsey** [comment]
Seems to require the double nesting to exercise the bug, both 
```
MULTIPOINT((-60 -50),(-63 -49))
```
and
```
GEOMETRYCOLLECTION(POINT(-60 -50),POINT(-63 -49))
```
work as variations on the second argument.

**Comment by pramsey** [comment]
@cuteDen-ECNU as a general proposition, every prepared variant should return the same as the non-prepared variant, I imagine there's a lot of possible issues hiding in that proposition.

**Comment by dr-jts** [comment]
Tests expressed with `geosop`:
```
bin/geosop -a "MULTIPOLYGON(((-60 -50,-70 -50,-60 -40,-60 -50)))" -b "GEOMETRYCOLLECTION(MULTIPOINT((-60 -50),(-63 -49)))" contains
==> true

bin/geosop -a "MULTIPOLYGON(((-60 -50,-70 -50,-60 -40,-60 -50)))" -b "GEOMETRYCOLLECTION(MULTIPOINT((-60 -50),(-63 -49)))" containsPrep
==> false
```

I thought this might be related to #982, but in fact in this case the `contains` result is correct, but the `preparedContains` result is wrong.  Also, "unwrapping" the MULTIPOINT produces the correct result:
```
bin/geosop -a "MULTIPOLYGON(((-60 -50,-70 -50,-60 -40,-60 -50)))" -b "MULTIPOINT((-60 -50),(-63 -49))" containsPrep 
==>true
```
Further investigation is required.

**Comment by cuteDen-ECNU** [comment]
> as a general proposition, every prepared variant should return the same as the non-prepared variant, I imagine there's a lot of possible issues hiding in that proposition.

I agree with you. I am refining my tool to focus on this kind of issue.

**Comment by dr-jts** [comment]
The problem is caused by [this line](https://github.com/libgeos/geos/blob/main/src/geom/prep/AbstractPreparedPolygonContains.cpp#L204) in `AbstractPreparedPolygonContains`:
```
if (geom->getNumGeometries() > 1) {
```
This does not handle GeometryCollections which contain one element which itself contains multiple elements.  

What is probably needed is a `getNumAtomicElements` method.  (There may be one - will look).
