### ISSUE TITLE
Issue with ST_OffsetCurve

### ISSUE THREAD

**Issue by wzbnb001** [libgeos/geos#1030]
on GEOS 3.10.x, the following function is returning LINESTRING(179 195,179 16), which is correct
SELECT ST_AsText(ST_OffsetCurve(ST_GeomFromText('LINESTRING(164 16,164 195)'), -15, 'quad_segs=4 join=round')) AS linestring_value;

on GEOS 3.12.x, the same function is returning LINESTRING(179 16,179 195), which is incorrect, since, although this point is translated 15 units to the right, the direction of the line is NOT reversed.

We are testing them with same version of postgis and gdal, only the GEOS version is different.

**Comment by dr-jts** [comment]
A GEOS repro:
```
geosop -a "LINESTRING (164 16, 164 195)" offsetCurve N-15
```
Result:
```
LINESTRING (179 16, 179 195)
```

**Comment by dr-jts** [comment]
The GEOS result is correct.  The line is offset 15 units to the right, and the direction is the same as the original line.

It's GEOS 3.10 that is incorrect.
