### ISSUE TITLE
ST_Relate gives incorrect result for interior-interior intersection dimension

### ISSUE THREAD

**Issue by cuteDen-ECNU** [libgeos/geos#1053]
Considering the following statement:
```sql
SELECT ST_Relate(g1, g2)
  FROM (VALUES
  ('MULTILINESTRING((2 4, 10 10),(15 10,10 5,5 10))'::geometry, 
   'MULTILINESTRING((2 4, 10 10))'::geometry)
  ) AS sdb(g1, g2);

--expected{ 1F1F001F2}; actual{ 0F1F001F2}
```

```shell 
bin/geosop -a 'MULTILINESTRING((2 4, 10 10),(15 10,10 5,5 10))' -b 'MULTILINESTRING((2 4, 10 10))' relate
# expected{ 1F1F001F2}; actual{ 0F1F001F2}
```
The intersection of interior-interior of g1 and g2 is `LINESTRING(2 4, 10 10)` whose dimension is 1. Thus the de9im code should be 1F1F001F2 instead of 0F1F001F2.

The version of Geos is the latest one:
[bdceea6](https://github.com/libgeos/geos/commit/bdceea69174e80cf2cc2959d6da8d9dd0e766e3e)

**Comment by dr-jts** [comment]
This is an example of a long-standing design issue with the current topological predicate algorithm.  See also:

* https://github.com/locationtech/jts/issues/396
* https://trac.osgeo.org/geos/ticket/572

There is a new topological predicate algorithm being worked on which solves this problem.

**Comment by dr-jts** [comment]
Actually the expected result is `1F1F00FF2` (since A contains B, the Exterior of A does not interact with the Interior of B).

This result is correctly computed by the RelateNG algorithm.
