### ISSUE TITLE
There seems to be a circular reference in WKT BNF

### ISSUE THREAD

**Issue by LiShunGang** [libgeos/geos#1065]
Screenshot from the following url
https://libgeos.org/specifications/wkt/
![image](https://github.com/libgeos/geos/assets/36393104/120c9161-a94e-4fb0-bc3b-f8e7bbc5336f)

'wkt representation', 'geometrycollection text representation' and 'geometrycollection text
refer' reference each other?

**Comment by dr-jts** [comment]
Yes, it's a recursive definition.  GeometryCollections can contain other GeometryCollections (and anything else).

**Comment by LiShunGang** [comment]
Thank you. I got it. GeometryCollections can contain itself.
