### ISSUE TITLE
Relate predicates fail on almost-identical polygons with small coordinate discrepancies

### ISSUE THREAD

**Issue by dr-jts** [libgeos/geos#1069]
Some predicates (e.g. `intersects` and `touches`) fail with `TopologyException` on polygon inputs which are almost identical in shape but have very small differences in coordinate values.

### Example coordinate discrepancies:
```
A: POINT ( -80.99882 27.267360999999998 )
B: POINT ( -80.99882 27.267361 ) 
```

WKB for A and B:
[a-wkb.txt](https://github.com/libgeos/geos/files/15031397/a-wkb.txt)
[b-wkb.txt](https://github.com/libgeos/geos/files/15031398/b-wkb.txt)

Reported in https://trac.osgeo.org/postgis/ticket/5713

**Comment by pramsey** [comment]
No crashes seen by me, fixed now?
