### ISSUE TITLE
What's the format of MULTIPOINT ?

### ISSUE THREAD

**Issue by LiShunGang** [libgeos/geos#1086]
I'm coding regex for WKT. I saw two kinds of format of MULTIPOINT, "MULTIPOINT(1 1, 2 2)" and "MULTIPOINT((1 1), (2 2))". Are they all right format?

https://libgeos.org/specifications/wkt/
```
<multipoint text> ::=
    <empty set> |
    <left paren> <point> {<comma> <point>} ... <right paren>
```

Does the defination should be
```
<multipoint text> ::=
    <empty set> |
    <left paren> <point text> {<comma> <point text>} ... <right paren>
```

**Comment by mwtoews** [comment]
The second form is more correct (i.e. it is the one mandated in specs), although both are found in the wild. The first form was written by GEOS' WKT Writers until recently (see #903). WKT Readers should be able to read most of the alternative forms except "MULTIPOINT (EMPTY, 1 2)", which raises a ParseException.

**Comment by LiShunGang** [comment]
Thank you for you reply. I will support both.
