### ISSUE TITLE
CMake CMP0153

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#1102]
CMP0153
-------

.. versionadded:: 3.28

The ``exec_program()`` command should not be called.

This command has long been superseded by the ``execute_process()``
command and has been deprecated since CMake 3.0.

CMake >= 3.28 prefer that this command never be called.
The ``OLD`` behavior for this policy is to allow the command to be called.
The ``NEW`` behavior for this policy is to issue a ``FATAL_ERROR`` when the
command is called.

This policy was introduced in CMake version 3.28.
It may be set by ``cmake_policy()`` or ``cmake_minimum_required()``.
If it is not set, CMake warns, and uses ``OLD`` behavior.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.

**Comment by rouault** [comment]
It looks like this issue can now be closed
