### ISSUE TITLE
Dynamic library is not fully setup by `make install` ( missing ldconfig )

### ISSUE THREAD

**Issue by strk** [libgeos/geos#1112]
Right after `make install` the system is not ready to use libgeos. User is still in charge of running `ldconfig` ( on a u*x box ).
This used to be automatic with automake, via libtool --mode=install.

**Comment by pramsey** [comment]
I'm not convinced this is correct behaviour. I certainly have had no shortage of libraries over my life that required I run `ldconfig` myself post-install. I'm frankly surprised it would ever be done as part of install separately.

**Comment by strk** [comment]
ok, I'm sold.

**Comment by hobu** [comment]
`ldconfig` as a post-install convenience was just a libtool-only thing IIRC.
