### ISSUE TITLE
Build fails in C++23 language mode due to one forward declaration

### ISSUE THREAD

**Issue by BwL1289** [libgeos/geos#1121]
GEOS version: `3.12.2`

In C++23 language mode (in both Clang 18.1.8 and GCC 14.1), the build fails due to use of forward declarations in places where the complete type should be present. 

Currently, the following lines are the root cause:
1. https://github.com/libgeos/geos/blob/3.12.2/include/geos/operation/buffer/OffsetCurveSection.h#L26
2. [geos/include/geos/operation/buffer/OffsetCurveSection.h at 3.12.2 · libgeos/geos](https://github.com/libgeos/geos/blob/3.12.2/include/geos/operation/buffer/OffsetCurveSection.h#L67C29-L67C39)

The same code builds fine in C++20 language mode in both of the above compilers. In C++23 what's changed is that if `unique_ptr` destructor is called (even implicitly, as `std::move` does under the hood) the type should be complete. Forward declarations are still allowed with `unique_ptr` if destructor isn't called in scope.

For now, by explicitly including `<geos/geom/CoordinateSequence.h>` in this file we bypass the issue and GEOS builds and works fine.

**Comment by pramsey** [comment]
Can you open up a PR with the requested change please? We are not moving to C++23 any time soon, but non-breaking changes to support it are fine.

**Comment by BwL1289** [comment]
@pramsey see [#1122](https://github.com/libgeos/geos/pull/1122)

**Comment by BwL1289** [comment]
@pramsey thank you!
