### ISSUE TITLE
could not find libgeos_c

### ISSUE THREAD

**Issue by hopeyl** [libgeos/geos#1124]
I'm running `./configure --host=arm-linux-gnueabihf `to compile and install postgis, but I'm getting the following error, I don't know why this is happening, please help me
geos version = 3.12.2
postgis version =3.4.1
![image](https://github.com/libgeos/geos/assets/84188706/8a6dd666-48b4-48b7-a877-4e067fb5b004)

**Comment by rouault** [comment]
To be closed. This is not a GEOS issue
