### ISSUE TITLE
Polygon buffer removes its hole when quadSegs = 0

### ISSUE THREAD

**Issue by dzakaTarik** [libgeos/geos#1125]
geosop - GEOS 3.12.2

When taking a small buffer around the polygon with `quadSegs = 0` and `distance=1e-5,` one polygon hole is completely removed for no apparent reason. Hole is much bigger than the buffer and there is no way that buffering removes this hole naturally. I tried distances 100, 10, 1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-6, all of which do not remove the hole.

Input polygon: [poly.wkt.txt](https://github.com/user-attachments/files/16162673/poly.wkt.txt)

**Visualisation** 
Input
<img width="897" alt="input poly" src="https://github.com/libgeos/geos/assets/105068198/9ffb426c-ff20-4984-b94d-f452e2e8603b">
Buffer `dist=1e-5, quadSegs=0`
<img width="878" alt="buffer 1e-5" src="https://github.com/libgeos/geos/assets/105068198/300833be-0bfc-406d-b426-6a000284eee1">
Buffer `dist=100, quadSegs=0`
<img width="891" alt="buffer 100" src="https://github.com/libgeos/geos/assets/105068198/16fddd93-55ad-4568-865b-57c0fdd38309">

To quickly reproduce, you can add a new operation to `utils/geosop/GeometryOp.cpp`:
`{"bufferWithQuadrantSegments", [](std::string name) { return GeometryOp::create(name,
    catConst,
    "compute the buffer of geometry by a distance with quadrant segments",
    [](const std::unique_ptr<Geometry>& geom, double d, int quadrantSegments) {
        return new Result( geom->buffer( d, quadrantSegments ) );
    });
    }},`

**Comment by pramsey** [comment]
So, firstly "quadsegs = 0" seems like a case that makes sense. The definition of quadsegs says "The number of segments per quadrant to generate. More segments provides a more "precise" buffer at the expense of size". There would seem to be an implied minimum of 1 segment for quadrant. So first question to explore I guess is what the code even thinks 0 means. Second question is why you think it's useful?

**Comment by pramsey** [comment]
So the code for OffsetCurve forces quadSegs up to 8. For BufferOp, the OffsetCurveGenerator sets it up to 1.

**Comment by pramsey** [comment]
Moving the default minimum segs to 4 resolves this hole-loss issue, but causes two XML failures, in TestBufferExternal-1.xml and issue-geos-188.xml that both test the 1-segment quadseg case. @dr-jts how important is the idea of having a 1 segment "quadsegs" parameter?

**Comment by dr-jts** [comment]
>  how important is the idea of having a 1 segment "quadsegs" parameter?

It's nice to have for generating "angular" buffers

<img width="580" alt="image" src="https://github.com/user-attachments/assets/4adefbee-8638-4385-9540-e30113d7bafb">

It's not clear why the OP requires `quadSegs = 0` in this case.  Since the larger quadSegs value eliminates the error, he can just use that value.

It would be nice to fix the problem, but this is probably one of those tricky robustness issues that still lurk for the unwary in the buffer code.

**Comment by pramsey** [comment]
`quadsegs = 0` is not a thing that actually happens, the existing code already bumps that case up to `1`.  Unfortunately it still has a hole-losing failure in that case (for the 1e-5 buffer distance).

**Comment by dr-jts** [comment]
> `quadsegs = 0` is not a thing that actually happens, the existing code already bumps that case up to `1`. Unfortunately it still has a hole-losing failure in that case (for the 1e-5 buffer distance).

Right.  The input is clamped to avoid crashing.  It's still up to the user to pick a meaningful value.  (And as noted, would be nice to fix the problem, but probs not easy).

**Comment by dr-jts** [comment]
JTS has the same issue.

I suspect the issue is caused by veeery short segments being generated as convex corner fillets are being computed. In this case, with quadrant segs = 1, corner fillets are just single segments connecting the adjacent offset segments.

I tried increasing the OffsetSegmentGenerator [CURVE_VERTEX_SNAP_DISTANCE_FACTOR](https://github.com/libgeos/geos/blob/main/src/operation/buffer/OffsetSegmentGenerator.cpp#L47) to 1e-4 (from 1e-6).  This removes more short segments.  That fixes this problem.  Seems like a safe change to make?

**Comment by dzakaTarik** [comment]
@pramsey 
> ...There would seem to be an implied minimum of 1 segment for quadrant. So first question to explore I guess is what the code even thinks 0 means. Second question is why you think it's useful?

Quoting [Geos docs](https://libgeos.org/doxygen/classgeos_1_1operation_1_1buffer_1_1BufferParameters.html#adc5559aa27d60c7b40aba6d5c13c0c45):

> If quadSegs = 0, joins are bevelled (flat)

Even negative values have some meaning according to docs.

**Comment by pramsey** [comment]
Huh, the code thinks otherwise, at least in GEOS (since non-positive values get re-written). Does JTS have some meaning for negative quadSegs, @drjts ?

**Comment by dr-jts** [comment]
> Huh, the code thinks otherwise, at least in GEOS (since non-positive values get re-written). Does JTS have some meaning for negative quadSegs, @drjts ?

Nope, no meaning to negative values.

**Comment by dr-jts** [comment]
> Huh, the code thinks otherwise, at least in GEOS (since non-positive values get re-written). Does JTS have some meaning for negative quadSegs, @drjts ?

Hmm, I have a vague recollection that this was added to allow specifying join style and quadrant segments with a single numeric parameter.   Perhaps this got lost along the way?
