### ISSUE TITLE
Doubts about the goes C interface

### ISSUE THREAD

**Issue by xwl742** [libgeos/geos#1126]
What is the connection between geos_c.cpp and geos_ts_c.cpp under capi? 
geos_ts_c.cpp, Does' ts' mean thread safe? 
I understand that geos_ts_c.cpp is responsible for the main implementation of the interface in geos_c.h, Is my understanding correct?
I look forward to receiving your reply ！

**Comment by rouault** [comment]
geos_c.cpp: C API functions relying on a global GEOS context
geos_ts_c.cpp: C API functions with the _r (reentrant) suffix

> Does' ts' mean thread safe?

much likely
