### ISSUE TITLE
`simplify` with `preserve_topology=True` difference for MultiLineString between 3.12.1 and 3.12.2

### ISSUE THREAD

**Issue by theroggy** [libgeos/geos#1127]
A CI test of mine started failing for 3.12.2 versus 3.12.1, and I wondered what the correct expected behaviour is...
Reference: https://github.com/pygeoops/pygeoops/pull/97

I suppose the change in behaviour is linked to this PR: https://github.com/libgeos/geos/pull/1012

There difference is in the result of `simplify` with `preserve_topology=True` for MultiLineString geometries in 3.12.2 compared to 3.12.1.

With 3.12.1, the input linestring left, the result of simplify to the right:
![image](https://github.com/user-attachments/assets/66c0bb90-5a14-4789-ad50-df8f3df5ff48)

With 3.12.2, the input linestring left, the result of simplify to the right:
![image](https://github.com/user-attachments/assets/7546cc62-2f2c-46d3-a154-ef47b7747024)

Script to reproduce:
``` py
from matplotlib import pyplot as plt
import shapely
import shapely.plotting as plotter

# Prepare test data
input_wkt = "MULTILINESTRING ((0 10, 10 10, 10 0), (10 10, 11 0, 10 0))"
input_geom = shapely.from_wkt(input_wkt)

# Simplify the input
result = shapely.simplify(input_geom, tolerance=2, preserve_topology=True)

# Plot input and result
fig, ax = plt.subplots(ncols=2)
colors = ["red", "blue"]
for index, line in enumerate(input_geom.geoms):
    plotter.plot_line(line, ax=ax[0], add_points=True, color=colors[index])
    ax[0].set_aspect("equal")
for index, line in enumerate(result.geoms):
    plotter.plot_line(line, ax=ax[1], add_points=True, color=colors[index])
    ax[1].set_aspect("equal")

plt.show()
```

**Comment by dr-jts** [comment]
The new behaviour is correct.  TopologyPreservingSimplifier keeps the linestrings separate, in order to preserve the topology.
