### ISSUE TITLE
MakeValid method

### ISSUE THREAD

**Issue by balbesina** [libgeos/geos#1134]
It's mb more a question than an issue. 

Function `GEOSMakeValidWithParams` uses `GEOSMakeValidParams`, where `method` is enum [GEOSMakeValidMethods](https://github.com/libgeos/geos/blob/6201229a66ae3eef2b0c62cc39dbab48b2e3df7e/capi/geos_c.h.in#L1475) with two options `GEOS_MAKE_VALID_LINEWORK = 0` and `GEOS_MAKE_VALID_STRUCTURE = 1`.

Postgis function [ST_MakeValid](https://postgis.net/docs/ST_MakeValid.html) provides method argument as a string `structure` or `linework` (default) e.g.
```sql
SELECT ST_AsText(ST_MakeValid('LINESTRING(0 0, 0 0)','method=structure'));
```

I'm trying to understand why sql func uses string argument instead of boolean. Other possible `method`s exist?
If not it looks like bad implementation of the function. Should be `GEOSMakeValid` without args and `GEOSMakeValidStructure` with bool flag `keepCollapsed` default false.

**Comment by rouault** [comment]
PostGIS API choices are PostGIS API choices, not a GEOS issue.
And I suspect GEOSMakeValid() being mapped to GEOSMakeValidWithParams() with method = GEOS_MAKE_VALID_LINEWORK and keepCollapsed = 1 is for backwards compatibility with the behavior before the introduction of GEOSMakeValidWithParams()

**Comment by balbesina** [comment]
Thx everyone. I was not accurate and didn’t check that keepCollapsed is true by default (without params). Which may have provided incorrect behaviour for linestring. The doc of sql function fooled me with words: keepCollapsed is only applied with method=structure. And it feels natural that create params method should create default params for makeValid without params. Your answers are really appreciated.
