### ISSUE TITLE
How to split a polygon with a line?

### ISSUE THREAD

**Issue by valvarezf** [libgeos/geos#1135]
I tried several methods:

.- OverlayNG::overlay DIFFERENCE
.- intersection and then add intersection and polygon to a polygonizer
.- symdifference / difference
.- intersection and then difference / symdifference
.- intersection and then EnhancedPrecisionOp::difference / EnhancedPrecisionOp::symdifference
.- intersection and then add intersection and polygon to a geomcollection and then use polygonizer

Can someone help me?

**Comment by dbaston** [comment]
This functionality isn't currently provided directly by GEOS. A common method is to union the splitting line with the boundary of the polygon, then polygonize the result. https://github.com/libgeos/geos/issues/1101 contains links to a few implementations of this.
