### ISSUE TITLE
RelateNG boundaryNode DE9IM regression

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#1149]
Pull latest head to get the updated testing infra, and then add the following test to `RelateNGTest.cpp`
```
// Boundary node
template<>
template<>
void object::test<63> ()
{
    std::string a = "POLYGON((0 0,140 0,140 140,0 140,0 0))";
    std::string b = "POLYGON((140 0,0 0,0 140,140 140,140 0))";
    checkRelateRule(a, b, "2FFF0FFF2", geos::algorithm::BoundaryNodeRule::getBoundaryMultivalentEndPoint());
}
```
PostGIS turns up a number of failures trying different bnRule cases, and this is one example.

**Comment by dr-jts** [comment]
@pramsey should port this (and add this test):

https://github.com/locationtech/jts/blob/master/modules/core/src/test/java/org/locationtech/jts/operation/relateng/RelateNGBoundaryNodeRuleTest.java

**Comment by pramsey** [comment]
Will get right on it.

**Comment by dr-jts** [comment]
Since the polygons are topologically equal, their boundary-boundary interaction has dimension 1.  So the DE-9IM matrix should be:  `2FFF1FFF2`.  This is what RelateNG reports.  (Note that the BNR only considers boundary points in linear elements, so the choice of BNR does not affect this DE-9IM result).

Looks like the PostGIS test is wrong?

**Comment by pramsey** [comment]
Well, more generally the older version of GEOS is what's generating that answer.

**Comment by dr-jts** [comment]
> Well, more generally the older version of GEOS is what's generating that answer.

Right, and this matches the JTS RelateOp output.  I guess this case was never tested with the old algorithm.

**Comment by dr-jts** [comment]
JTS test: https://github.com/locationtech/jts/commit/a96516ad0b7524a34045e8d2ebd3f7d9d0b79ab6

**Comment by dr-jts** [comment]
Kudos to PostGIS for having more extensive tests!  (Even if they are wrong.. :).  Would be good to pull them down to JTS/GEOS.

**Comment by pramsey** [comment]
Ported test, have one failure
```
LINESTRING (20 100, 20 220, 120 100, 20 100) relate LINESTRING (20 20, 20 100) = F01FFF102
[4=F]....

---> group: geos::operation::relateng::RelateNGBoundarNodeRule, test: test<4>
     problem: assertion failed
     failed assertion: `runRelate: expected `FF10FF1F2` actual `F01FFF102``
```

**Comment by pramsey** [comment]
Ported the example from PostGIS and failure is the same, 
```
POLYGON ((0 0, 140 0, 140 140, 0 140, 0 0)) relate MultiValentEndPointBoundaryNodeRule POLYGON ((140 0, 0 0, 0 140, 140 140, 140 0)) = 2FFF1FFF2

geos::operation::relateng::RelateNGBoundarNodeRule: [9=F]

---> group: geos::operation::relateng::RelateNGBoundarNodeRule, test: test<9>
     problem: assertion failed
     failed assertion: `runRelate: expected `2FFF0FFF2` actual `2FFF1FFF2``
```

**Comment by dr-jts** [comment]
> Ported the example from PostGIS and failure is the same,

So this is just reflecting the current (and correct) RelateNG behaviour, right?

**Comment by dr-jts** [comment]
> Ported test, have one failure
> 
> ```
> LINESTRING (20 100, 20 220, 120 100, 20 100) relate MonoValentEndPointBoundaryNodeRule LINESTRING (20 20, 20 100) = F01FFF102
> 
> geos::operation::relateng::RelateNGBoundarNodeRule: [4=F]
> 
> ---> group: geos::operation::relateng::RelateNGBoundarNodeRule, test: test<4>
>      problem: assertion failed
>      failed assertion: `runRelate: expected `FF10FF1F2` actual `F01FFF102``
> ```

Not sure where that expected result came from.  The actual is correct.

Added to JTS: https://github.com/locationtech/jts/commit/7e261724cdb3702406f8756bc2ccae14ad32e094
