### ISSUE TITLE
Restore Quadtree move semantics

### ISSUE THREAD

**Issue by ikolev21** [libgeos/geos#1161]
In geos-3.13 the class `geos::index::quadtree::Quadtree` has deleted copy constructor and copy assignment operator, for compatibility with an old MSVC version (2013), according to the comment.
This also disables move semantics of the class, though the class *is* movable by default.

I think MSVC 2013 doesn't support declaring default move constructor, but in case there's no longer need to support that compiler (and I see the INSTALL document mentions building with VC 2019), a default move constructor and assignment operator can replace the deleted copy operators.

**Comment by pramsey** [comment]
PR would be great.
