### ISSUE TITLE
Error while building Geos Release 3.13.0 in Visual Studio for platform toolset "Visual Studio 2017(v141)"

### ISSUE THREAD

**Issue by psharma-gdal** [libgeos/geos#1172]
Following error while building geos Release 3.13.0 in Visual Studio for platform toolset "Visual Studio 2017(v141)"
 
` [exec] C:\geos-3.13.0\dist\include\geos/operation/relateng/TopologyPredicate.h(197): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable conversion) `
   
   This seems to build OK when platform toolset "v143"
   
   This file `TopologyPredicate.h` seems to be introduced in latest release only

**Comment by dr-jts** [comment]
I found a similar issue on SO [here](https://stackoverflow.com/questions/1631338/error-c2679-binary-no-operator-found-which-takes-a-right-hand-operand-of).

It recommends adding 
```
#include <string>
```
(and maybe some other standard headers).

@psharma-gdal  Can you try this and see if it fixes the problem?

**Comment by rouault** [comment]
As this is a std::ostream related operator, I believe this should rather be:

``#include <ostream>``

Cf https://en.cppreference.com/w/cpp/io/basic_ostream
