### ISSUE TITLE
Which C++ function corresponds to ST_MakeValid

### ISSUE THREAD

**Issue by afabri** [libgeos/geos#1176]
Is there a page with a mapping for this and other functions?

**Comment by pramsey** [comment]
PostGIS accesses GEOS via the GEOS C-API, you can find all the exposures in the header file, https://libgeos.org/doxygen/geos__c_8h.html

**Comment by dr-jts** [comment]
When you know what GEOS C API function is called by a PostGIS function, then look at `geos_ts_c.cpp` to see what C++ code are used to implement the functionality.

For `GEOSMakeValid` the C++ interface is [here](https://github.com/libgeos/geos/blob/main/capi/geos_ts_c.cpp#L2277).
