### ISSUE TITLE
ST_ConcaveHull does not return results containing all input points with MultiPolygon

### ISSUE THREAD

**Issue by nbvfgh** [libgeos/geos#1213]
Given following query:
```
WITH mp AS(
	SELECT ST_GeomFromText('MULTIPOLYGON (((0 0, 1 0, 2 1, 1 1, 0 0),(0 0, 1 1, 2 1, 0 0)), 
						((8 2, 8 4, 10 4, 10 2, 8 2)),
						((4 9, 5 9, 5 8, 4 8, 4 9)))'
	) geom
)
SELECT ST_Contains(ST_ConcaveHull(mp.geom, 0.3, false), mp.geom),
	   ST_AsText(ST_Difference(mp.geom, ST_ConcaveHull(mp.geom, 0.3, false)))
	   from mp;
-- expected: {true, POLYGON EMPTY}
-- acutal:   {false, MULTILINESTRING((2 1,1 1),(1 1,0 0))}
```

For polygonal inputs, the hull should enclose all the points of the input and also all the areas covered by the input. 
However, in the above query, the result set did not include all the points of the MultiPolygon input, which is not as expected.

Version info:
`GEOS="3.13.0-CAPI-1.19.0" `

**Comment by nbvfgh** [comment]
This result may be due to the input MultiPolygon being an invalid one.

**Comment by dr-jts** [comment]
> This result may be due to the input MultiPolygon being an invalid one.

Yes, Concave Hull of polygons requires the input to be valid.
