### ISSUE TITLE
Assert (0) with IsValid

### ISSUE THREAD

**Issue by andrewkatson** [libgeos/geos#260]
Hi I noticed that there is an assert(0) which is making it hard to fail from this gracefully. (https://github.com/libgeos/geos/blob/master/src/operation/valid/IsValidOp.cpp at line 603). I have been using shapely for python and it relies on this module. Occasionally, I will receive some geometry that triggers this. I have tried to reproduce it by making a multipolygon that contains two polygons. One that has a hole and the other that perfectly fits that hole. However, when calling isvalid it says false. Am I misunderstanding this edge case? Is there any reason why this has to be an assert(0)? I am just curious and would like to understand more about this.

**Comment by dr-jts** [comment]
If I understand your test case correctly, then it is indeed INVALID.  The
elements of a MultiPolygon can only have a finite number of points in
common. This means they cannot share an edge - which happens in the case of
a "polygon perfectly fitting a hole".

**Comment by andrewkatson** [comment]
Absolutely, I am just wondering why it does not function like other invalid polygons where the function will ultimately return false. At the moment, assert(0) just tells the OS to stop running the program and cannot be caught. So I am curious why this is invalid polygon is being treated so differently.

**Comment by dr-jts** [comment]
Ok, I see the problem now.  That assert is valid, because it indicates a
state that the code is assuming should not be possible - namely, that there
should be at least one point which is not shared between a hole and any
other shell.  If this is not the case then the situation should have been
detected by an earlier check in the inValid algorithm.

I'm not sure why that is happening.  It would help if you can post your
failing test data.

The code has been extensively reworked in master, but it's possible that
this situation can still occur.  Some test data would help to confirm this.

**Comment by andrewkatson** [comment]
I agree that it should be caught by an earlier check as that seems to be happening whenever I generate an artificial polygon to test this edge case. I cannot seem to trigger the assert when faking the data. The problem I am having is normally when I have some issue with a geometry I catch any exception raised and then save that failing data so I would be able to provide it. However, in this case I have a set of hundreds of thousands of geometries and during the processing of them a different intermediate geometry will trigger this (and re reunning will not trigger on ones that previously produced a failing intermediate). So, in order to provide the data I would need a process that is efficient and can catch the failing geometry.  If you have any ideas beyond the ones I have thought of please let me know. 

1. store every intermediate geometry and wait for a failure (just overwrite the last one saved)
2. run a subprocess that is passed every geometry where it checks for isvalid and then stores it if it fails (would need script A --- geom --> script B  and script A waits for a response and can then check for the OS error cause by this issue). This would replace calling isValid in script A as it does now. 

Which do you think is that fastest method?

**Comment by dr-jts** [comment]
Yikes, sounds like a Heisenbug!  May be hard to capture, in that case. Your
first approach to capturing a specimen sounds reasonable, but without
knowing the details of your code it's hard to say whether how much work
that would be.

**Comment by andrewkatson** [comment]
I think it should not be too hard to implement. I would just divert every check like geom.is_valid to be like safe_is_valid(geom) where safe_is_valid stores the geometry and then checks validity. So nothing bad. It will just take a while to run (maybe 2-3 days) before the issue surfaces. I can go try that and let you know how it goes should it happen. And I'll have an update then. :)

**Comment by dbaston** [comment]
I could make you a shapely build (in a Docker container) that would have the assert changed to an exception. Would that help?

**Comment by dbaston** [comment]
Looks like I had been planning to throw here anyway; see https://github.com/libgeos/geos/commit/b679eca65dc9fa0ffa1a80fb3fd00bbfce466edd

**Comment by andrewkatson** [comment]
Sorry for the delay. I would like to have a container with that build if it is not too much trouble :) thank you

**Comment by dbaston** [comment]
Sure, maybe `dbaston/geos-shapely` will help. (https://hub.docker.com/r/dbaston/geos-shapely)

Thanks for your effort.

**Comment by andrewkatson** [comment]
Dan, just an update. I am going to try using your solution. But I will continue to run my version until it hits this error again for future reference. Then I will switch to yours. :)
