### ISSUE TITLE
CMake config exports path causing compilation problems on MSVC

### ISSUE THREAD

**Issue by dirkvdb** [libgeos/geos#262]
The cmake target include directories for geos and geos_c add the geos subdirectory to the install interface:

```
target_include_directories(geos_c
PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
    $<INSTALL_INTERFACE:include/geos>)
```
This directory contains the very generic io.h which clashes on windows with io.h header from the windows sdk.

I think the ` $<INSTALL_INTERFACE:include/geos>` entry should be removed as includes of the c++ api are done with geos/ prefix anyway.

same for the geos target.

**Comment by strk** [comment]
Please report your issue on http://trac.osgeo.org/geos

**Comment by JackBoosY** [comment]
Should be fixed in PR https://github.com/libgeos/geos/pull/242
