### ISSUE TITLE
makevalid failure

### ISSUE THREAD

**Issue by manuel76413** [libgeos/geos#265]
std::vector<Coordinate> v;
  v.push_back(Coordinate(2.22, 2.28));
  v.push_back(Coordinate(7.67, 2.06));
  v.push_back(Coordinate(10.98, 7.70));
  v.push_back(Coordinate(9.39, 5.00));
  v.push_back(Coordinate(7.96, 7.12));
  v.push_back(Coordinate(6.77, 5.16));
  v.push_back(Coordinate(7.43, 6.24));
  v.push_back(Coordinate(3.70, 7.22));
  v.push_back(Coordinate(5.72, 5.77));
  v.push_back(Coordinate(4.18, 10.74));
  v.push_back(Coordinate(2.20, 6.83));
  v.push_back(Coordinate(2.22, 2.28));

  geos::geom::Polygon* errplyg = MakePolygon(v);
  wkt_print_geom(errplyg);
  MakeValid mkvalid;
  try {
    auto validGeom = mkvalid.build(errplyg);
    wkt_print_geom(validGeom.get());
  } catch (const GEOSException& exc) {
    cerr << "GEOS Exception: " << exc.what() << "\n";
    exit(1);
  } catch (const exception& e) {
    cerr << "Standard exception thrown: " << e.what() << endl;
    exit(1);
  }
  // and this is a catch-all non standard ;)
  catch (...) {
    cerr << "unknown exception trown!\n";
    exit(1);
  }
/////////////
raise debug assertion failed in mkvalid.build(errplyg), error :
...\include\vector Line: 1742
Expression: vector subscript out of range

**Comment by dbaston** [comment]
I'm guessing this is on MSVC?

**Comment by manuel76413** [comment]
> I'm guessing this is on MSVC?

Yes,  compiled on MSVC, raise assertion, anybody know how to correct this?

**Comment by dbaston** [comment]
I can't reproduce it with MSVC 2019 Community. Do I need to do something other than import the CMake project and run the tests on a x64-Debug build?

**Comment by pramsey** [comment]
Try the new MakeValid implementation option as another work-around.
