### ISSUE TITLE
Unit of distance.

### ISSUE THREAD

**Issue by gorishaa9** [libgeos/geos#294]
Hi, 

I am finding hard to understand the unit of `double distance`, the width of the `buffer` around a geometry. When I am trying to form a buffer around a linestring or any geometry, what units should the width of the buffer be? Please let me know.

Thanks.

**Comment by dr-jts** [comment]
The unit of distance is the same as whatever the unit of distance is in the
underlying coordinate system of the coordinates.  GEOS does not represent
this explicitly; it is up to the user to determine this.

GEOS also assumes a planar coordinates system. Note that this means that
for geographic coordinates the unit of distance is degrees, which generally
does not produce accurate answers.
