### ISSUE TITLE
Crash in GEOSDistance_r

### ISSUE THREAD

**Issue by nyalldawson** [libgeos/geos#295]
Given the polygon with WKT:

    MultiPolygonZ (PolygonZ EMPTY,((-0.14000000000000001 44.89999999999999858 0, -0.14699999999999999 44.90400000000000347 0, -0.14729999999999999 44.90500000000000114 0, -0.14000000000000001 44.89999999999999858 0)))

Attempting to find the distance to any other polygon geometries using GEOSDistance_r results in a crash from within geos::operation::distance::GeometryLocation

(Likely it's due to the empty polygon member, but this should raise a GEOSException instead of crashing.)

Reported downstream as https://github.com/qgis/QGIS/issues/35149

**Comment by dbaston** [comment]
Failing test in https://github.com/dbaston/libgeos/commit/8096b0da2127e78112582688cafbcad0457fcf9c

Looks like GEOS has some longstanding differences relative to JTS on whether a `GeometryLocation` can have a null coordinate.

**Comment by dr-jts** [comment]
Looks like this fails in JTS as well.  Empty geometries are a right royal pain.

Will log this as an issue.  Good news is that the fix is likely simple.

**Comment by dr-jts** [comment]
See JTS [524](https://github.com/locationtech/jts/pull/524).

**Comment by pramsey** [comment]
This should be fixed in master and 3.8.

2ac00b1c5ae669c384d78155cbf94042d0fc90b0
