### ISSUE TITLE
Length of the Geometry.

### ISSUE THREAD

**Issue by gorishaa9** [libgeos/geos#297]
Hi,

I am creating a `LineString` object using `GeometryFactory` and specifying a `PrecisionModel`. I do that as follows:
`PrecisionModel* pm = new PrecisionModel(10000);`
`auto global_factory = GeometryFactory::create(pm, 3857)`

The `CoordinateArraySequence` contains geographical coordinates in decimal degrees, the longitude and latitude. The `LineString` is created as follows:
`const Geometry* ls = global_factory->createLineString(cl);`, where
`cl` is the `CoordinateArraySequence*`. 

When I do `ls->getLength()`, the length I see is wrong. It gives me some garbage values. Where am I going wrong?

Any help will be greatly appreciated. Thanks.

**Comment by dbaston** [comment]
GEOS works in on the Cartesian (XY) plane only. The SRID is not considered in any calculations.
