### ISSUE TITLE
Crash in WKT of MultiPoint including an empty Point

### ISSUE THREAD

**Issue by jorisvandenbossche** [libgeos/geos#305]
Using the Python `pygeos` package to show the error (from https://github.com/pygeos/pygeos/issues/134):

```python
# creating a MultiPoint with that includes an empty Point
import pygeos

point = pygeos.points(1,1)  
box = pygeos.box(2,2,4,4) 
point_empty = pygeos.intersection(p, box)

mp_empty  = pygeos.multipoints([point, point_empty])                  
```

Converting to WKB raises an informative error:
```
>>> pygeos.to_wkb(mp_empty)      
...
GEOSException: IllegalArgumentException: Empty Points cannot be represented in WKB
```

However, converting to WKT crashes:

```
>>> pygeos.to_wkt(mp_empty)    
Segmentation fault (core dumped)
```

I am not 100% sure this is a GEOS issue, since there might be something wrong on the PyGEOS side. But posting here in case somebody knows or can confirm this is a GEOS bug.

**Comment by pramsey** [comment]
https://trac.osgeo.org/geos/ticket/1027

**Comment by pramsey** [comment]
Patched in 3.7, 3.8, master.

a73568cc

**Comment by jorisvandenbossche** [comment]
Thanks for the quick fix!

One thing I am wondering, is the reading of such WKT output supported? (or *should* it be supported?)

```
In [5]: pygeos.from_wkt("MULTIPOINT (EMPTY, 1 2)")  
---------------------------------------------------------------------------
GEOSException                             Traceback (most recent call last)
<ipython-input-5-8a845f13df47> in <module>
----> 1 pygeos.from_wkt("MULTIPOINT(EMPTY, 1 1)")

~/scipy/repos/pygeos/pygeos/io.py in from_wkt(geometry, **kwargs)
    158     <pygeos.Geometry POINT (0 0)>
    159     """
--> 160     return lib.from_wkt(geometry, **kwargs)
    161 
    162 

GEOSException: ParseException: Unexpected token: WORD EMPTY
```

(using GEOS 3.8.0)

**Comment by pramsey** [comment]
Current reading it is not supported. JTS does not read it either. PostGIS does. Hard call. It would have been way easier to write the test if reading was supported. :)

**Comment by jorisvandenbossche** [comment]
I would vote (if it mattered ;)) for consistency within GEOS: either support it for both reading and writing, or not support it. It could also raise with a nice error message (like writing to WKB does), instead of crashing as before.

Personally, I think it would be nice to have some of the extensions that are in PostGIS in GEOS (also eg for WKB of empty points), instead of having PostGIS, sf, Shapely, etc all implement their own similar workaround.
