### ISSUE TITLE
GEOSWithin gives bad results on big endian architectures (s390x)

### ISSUE THREAD

**Issue by hroncok** [libgeos/geos#323]
Hello. In Fedora, we build geos for various architectures. One of them is s390x, which is big endian.

Python package [Shapely](https://pypi.org/project/Shapely/) was failing some tests on thich architecture and we tracked the problem to the following reporducer:

```c
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <geos_c.h>

static void message_handler(const char *fmt, ...)
{
  va_list ap;

  va_start(ap, fmt);
  vfprintf(stderr, fmt, ap);
  putc('\n', stderr);
  va_end(ap);
}

int main()
{
  GEOSCoordSeq polygon1, polygon2;
  GEOSGeom ring1, ring2;
  GEOSGeom poly1, poly2;
  char result;

  // Initialization
  initGEOS(message_handler, message_handler);

  // Create the first polygon
  polygon1 = GEOSCoordSeq_create(10, 2);
  GEOSCoordSeq_setX(polygon1,  0, 339);
  GEOSCoordSeq_setY(polygon1,  0, 346);
  GEOSCoordSeq_setX(polygon1,  1, 459);
  GEOSCoordSeq_setY(polygon1,  1, 346);
  GEOSCoordSeq_setX(polygon1,  2, 399);
  GEOSCoordSeq_setY(polygon1,  2, 311);
  GEOSCoordSeq_setX(polygon1,  3, 340);
  GEOSCoordSeq_setY(polygon1,  3, 277);
  GEOSCoordSeq_setX(polygon1,  4, 399);
  GEOSCoordSeq_setY(polygon1,  4, 173);
  GEOSCoordSeq_setX(polygon1,  5, 280);
  GEOSCoordSeq_setY(polygon1,  5, 242);
  GEOSCoordSeq_setX(polygon1,  6, 339);
  GEOSCoordSeq_setY(polygon1,  6, 415);
  GEOSCoordSeq_setX(polygon1,  7, 280);
  GEOSCoordSeq_setY(polygon1,  7, 381);
  GEOSCoordSeq_setX(polygon1,  8, 460);
  GEOSCoordSeq_setY(polygon1,  8, 207);
  GEOSCoordSeq_setX(polygon1,  9, 339);
  GEOSCoordSeq_setY(polygon1,  9, 346);
  ring1 = GEOSGeom_createLinearRing(polygon1);
  poly1 = GEOSGeom_createPolygon(ring1, NULL, 0);

  // Create the second polygon
  polygon2 = GEOSCoordSeq_create(12, 2);
  GEOSCoordSeq_setX(polygon2,  0, 339);
  GEOSCoordSeq_setY(polygon2,  0, 207);
  GEOSCoordSeq_setX(polygon2,  1, 280);
  GEOSCoordSeq_setY(polygon2,  1, 311);
  GEOSCoordSeq_setX(polygon2,  2, 460);
  GEOSCoordSeq_setY(polygon2,  2, 138);
  GEOSCoordSeq_setX(polygon2,  3, 399);
  GEOSCoordSeq_setY(polygon2,  3, 242);
  GEOSCoordSeq_setX(polygon2,  4, 459);
  GEOSCoordSeq_setY(polygon2,  4, 277);
  GEOSCoordSeq_setX(polygon2,  5, 459);
  GEOSCoordSeq_setY(polygon2,  5, 415);
  GEOSCoordSeq_setX(polygon2,  6, 399);
  GEOSCoordSeq_setY(polygon2,  6, 381);
  GEOSCoordSeq_setX(polygon2,  7, 519);
  GEOSCoordSeq_setY(polygon2,  7, 311);
  GEOSCoordSeq_setX(polygon2,  8, 520);
  GEOSCoordSeq_setY(polygon2,  8, 242);
  GEOSCoordSeq_setX(polygon2,  9, 519);
  GEOSCoordSeq_setY(polygon2,  9, 173);
  GEOSCoordSeq_setX(polygon2, 10, 399);
  GEOSCoordSeq_setY(polygon2, 10, 450);
  GEOSCoordSeq_setX(polygon2, 11, 339);
  GEOSCoordSeq_setY(polygon2, 11, 207);
  ring2 = GEOSGeom_createLinearRing(polygon2);
  poly2 = GEOSGeom_createPolygon(ring2, NULL, 0);

  // Check whether the second polygon is within the first
  result = GEOSWithin(poly1, poly2);
  printf("The result is %d\n", (int)result);

  // Cleanup
  GEOSGeom_destroy(poly1);
  GEOSGeom_destroy(poly2);
  finishGEOS();
  return EXIT_SUCCESS;
}
```

The code is a C translation of one of the failing Shapely tests.  It shows that the bug is not caused by Shapely.  Build it with `gcc -o test test.c -lgeos_c`.  If built and run on a little endian machine, it correctly produces this output:

```
TopologyException: side location conflict at 459 346
The result is 2
```

If built and run on s390x (big endian), it incorrectly produces this output:

```
The result is 0
```

Since this was not an issue in the past, we've bisected the problem to https://git.osgeo.org/gitea/geos/geos/commit/10ff0f8d6809c212aa9eb75f710bd068a90ccff0 -- likely, the DD class itself being the issue.

See the downstream report in https://bugzilla.redhat.com/show_bug.cgi?id=1841335

I will report this to https://trac.osgeo.org/geos/report/1 once I get an account there.

**Comment by dr-jts** [comment]
Odd, since those are wildly invalid geometries.

Here is the WKT:

A:
```
POLYGON ((339 346, 459 346, 399 311, 340 277, 399 173, 280 242, 339 415, 280 381, 460 207, 339 346))
```
B
```
POLYGON ((339 207, 280 311, 460 138, 399 242, 459 277, 459 415, 399 381, 519 311, 520 242, 519 173, 399 450, 339 207))
```

**Comment by sharkcz** [comment]
If a developer needs access to a big endian system to investigate this issue, please let me know.

**Comment by pramsey** [comment]
* is this against master (I assume so)
* do all the other GEOS tests work on big endian?
* what happens against 3.8 (my guess, nothing works at all, because ttmath barfs on big endian, but I'd like a confirmation)
* a big endian system would be very helpful for these issues, yes

**Comment by dbaston** [comment]
> do all the other GEOS tests work on big endian?

see https://travis-ci.com/github/libgeos/geos/jobs/331329852, from https://github.com/libgeos/geos/pull/322

**Comment by dr-jts** [comment]
A comment: technically speaking the result of 2 (error) and 0 (false) are both correct, since the output from spatial predicates on invalid geometries is undefined.

It would be good to find out why the output is different for big-endian, though.

There may not be a GEOS test which specifically tests the result from invalid geometries?

Does every big-endian architecture produce the same result?

**Comment by dr-jts** [comment]
I also see these comments in the original [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1841335):

> and indeed, many tests fail on s390x.

> the problem is that newly added tests were immediately failing on those arches, so the actual code may have already been broken on those arches way before...

This makes me wonder if there is a bigger issue wrong, and we should look at all failures before narrowing in on a possible cause.

Is it possible that the Travis s390x environment is somehow different to the one being used in the original issue?

**Comment by hroncok** [comment]
I'll try to answer as many questions as possible, but let me have my own answer: Should or should I not open the trac ticket? It's more comfortable for me to continue the conversation here, but I don't want to leave anybody out.

> is this against master (I assume so)

Since 10ff0f8d6809c212aa9eb75f710bd068a90ccff0 until 099e74b3127348e1f8544ab279b609e2fdc6cc74 (current master), it behaves this way.

> do all the other GEOS tests work on big endian?

The tests used to be skipped altogether in the past, recently the results are ignored (they don't abort the RPM package build).

Latest [test build with 099e74b](https://koji.fedoraproject.org/koji/taskinfo?taskID=45318460) fails on aarch64, ppc64le, s390x, succeeds on armv7hl, i686, x86_64. The s390x failures are:

```
The following tests FAILED:
	 11 - unit-algorithm-LocatePointInRing (Failed)
	 14 - unit-algorithm-OrientationIndexFailure (Failed)
	 17 - unit-algorithm-RobustLineIntersector (Failed)
	 72 - unit-capi-GEOSVoronoiDiagram (Failed)
	104 - unit-geom-Triangle (Failed)
	117 - unit-linearref-LengthIndexedLine (Failed)
	118 - unit-math-DD (Failed)
	130 - unit-operation-distance-DistanceOp (Failed)
	165 - general-TestCentroid (Failed)
	179 - general-TestFunctionPLPrec (Failed)
	210 - issue-issue-geos-350 (Failed)
	257 - robust-TestRobustRelate (Failed)
```

> what happens against 3.8

The [real build with 3.8.1](https://koji.fedoraproject.org/koji/buildinfo?buildID=1476560) succeeded on all architectures because the test result was ignored. Inspection of the logs reveals that:

 - 100% tests passed on x86_64, i686, armv7hl
 - 98% tests passed, 4 tests failed out of 260 on ppc64l, aarch64  (tests 68, 112, 158, 203)
 - 90% tests passed, 27 tests failed out of 260 on s390x:

```
The following tests FAILED:
	 11 - unit-algorithm-LocatePointInRing (Failed)
	 13 - unit-algorithm-MinimumDiameter (Failed)
	 14 - unit-algorithm-OrientationIndexFailure (Failed)
	 16 - unit-algorithm-RobustLineIntersection (Failed)
	 17 - unit-algorithm-RobustLineIntersector (Failed)
	 68 - unit-capi-GEOSVoronoiDiagram (SEGFAULT)
	100 - unit-geom-Triangle (Failed)
	112 - unit-linearref-LengthIndexedLine (Failed)
	140 - unit-operation-valid-IsValidOp (Failed)
	150 - unit-triangulate-Voronoi (Failed)
	158 - general-TestCentroid (Failed)
	160 - general-TestConvexHull (Failed)
	164 - general-TestFunctionAA (Failed)
	168 - general-TestFunctionLL (Failed)
	170 - general-TestFunctionPA (Failed)
	182 - general-TestRelateAA (Failed)
	183 - general-TestRelateAC (Failed)
	186 - general-TestRelateLL (Failed)
	203 - issue-issue-geos-350 (Failed)
	227 - misc-InvalidRelates (Failed)
	243 - misc-safe-TestBufferJagged (Failed)
	252 - validate-TestRelateAA (Failed)
	253 - validate-TestRelateAC (Failed)
	254 - validate-TestRelateLA (Failed)
	256 - validate-TestRelateLL (Failed)
	257 - validate-TestRelatePA (Failed)
	258 - validate-TestRelatePL (Failed)
```

> Does every big-endian architecture produce the same result?

Unfortunately, Fedora longer supports any other BE architecture, so I don't know.

> To elaborate on my comment above, I don't think Shapely should be relying on specific output from GEOS for invalid inputs.

The failing tests of Shapely are:

```
======================================================================
FAIL: test_topological_error (tests.test_iterops.IterOpsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Shapely-1.7b1/tests/test_iterops.py", line 69, in test_topological_error
    list(iterops.within(polygon1, [polygon2]))
AssertionError: TopologicalError not raised
======================================================================
FAIL: test_binary_predicate_exceptions (tests.test_predicates.PredicatesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Shapely-1.7b1/tests/test_predicates.py", line 42, in test_binary_predicate_exceptions
    self.assertRaises(TopologicalError, Polygon(p1).within, Polygon(p2))
AssertionError: TopologicalError not raised by within
======================================================================
FAIL: test_split_line_with_line (tests.test_split.TestSplitLine)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Shapely-1.7b1/tests/test_split.py", line 122, in test_split_line_with_line
    self.assertTrue(splitter.touches(self.ls))
AssertionError: False is not true
----------------------------------------------------------------------
Ran 225 tests in 0.633s
FAILED (failures=3, skipped=1)
```

https://github.com/Toblerity/Shapely/blob/1.7.0/tests/test_iterops.py#L58
https://github.com/Toblerity/Shapely/blob/1.7.0/tests/test_predicates.py#L35
https://github.com/Toblerity/Shapely/blob/1.7.0/tests/test_split.py#L102

Do the tests in Shapely also contain invalid inputs? Should the test be amended? Note that 2 of the 3 tests failures are "TopologicalError not raised" hence I suppose the invalid input is on purpose.

> Is it possible that the Travis s390x environment is somehow different to the one being used in the original issue?

It is possible that Travis uses a virtualized s390x environment. Fedora builders use real s390x hardware. I don't know if this could manifest in such difference or not.


Thanks for your fast response, it is really appreciated.

**Comment by hroncok** [comment]
>> is this against master (I assume so)
> 
> Since 10ff0f8d6809c212aa9eb75f710bd068a90ccff0 until 099e74b3127348e1f8544ab279b609e2fdc6cc74 (current master), it behaves this way.

I stand corrected, this might actually be fixed on current master. Let me recheck.

**Comment by sharkcz** [comment]
AFAIK Travis uses IBM Cloud resources for s390x and ppc64le arches, so there shouldn't be difference caused by the hw.

**Comment by hroncok** [comment]
bed36f15c780057ae9b83eb9cd2e8ef6a9ada498 is the fixer of the C reproducer. Not sure if it fixes shapely.

**Comment by dr-jts** [comment]
> [bed36f1](https://github.com/libgeos/geos/commit/bed36f15c780057ae9b83eb9cd2e8ef6a9ada498) is the fixer of the C reproducer. Not sure if it fixes shapely.

Are you saying that GEOS now works correctly, since `DD` replaced `ttmath`?

**Comment by hroncok** [comment]
Disclaimer: I am the Fedora's Python maintainer, I don't understand GEOS. I am saying that the reproducer is fixed, not that GEOS works correctly.

**Comment by hroncok** [comment]
If backporting bed36f1 fixes the Shapely test problem, do you want me to reuse this to hunt down the remaining test failures, or close as fixed?

**Comment by dr-jts** [comment]
> If backporting [bed36f1](https://github.com/libgeos/geos/commit/bed36f15c780057ae9b83eb9cd2e8ef6a9ada498) fixes the Shapely test problem, do you want me to reuse this to hunt down the remaining test failures, or close as fixed?

It would be good to confirm if  [bed36f1](https://github.com/libgeos/geos/commit/bed36f15c780057ae9b83eb9cd2e8ef6a9ada498) fixes all the Shapely tests.  If so, that indicates that GEOS is now working correctly on the s390 BE architecture (as the GEOS CI has indicated for us).

GEOS 3.8 and earlier did not work on BE, so if those tests were only recently turned on then it's not surprising that there are failures when using that version.

**Comment by hroncok** [comment]
> It would be good to confirm if bed36f1 fixes all the Shapely tests.

Working on it. However, I'm calling it a day. Hopefully I will be able to verify it tomorrow.

Thanks for all the help provided here, always a pleasure to iterate fast with upstreams.

**Comment by dr-jts** [comment]
Our pleasure - you are helping us improve the GEOS project, which is great.

**Comment by pramsey** [comment]
For your information with regard to the problems / solutions:

* GEOS 3.8 by default uses the 'ttmath' package for higher precision math support which includes a good deal of ASM and assumptions about architecture
* GEOS master (3.9) switched to using the 'DD' class and a pure-C++ implementation
* GEOS 3.8 branch had DD added, but not **enabled** by default. I attempted to add some configure rules to turn swap in DD for ttmath when big endian architecture was detected, but had to platform on which to test them.

GEOS master seems to [pass all tests](https://travis-ci.com/github/libgeos/geos/jobs/331329852) using DD on s390. 

If GEOS 3.8 branch is not passing all tests, we should ensure that the configure switch is working for the s390 build.

**Comment by hroncok** [comment]
First of all, backporting bed36f1 to 3.8.1 fixes all the Shapely tests :fireworks: 

With that, we still see some test failures on aarch64, ppc64le and s390x.

But at least this time the failures are identical across the three architectures:

```
95% tests passed, 12 tests failed out of 261
Total Test time (real) =   7.70 sec
The following tests FAILED:
	 11 - unit-algorithm-LocatePointInRing (Failed)
	 14 - unit-algorithm-OrientationIndexFailure (Failed)
	 17 - unit-algorithm-RobustLineIntersector (Failed)
	 68 - unit-capi-GEOSVoronoiDiagram (Failed)
	100 - unit-geom-Triangle (Failed)
	112 - unit-linearref-LengthIndexedLine (Failed)
	113 - unit-math-DD (Failed)
	125 - unit-operation-distance-DistanceOp (Failed)
	159 - general-TestCentroid (Failed)
	173 - general-TestFunctionPLPrec (Failed)
	204 - issue-issue-geos-350 (Failed)
	251 - robust-TestRobustRelate (Failed)
```

I wonder why we get the failures and you don't.

This is the list of installed packages and their versions, when we build geos:

```
adobe-mappings-cmap-20171205-7.fc32.noarch
adobe-mappings-cmap-deprecated-20171205-7.fc32.noarch
adobe-mappings-pdf-20180407-5.fc32.noarch
alternatives-1.11-6.fc32.s390x
annobin-9.22-1.fc33.s390x
atk-2.36.0-1.fc33.s390x
audit-libs-3.0-0.20.20191104git1c2f876.fc33.s390x
avahi-libs-0.8-2.fc33.s390x
basesystem-11-9.fc32.noarch
bash-5.0.17-1.fc33.s390x
binutils-2.34.0-7.fc33.s390x
binutils-gold-2.34.0-7.fc33.s390x
bzip2-1.0.8-2.fc32.s390x
bzip2-libs-1.0.8-2.fc32.s390x
ca-certificates-2020.2.41-3.fc33.noarch
cairo-1.16.0-8.fc33.s390x
cairo-gobject-1.16.0-8.fc33.s390x
cmake-3.17.3-2.fc33.s390x
cmake-data-3.17.3-2.fc33.noarch
cmake-filesystem-3.17.3-2.fc33.s390x
cmake-rpm-macros-3.17.3-2.fc33.noarch
coreutils-8.32-6.fc33.s390x
coreutils-common-8.32-6.fc33.s390x
cpio-2.13-5.fc33.s390x
cpp-10.1.1-1.fc33.s390x
cracklib-2.9.6-22.fc32.s390x
crypto-policies-20200610-1.git7f9d474.fc33.noarch
cups-libs-2.3.3-6.fc33.s390x
curl-7.70.0-1.fc33.s390x
cyrus-sasl-lib-2.1.27-5.fc33.s390x
dbus-libs-1.12.18-1.fc33.s390x
dejavu-sans-fonts-2.37-12.fc33.noarch
diffutils-3.7-4.fc32.s390x
doxygen-1.8.18-2.fc33.s390x
dwz-0.13-2.fc32.s390x
efi-srpm-macros-4-4.fc32.noarch
elfutils-0.180-2.fc33.s390x
elfutils-default-yama-scope-0.180-2.fc33.noarch
elfutils-libelf-0.180-2.fc33.s390x
elfutils-libs-0.180-2.fc33.s390x
emacs-filesystem-26.3-3.fc33.noarch
expat-2.2.8-2.fc32.s390x
fedora-gpg-keys-33-0.6.noarch
fedora-release-33-0.9.noarch
fedora-release-common-33-0.9.noarch
fedora-release-identity-basic-33-0.9.noarch
fedora-repos-33-0.6.noarch
fedora-repos-rawhide-33-0.6.noarch
file-5.38-6.fc33.s390x
file-libs-5.38-6.fc33.s390x
filesystem-3.14-2.fc32.s390x
findutils-4.7.0-4.fc33.s390x
fontconfig-2.13.92-11.fc33.s390x
fonts-filesystem-2.0.5-3.fc33.noarch
fonts-srpm-macros-2.0.5-3.fc33.noarch
fpc-srpm-macros-1.3-1.fc32.noarch
freetype-2.10.1-2.fc32.s390x
fribidi-1.0.9-1.fc33.s390x
gawk-5.0.1-7.fc32.s390x
gc-8.0.4-3.fc32.s390x
gcc-10.1.1-1.fc33.s390x
gcc-c++-10.1.1-1.fc33.s390x
gd-2.3.0-1.fc33.s390x
gdb-minimal-9.1-8.fc33.s390x
gdbm-libs-1.18.1-3.fc32.s390x
gdk-pixbuf2-2.40.0-2.fc32.s390x
gdk-pixbuf2-modules-2.40.0-2.fc32.s390x
ghc-srpm-macros-1.5.0-2.fc32.noarch
glib2-2.64.3-1.fc33.s390x
glibc-2.31.9000-14.fc33.s390x
glibc-common-2.31.9000-14.fc33.s390x
glibc-devel-2.31.9000-14.fc33.s390x
glibc-headers-s390-2.31.9000-14.fc33.noarch
glibc-minimal-langpack-2.31.9000-14.fc33.s390x
gmp-6.2.0-1.fc33.s390x
gnat-srpm-macros-4-11.fc32.noarch
gnutls-3.6.14-2.fc33.s390x
go-srpm-macros-3.0.8-5.fc32.noarch
google-droid-sans-fonts-20200215-5.fc33.noarch
graphite2-1.3.14-2.fc33.s390x
graphviz-2.44.0-8.fc33.s390x
grep-3.4-1.fc33.s390x
gtk-update-icon-cache-3.24.20-1.fc33.s390x
gtk2-2.24.32-7.fc32.s390x
gts-0.7.6-37.20121130.fc32.s390x
guile22-2.2.6-4.fc32.s390x
gzip-1.10-2.fc32.s390x
harfbuzz-2.6.7-1.fc33.s390x
hicolor-icon-theme-0.17-8.fc32.noarch
info-6.7-7.fc33.s390x
isl-0.16.1-10.fc32.s390x
jasper-libs-2.0.16-2.fc32.s390x
jbig2dec-libs-0.18-1.fc33.s390x
jbigkit-libs-2.1-18.fc32.s390x
jsoncpp-1.9.3-1.fc33.s390x
kernel-headers-5.8.0-0.rc1.git0.1.fc33.s390x
keyutils-libs-1.6-4.fc32.s390x
krb5-libs-1.18.2-9.fc33.s390x
langpacks-core-font-en-3.0-3.fc33.noarch
lasi-1.1.3-2.fc32.s390x
lcms2-2.10-1.fc33.s390x
libICE-1.0.10-3.fc32.s390x
libSM-1.2.3-5.fc32.s390x
libX11-1.6.9-3.fc32.s390x
libX11-common-1.6.9-3.fc32.noarch
libXau-1.0.9-3.fc32.s390x
libXaw-1.0.13-14.fc32.s390x
libXcomposite-0.4.5-2.fc32.s390x
libXcursor-1.2.0-2.fc32.s390x
libXdamage-1.1.5-2.fc32.s390x
libXext-1.3.4-3.fc32.s390x
libXfixes-5.0.3-11.fc32.s390x
libXft-2.3.3-3.fc32.s390x
libXi-1.7.10-3.fc32.s390x
libXinerama-1.1.4-5.fc32.s390x
libXmu-1.1.3-3.fc32.s390x
libXpm-3.5.13-2.fc32.s390x
libXrandr-1.5.2-3.fc32.s390x
libXrender-0.9.10-11.fc32.s390x
libXt-1.2.0-1.fc32.s390x
libXxf86vm-1.1.4-13.fc32.s390x
libacl-2.2.53-6.fc33.s390x
libarchive-3.4.3-1.fc33.s390x
libasan-10.1.1-1.fc33.s390x
libatomic-10.1.1-1.fc33.s390x
libattr-2.4.48-8.fc32.s390x
libblkid-2.35.2-2.fc33.s390x
libbrotli-1.0.7-11.fc33.s390x
libcap-2.26-7.fc32.s390x
libcap-ng-0.7.10-3.fc33.s390x
libcom_err-1.45.6-2.fc33.s390x
libcurl-7.70.0-1.fc33.s390x
libdatrie-0.2.9-11.fc32.s390x
libdb-5.3.28-40.fc32.s390x
libevent-2.1.8-8.fc32.s390x
libfdisk-2.35.2-2.fc33.s390x
libffi-3.1-25.fc33.s390x
libfontenc-1.1.3-12.fc32.s390x
libgcc-10.1.1-1.fc33.s390x
libgcrypt-1.8.5-6.fc33.s390x
libgomp-10.1.1-1.fc33.s390x
libgpg-error-1.37-1.fc33.s390x
libgs-9.52-4.fc33.s390x
libidn-1.35-7.fc32.s390x
libidn2-2.3.0-2.fc32.s390x
libijs-0.35-11.fc32.s390x
libimagequant-2.12.6-2.fc32.s390x
libjpeg-turbo-2.0.4-3.fc33.s390x
libmcpp-2.7.2-25.fc32.s390x
libmetalink-0.1.3-10.fc32.s390x
libmount-2.35.2-2.fc33.s390x
libmpc-1.1.0-8.fc32.s390x
libnghttp2-1.41.0-1.fc33.s390x
libnsl2-1.2.0-6.20180605git4a062cf.fc32.s390x
libpaper-1.1.24-26.fc32.s390x
libpkgconf-1.7.0-1.fc33.s390x
libpng-1.6.37-3.fc32.s390x
libpsl-0.21.0-4.fc32.s390x
libpwquality-1.4.2-3.fc33.s390x
libraqm-0.7.0-5.fc32.s390x
librsvg2-2.48.7-1.fc33.s390x
libselinux-3.0-5.fc33.s390x
libsemanage-3.0-4.fc33.s390x
libsepol-3.0-3.fc32.s390x
libsigsegv-2.11-10.fc32.s390x
libsmartcols-2.35.2-2.fc33.s390x
libssh-0.9.4-2.fc33.s390x
libssh-config-0.9.4-2.fc33.noarch
libstdc++-10.1.1-1.fc33.s390x
libstdc++-devel-10.1.1-1.fc33.s390x
libtasn1-4.16.0-1.fc32.s390x
libthai-0.1.28-4.fc32.s390x
libtiff-4.1.0-2.fc32.s390x
libtirpc-1.2.6-0.fc33.s390x
libtool-ltdl-2.4.6-34.fc33.s390x
libubsan-10.1.1-1.fc33.s390x
libunistring-0.9.10-7.fc32.s390x
libutempter-1.2.0-1.fc33.s390x
libuuid-2.35.2-2.fc33.s390x
libuv-1.38.0-2.fc33.s390x
libverto-0.3.0-9.fc32.s390x
libwebp-1.1.0-3.fc33.s390x
libxcb-1.13.1-4.fc32.s390x
libxcrypt-4.4.16-3.fc33.s390x
libxcrypt-devel-4.4.16-3.fc33.s390x
libxml2-2.9.10-5.fc33.s390x
libzstd-1.4.5-3.fc33.s390x
lua-libs-5.3.5-7.fc32.s390x
lz4-libs-1.9.1-2.fc32.s390x
make-4.3-1.fc33.s390x
mcpp-2.7.2-25.fc32.s390x
mpfr-4.0.2-4.fc33.s390x
ncurses-6.2-1.20200222.fc33.s390x
ncurses-base-6.2-1.20200222.fc33.noarch
ncurses-libs-6.2-1.20200222.fc33.s390x
netpbm-10.90.00-1.fc33.s390x
nettle-3.6-1.fc33.s390x
nim-srpm-macros-3-2.fc32.noarch
ocaml-srpm-macros-6-2.fc32.noarch
openblas-srpm-macros-2-7.fc32.noarch
openjpeg2-2.3.1-6.fc33.s390x
openldap-2.4.47-4.fc32.s390x
openssl-libs-1.1.1g-9.fc33.s390x
p11-kit-0.23.20-1.fc32.s390x
p11-kit-trust-0.23.20-1.fc32.s390x
pam-1.3.1-26.fc33.s390x
pango-1.45.2-1.fc33.s390x
patch-2.7.6-12.fc32.s390x
pcre-8.44-1.fc33.s390x
pcre2-10.35-3.fc33.s390x
pcre2-syntax-10.35-3.fc33.noarch
perl-Carp-1.50-440.fc32.noarch
perl-Errno-1.30-454.fc33.s390x
perl-Exporter-5.74-2.fc32.noarch
perl-PathTools-3.78-441.fc32.s390x
perl-Scalar-List-Utils-1.55-441.fc33.s390x
perl-constant-1.33-441.fc32.noarch
perl-interpreter-5.30.3-454.fc33.s390x
perl-libs-5.30.3-454.fc33.s390x
perl-macros-5.30.3-454.fc33.noarch
perl-srpm-macros-1-34.fc32.noarch
pixman-0.40.0-1.fc33.s390x
pkgconf-1.7.0-1.fc33.s390x
pkgconf-m4-1.7.0-1.fc33.noarch
pkgconf-pkg-config-1.7.0-1.fc33.s390x
popt-1.18~rc1-1.fc33.s390x
publicsuffix-list-dafsa-20190417-3.fc32.noarch
python-pip-wheel-20.1.1-3.fc33.noarch
python-setuptools-wheel-47.1.1-1.fc33.noarch
python-srpm-macros-3.9-4.fc33.noarch
python3-3.9.0~b3-1.fc33.s390x
python3-libs-3.9.0~b3-1.fc33.s390x
qt5-srpm-macros-5.14.2-3.fc33.noarch
readline-8.0-4.fc32.s390x
redhat-rpm-config-161-2.fc33.noarch
rhash-1.3.8-3.fc32.s390x
rpm-4.16.0-0.beta1.4.fc33.s390x
rpm-build-4.16.0-0.beta1.4.fc33.s390x
rpm-build-libs-4.16.0-0.beta1.4.fc33.s390x
rpm-libs-4.16.0-0.beta1.4.fc33.s390x
rust-srpm-macros-15-1.fc33.noarch
sed-4.8-1.fc33.s390x
setup-2.13.6-2.fc32.noarch
shadow-utils-4.8.1-3.fc33.s390x
shared-mime-info-2.0-1.fc33.s390x
sqlite-libs-3.32.2-1.fc33.s390x
systemd-libs-245.6-2.fc33.s390x
tar-1.32-4.fc32.s390x
tzdata-2020a-2.fc33.noarch
unzip-6.0-47.fc32.s390x
urw-base35-bookman-fonts-20170801-14.fc32.noarch
urw-base35-c059-fonts-20170801-14.fc32.noarch
urw-base35-d050000l-fonts-20170801-14.fc32.noarch
urw-base35-fonts-20170801-14.fc32.noarch
urw-base35-fonts-common-20170801-14.fc32.noarch
urw-base35-gothic-fonts-20170801-14.fc32.noarch
urw-base35-nimbus-mono-ps-fonts-20170801-14.fc32.noarch
urw-base35-nimbus-roman-fonts-20170801-14.fc32.noarch
urw-base35-nimbus-sans-fonts-20170801-14.fc32.noarch
urw-base35-p052-fonts-20170801-14.fc32.noarch
urw-base35-standard-symbols-ps-fonts-20170801-14.fc32.noarch
urw-base35-z003-fonts-20170801-14.fc32.noarch
util-linux-2.35.2-2.fc33.s390x
which-2.21-19.fc33.s390x
xapian-core-libs-1.4.14-1.fc33.s390x
xml-common-0.6.3-54.fc32.noarch
xorg-x11-font-utils-7.5-44.fc32.s390x
xorg-x11-fonts-ISO8859-1-100dpi-7.5-24.fc32.noarch
xorg-x11-server-utils-7.7-35.fc33.s390x
xxhash-libs-0.7.3-1.fc33.s390x
xz-5.2.5-2.fc33.s390x
xz-libs-5.2.5-2.fc33.s390x
zip-3.0-26.fc32.s390x
zlib-1.2.11-21.fc32.s390x
zstd-1.4.5-3.fc33.s390x

```

**Comment by pramsey** [comment]
Yeah, very strange. I was pretty suspicious that our s390 travis-ci entry passed all tests, seemed like waaaaay too much good luck for a project that hasn't had access to a big endian testing platform in a decade. So your result seems more "real" for whatever that's worth (nothing much). 

If there's any way we could get access to a big endian platform to test with, would love to take a run at it.

**Comment by dr-jts** [comment]
And the place to start is that `unit-math-DD` failure.

**Comment by hroncok** [comment]
@sharkcz Can give access to s390x.

However the failures also happen on aarch64 and ppc64le which are both little endian :/

If there is a way to runt he tests in verbose mode, I can use it and paste the logs here.

**Comment by pramsey** [comment]
Oh, exciting, so just good old platform issues... DD does depend on very particular adherence to IEEE double.

**Comment by sharkcz** [comment]
> If there's any way we could get access to a big endian platform to test with, would love to take a run at it.

@pramsey , please send me an email to sharkcz at fedoraproject dot org

**Comment by pramsey** [comment]
All tests (master) pass on an ARM server provisioned from AWS.

**Comment by hroncok** [comment]
> All tests (master) pass on an ARM server provisioned from AWS.

64bit or 32bit ARM?

**Comment by pramsey** [comment]
ARM64

**Comment by pramsey** [comment]
@sharkcz your SMTP server is currently unhappy 
```
451 4.3.0 Could not connect to other SMTP server 10.5.126.11: Connection timed out
```

**Comment by sharkcz** [comment]
@pramsey, hm, probably caused the datacenter move being in progress. Please use dan at danny dot cz instead.

**Comment by sharkcz** [comment]
Please also check your spam folder if you don't see my reply I just sent, gmail doesn't like me sometimes :-)
