### ISSUE TITLE
makeValid generates unexpected output

### ISSUE THREAD

**Issue by Xuanzhen-Zhang** [libgeos/geos#330]
std::string wkt = "FROM TXT FILE";
geos::operation::valid::MakeValid makeValid;
geos::io::WKTReader wktReader;
std::shared_ptr<const geos::geom::Geometry> geometry(wktReader.read(wkt));
std::cout << "preMkValid: " << geometry->getArea() << endl;
geometry = makeValid.build(geometry.get());
std::cout << "postMkValid: " << geometry->getArea() << endl;

Output is:
preMkValid: 1.11382
postMkValid: 4205.05

Attached is the wkt. After calling make valid, the difference in area becomes massive. This is a bathymetry geometry. The original geometry is just the border (first image with ice sheet unfilled), but after calling makeValid.build(geom), the new geometry becomes the entire ice sheet (second image with ice sheet filled). Desirably, it should still resemble the original geometry with just its borders. 
<img width="1698" alt="Screen Shot 2020-07-15 at 2 35 15 PM" src="https://user-images.githubusercontent.com/29758861/87582671-ba434e80-c6a8-11ea-96d5-d3b48eaabb07.png">
<img width="1057" alt="Screen Shot 2020-07-15 at 1 52 13 PM" src="https://user-images.githubusercontent.com/29758861/87582683-bf080280-c6a8-11ea-990f-f017ce839f7d.png">

[GoesBathymetryBug.txt](https://github.com/libgeos/geos/files/4927248/GoesBathymetryBug.txt)

**Comment by pramsey** [comment]
Just don't call MakeValid on a linestring? It's meant to process polygons. Linestrings don't have invalidities.

**Comment by jagill** [comment]
The OGC has a spec for simplicity, and ISO has a spec for both validity and simplicity, for LineStrings.  Moreover, if you have a large number of geometries, you should expect that you should be able to call `makeValid` on them without large surprises.

**Comment by Xuanzhen-Zhang** [comment]
> Is it an area or a line? Make valid can only do so much for you, if you feed it something nonsensical, it might return nonsense.

It is a multipolygon border, so the area enclosed is quite small.

**Comment by pramsey** [comment]
So the result of MakeValid is the same for both the old/new overlay engines, which means the result isn't "wrong" per se, just that it's got a different way to turn an invalid input to a valid output.

![screenshot_500](https://user-images.githubusercontent.com/113883/97748517-d083e780-1aaa-11eb-8ceb-1802eebdb150.png)

This is the output, the system has decided that the way to reconcile the doubled-up bottom rings is to use the outer ring as the enclosing ring, and return the spare inner ring as a line in a collection. The MakeValid code is very ring-centric, so this kind of falls out in an expected way. 

A "better" or at least different MakeValid might drop all the edges into a graph and then decide what is an "enclosed area" by doing a scan-line routine. This is probably what we're seeing when we look at the rendering of the geometry in QGIS. Is it the "right" way to interpret the invalid geometry? Maybe, at least insofar as it's the visualization that most/many user interface tools will provide. I think waiting to add a graph-based MakeValid might be better than trying to coerce the existing routine into being something it is not.

**Comment by jagill** [comment]
This makes sense to me.  It's not worth hacking the original routine with a special case.  Is a graph-based MakeValid something that is on the backlog?

**Comment by pramsey** [comment]
Yes, a less hacked-together MakeValid is on the list of things, and will hopefully improve on the reliability of the current one a little. Unfortunately we might have these kind of behaviour changes, but I think as long as we return valid results, with some reliability that's all folks can reasonably ask.

**Comment by pramsey** [comment]
With the GeometryFixer ported at 51560014f726a1f0b71e1b3a5a6ddee1d9e76c47, this will be resolved on next release.
