### ISSUE TITLE
isValidOp.h

### ISSUE THREAD

**Issue by bouyeijiang** [libgeos/geos#339]
// CHECKME: should this really be a pointer ?
    TopologyValidationError* validErr;

throw an exception method:
IsValidOp::checkNoSelfIntersectingRing(EdgeIntersectionList& eiList)
{
set<const Coordinate*, CoordinateLessThen>nodeSet;
    bool isFirst = true;
    for(const EdgeIntersection& ei : eiList) {
        if(isFirst) {
            isFirst = false;
            continue;
        }
        if(nodeSet.find(&ei.coord) != nodeSet.end()) {
           validErr = new TopologyValidationError(
                TopologyValidationError::eRingSelfIntersection,
                ei.coord); //throw an exception
            return;
        }
        else {
            nodeSet.insert(&ei.coord);
        }
}

when i attach a value to validErr has throw an exception：
An attempt was made to read or write to protected memory. This usually indicates that other memory is corrupted

example source:
c# call dll

**Comment by MaxRev-Dev** [comment]
I confirm, that this problem appeared in my [GDAL C# bindings](https://github.com/MaxRev-Dev/gdal.netcore) (3.2.0) after GEOS was updated to 3.9.0beta2. 
`An attempt was made to read or write to protected memory. This usually indicates that other memory is corrupted`
***This exception terminates the AppDomain entirely.***  
I can provide some C# tests if needed, but this comes directly from GEOS.

**Comment by dbaston** [comment]
Yes, an example GEOS call that fails would be helpful.

**Comment by MaxRev-Dev** [comment]
@dbaston Yes, of course. 
Ready to repro:
[gdal-test.zip](https://github.com/libgeos/geos/files/5762924/gdal-test.zip)

Used packages: (GDAL 3.2.0, GEOS 3.9.0beta2)
```
  <PackageReference Include="MaxRev.Gdal.Core" Version="3.2.0.210" />
  <PackageReference Include="MaxRev.Gdal.LinuxRuntime.Minimal" Version="3.2.0.200" />
  <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.2.0.200" />
```
Failing test:
``` csharp
  using MaxRev.Gdal.Core;
  using Xunit; 
  using OSGeo.GDAL;
  using OSGeo.OGR;
  using System; 

  public UnitTest1()
  {
      GdalBase.ConfigureAll();
  }
  
  [Fact]
  public void GdalDoesNotFailOnMakeValid()
  {
      var wkt = _staticWkt; // your non-valid wkt, i'm using feature from NaturalEarth 2.0 - ne_10m_parks_and_protected_lands_line.shp
      var geom = new Geometry(wkbGeometryType.wkbPolygon, wkt, 0, IntPtr.Zero, null);
      Assert.True(!geom.IsValid());
      geom.MakeValid(); // fails with System.AccessViolationException
      Assert.True(geom.IsValid());
  }
```

**Comment by pramsey** [comment]
Well, the lifecycle of `IsValidOp::validErr` is certainly a little dodgy (it gets deleted when IsValidOp goes out of scope, and yet IsValidOp is willing to hand out a pointer to it) but the users of it all appear to handle the lifecycle correctly, it never outlives the parent IsValidOp.

**Comment by MaxRev-Dev** [comment]
Build with stable [3.9.0](https://github.com/libgeos/geos/releases/tag/3.9.0) fixes this issue for me.

**Comment by pramsey** [comment]
Well that's very odd. Good news though... I'm just going to peak at the version diff.

There's really not a lot in that diff, certainly nothing that would cause memory corruption in IsValidOp. 

https://github.com/libgeos/geos/compare/3.9.0beta2...3.9.0

Close out if 3.9 is looking good.
