### ISSUE TITLE
Build errors on a Mac ARM64 system

### ISSUE THREAD

**Issue by sigmafelix** [libgeos/geos#350]
Hello,
I am trying to build `libgeos` on my Mac ARM64 system (MBP 2020). When I build the library, there are errors as below:

```
isong@Insangs-MacBook-Pro geos-3.8.1 % sudo make
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make  all-recursive
Making all in include
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make  all-recursive
Making all in geos
Making all in algorithm
Making all in locate

[truncated]

duplicate symbol 'vtable for geos::noding::BasicSegmentString' in:
    .libs/inlines.o
    noding/.libs/libnoding.a(BasicSegmentString.o)
duplicate symbol 'typeinfo name for geos::noding::BasicSegmentString' in:
    .libs/inlines.o
    noding/.libs/libnoding.a(BasicSegmentString.o)
duplicate symbol 'typeinfo for geos::noding::BasicSegmentString' in:
    .libs/inlines.o
    noding/.libs/libnoding.a(BasicSegmentString.o)
ld: 3 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libgeos.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
``` 

Does anyone have any idea for this problem?
Thank you.

**Comment by pramsey** [comment]
No immediate ideas. GEOS builds and regresses fine on AWS ARM servers, so it may not be an architecture issue per se, but something about Apple's tooling. It's possible we'll see this under x86 Big Sur as well, I guess? I haven't upgraded yet.

**Comment by sigmafelix** [comment]
@pramsey Thank you for the prompt response. I tried building `libgoes` with `cmake`, and the problem was set. I guess the problem comes out from the Apple's developer tools.

**Comment by pramsey** [comment]
Whoa, could you elaborate? You build with autotools and it failed, and you built with cmake and it didn't? Or the other way around? Or something else, you tried to build directly with xcode and it failed? What were you doing that led to the failure, and what worked?
