### ISSUE TITLE
GEOSversion() link with static library failed

### ISSUE THREAD

**Issue by fatalioerror** [libgeos/geos#366]
hi,  I have a problem when link with libgeos_c.a

geot.c
`
#include "geos_c.h"
const char *GEOSversion();
int main() {
        GEOSversion();
        return 0;
}
`
compile with libgeos_c.so. it works OK!
`
clang  geot.c -o geot -I/root/geostest/geos/include -L/root/geostest/geos/lib -lgeos_c
`
but when i build it with static lib libgeos_c.a, it fail.
`
clang  geot.c -o geot -I/root/geostest/geos/include /root/geostest/geos/lib/libgeos_c.a
`

error msg: 

ld: error: undefined symbol: operator new(unsigned long)
 referenced by geos_ts_c.cpp:430
               libgeos_c_la-geos_ts_c.o:(initGEOS_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: geos::geom::GeometryFactory::getDefaultInstance()
referenced by geos_ts_c.cpp:195
              libgeos_c_la-geos_ts_c.o:(initGEOS_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: geos::util::Interrupt::cancel()
 referenced by geos_ts_c.cpp:432
               libgeos_c_la-geos_ts_c.o:(initGEOS_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: operator delete(void*)
 referenced by geos_ts_c.cpp:430
              libgeos_c_la-geos_ts_c.o:(initGEOS_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: operator new(unsigned long)
 referenced by geos_ts_c.cpp:430
               libgeos_c_la-geos_ts_c.o:(GEOS_init_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: geos::geom::GeometryFactory::getDefaultInstance()
 referenced by geos_ts_c.cpp:195
               libgeos_c_la-geos_ts_c.o:(GEOS_init_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: geos::util::Interrupt::cancel()
 referenced by geos_ts_c.cpp:432
             libgeos_c_la-geos_ts_c.o:(GEOS_init_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: operator delete(void*)
 referenced by geos_ts_c.cpp:430
               libgeos_c_la-geos_ts_c.o:(GEOS_init_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: operator delete(void*)
 referenced by geos_ts_c.cpp:485
             libgeos_c_la-geos_ts_c.o:(finishGEOS_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: operator delete(void*)
 referenced by geos_ts_c.cpp:485
              libgeos_c_la-geos_ts_c.o:(GEOS_finish_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_begin_catch
 referenced by geos_ts_c.cpp:0
               libgeos_c_la-geos_ts_c.o:(GEOSDisjoint_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_end_catch
 referenced by geos_ts_c.cpp:0
               libgeos_c_la-geos_ts_c.o:(GEOSDisjoint_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_end_catch
 referenced by geos_ts_c.cpp:369
               libgeos_c_la-geos_ts_c.o:(GEOSDisjoint_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_end_catch
 referenced by geos_ts_c.cpp:367
               libgeos_c_la-geos_ts_c.o:(GEOSDisjoint_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_begin_catch
 referenced by geos_ts_c.cpp:0
               libgeos_c_la-geos_ts_c.o:(GEOSTouches_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_end_catch
 referenced by geos_ts_c.cpp:0
               libgeos_c_la-geos_ts_c.o:(GEOSTouches_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_end_catch
 referenced by geos_ts_c.cpp:369
               libgeos_c_la-geos_ts_c.o:(GEOSTouches_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_end_catch
 referenced by geos_ts_c.cpp:367
               libgeos_c_la-geos_ts_c.o:(GEOSTouches_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_begin_catch
 referenced by geos_ts_c.cpp:0
               libgeos_c_la-geos_ts_c.o:(GEOSIntersects_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: undefined symbol: __cxa_end_catch
 referenced by geos_ts_c.cpp:0
               libgeos_c_la-geos_ts_c.o:(GEOSIntersects_r) in archive /root/geostest/geos/lib/libgeos_c.a

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pramsey** [comment]
You probably have to include the static geos library as well as geos_c on the link line, otherwise you'll be missing the core symbols.

**Comment by fatalioerror** [comment]
> 
> 
> You probably have to include the static geos library as well as geos_c on the link line, otherwise you'll be missing the core symbols.

thanks.  It's right.
