### ISSUE TITLE
ParseException: Expected word but encountered end of stream

### ISSUE THREAD

**Issue by Cbarrow98** [libgeos/geos#372]
Hello,

Encountered this problem when trying to use shapely.wkt sub-module to parse wkt format

This was my code: **df2['Coordinates'] = df2['Coordinates'].apply(wkt.loads)**

-There is no missing data (Have checked)
- The format of coordiantes are the same e.g "POINT (-122.30332400000002 47.756486)"

Any suggestions ?

**Comment by pramsey** [comment]
I'm sorry, I don't see an issue with GEOS here, or even an error message. Perhaps find a support channel for shapely?
