### ISSUE TITLE
WKT writer precision

### ISSUE THREAD

**Issue by jaakkor2** [libgeos/geos#375]
Using the Julia interface to GEOS, a non-consistent behavior of WKTWriter with rounding precision was observed.  Original issue  https://github.com/JuliaGeo/LibGEOS.jl/issues/86. Used versions are LibGEOS v0.6.6 and GEOS_jll v3.9.0+0.
```
using LibGEOS
p = readgeom("POINT (654321.12345 0.1)");
writer = LibGEOS.WKTWriter(LibGEOS._context, trim=false, roundingprecision=3);
writegeom(p, writer)
```
gives
```
"POINT (654321.123 0.100)"
```
whereas
```
writer = LibGEOS.WKTWriter(LibGEOS._context, trim=true, roundingprecision=3);
writegeom(p, writer)
```
gives
```
"POINT (6.54e+05 0.1)"
```
Relevant libgeos code here https://github.com/libgeos/geos/blob/5b722cfd7c0dc7f3a5e205928397f304c60daf10/src/io/WKTWriter.cpp#L358-L369 

Judging from http://www.cplusplus.com/reference/iomanip/setprecision/ , if `std::fixed` is not in the stream, `std::setprecision` sets the significant digits.

**Comment by jaakkor2** [comment]
Same as above, now using pygeos

```python
>>> import pygeos
>>> p = pygeos.Geometry("POINT (654321.12345 0.1)")
>>> pygeos.io.to_wkt(p, trim=False, rounding_precision=3)
'POINT (654321.123 0.100)'
>>> pygeos.io.to_wkt(p, trim=True, rounding_precision=3)
'POINT (6.54e+05 0.1)'                    
```
```
geos               conda-forge/win-64::geos-3.8.1-he025d50_0
pygeos             conda-forge/win-64::pygeos-0.8-py38h9764186_1
```

**Comment by pramsey** [comment]
Output in "trim" mode should be closer to "expectations" in master, as of 2376cd6bf5d0743b02b588af17d2e9067c1874de
