### ISSUE TITLE
geos-config from cmake does not match that from autotools

### ISSUE THREAD

**Issue by shawnlaffan** [libgeos/geos#387]
The geos-config file generated under cmake does not match that for autotools, which later impacts on GDAL builds under FreeBSD (via Cirrus CI) using a perl alien ecosystem (overall CI system at https://github.com/shawnlaffan/geo-gdal-ffi-canary/).

Differences noted are from the 3.9.0 release tarball.  

The main difference seems to be due to these lines (autotools, then cmake):
https://github.com/libgeos/geos/blob/395e6c2d2531eda7483dd137058041f830e33825/tools/geos-config.in#L52
https://github.com/libgeos/geos/blob/395e6c2d2531eda7483dd137058041f830e33825/tools/geos-config.cmake#L45

In autotools this results in 
```sh
      echo -L${libdir} -lgeos-3.9.0
```

under cmake this results in
```sh
      echo -L${libdir} -lgeos-3
```

Should the cmake file use ```-lgeos-@GEOS_VERSION@``` instead of ```-lgeos-@GEOS_VERSION_MAJOR@```?

As an additional data point, ```libgeos-3.9.0.so``` is generated under autotools, but not under cmake.  Instead, ```libgeos.so.3.9.0``` is created.  Similarly, autotools has ```libgeos_c.so.17``` while cmake has ```libgeos_c.so.1```.  Perhaps that should be a separate issue, though.  

Thanks,
Shawn.

**Comment by dbaston** [comment]
I think that if we want to have naming of `libgeos.so.3.9.0` then the correct output is just `-lgeos`. If we want to have `libgeos-3.9.0.so` (emphasizing the lack of inter-version compatibility, I guess?) then yes, we should use `-lgeos-@GEOS_VERSION@`.

**Comment by shawnlaffan** [comment]
Just an update.  

It looks like the GDAL failures I noted are unrelated to ```geos-config```.  The GDAL configure script does not call ```geos-config --libs```, and compiles without issue.  The failures appear to be due to the absence of the .la files under cmake, and can be worked around by setting LD_LIBRARY_PATH (the dynamic libs are installed to a non-standard path under this build system).  

The ```geos-config``` parameters should still be consistent between build systems, though.

**Comment by dbaston** [comment]
@pramsey I can update the CMake config so that the library is called `libgeos-3.10.0` instead of being called `libgeos`. It feels like I'm fighting against the tools when I do this, though. Should we continue with what seems like an unconventional lib name?

**Comment by pramsey** [comment]
I feel like we should bend to the wind of the tools rather than fighting them. Trying to hard-version our library has led to a lot of complexity for little obvious gain, I think?

**Comment by hobu** [comment]
> Trying to hard-version our library has led to a lot of complexity for little obvious gain, I think?

Yes.

**Comment by pramsey** [comment]
Autotools is gone, long live the king.
