### ISSUE TITLE
Many C API functions lack tests

### ISSUE THREAD

**Issue by dbaston** [libgeos/geos#396]
Functions and code paths not tested can be seen in this codecov report: https://codecov.io/gh/libgeos/geos/src/master/capi/geos_ts_c.cpp. You should be able to view it without an account at least once, but it seems to require login after a few page views.

This would be a great task for anyone who wants to begin contributing to GEOS.

The behavior of the underlying operations is generally tested elsewhere, but C API tests should at least verify that 
- the function correctly operates with trivial inputs
- it preserves SRID, if applicable
- it returns the documented error code on error (if you can think of a way to trigger an error)

**Comment by jericks** [comment]
I would like to help out with this.  Would you prefer one big pull request or several smaller pull requests (one for function)?

**Comment by dbaston** [comment]
However you prefer to do it is good by me. Thanks!

**Comment by jericks** [comment]
I started by writing tests for GEOSDisjoint and GEOSTouches:

https://github.com/libgeos/geos/compare/master...jericks:codecov

**Comment by dbaston** [comment]
Thanks! Here are my suggestions:

- instead of creating local variables for the test geometries, use the built-in member variables `geom1_`, `geom2_`, etc. These will be automatically cleaned up, so you don't need to call `GEOSGeom_destroy`. You can peek at the `capitest::utility` class to see a full list.
- if you can test the necessary code paths with two geometries instead of three, that's better
- if you can test the necessary code paths with easily-readable geometries like `POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))`, that's better

**Comment by jericks** [comment]
To test all the *_r functions should add a struct utility_r to the capi_test_utils?

**Comment by dbaston** [comment]
I see the appeal but am not sure it's worth it, since the non-`_r` functions are just trivial wrappers around the `_r` versions.

**Comment by dbaston** [comment]
Still seems a worthy goal, IMO.
