### ISSUE TITLE
Parameter resolution in buffer method doesn't work properly

### ISSUE THREAD

**Issue by SergeyMalashenko** [libgeos/geos#409]
![image](https://user-images.githubusercontent.com/13943547/108042086-6c346600-7050-11eb-8382-dc3a76c591fc.png)
![image](https://user-images.githubusercontent.com/13943547/108042118-735b7400-7050-11eb-814c-6ce0e92efdaf.png)

**Comment by pramsey** [comment]
Not sure what you mean by "properly", but it seems to be doing *something*.
