### ISSUE TITLE
Broken documentation link on main geos web page

### ISSUE THREAD

**Issue by notmatthancock** [libgeos/geos#413]
The following link is provided under https://trac.osgeo.org/geos/#DocumentationandOtherInformation :

​GEOS API -- Doxygen-generate API documentation - http://geos.osgeo.org/doxygen/

But the link is broken.

**Comment by BuonOmo** [comment]
I think this issues deserves a :+1: comment (this one) since one now must either go through the code or generate the doc locally to access it.

**Comment by pramsey** [comment]
Duplicates #405. Hopefully will fix soon.
