### ISSUE TITLE
Is there an easy way of installing the latest version on Ubuntu?

### ISSUE THREAD

**Issue by MHBalsmeier** [libgeos/geos#420]
Hi,
is there a way of installing the latest version of geos on Ubuntu with apt? I would like to use version 3.9, however, sudo apt-get install --upgrade libgeos-dev gives me 3.8.0-1build1.

Is there an easier way of installing 3.9 than building it manually from source?

Thanks.

**Comment by dbaston** [comment]
Looks like the ubuntugis PPA has 3.9.0 for focal: 
https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

Otherwise I'm not aware of anything. As far as source builds go, GEOS is almost as simple as they come (no dependencies)

**Comment by MHBalsmeier** [comment]
Alright, thanks!
