### ISSUE TITLE
C++ unstable warning can't be depressed.

### ISSUE THREAD

**Issue by Jayyee-HPC** [libgeos/geos#425]
`#define USE_UNSTABLE_GEOS_CPP_API` can't stop the compiler warning. ""
And the warning is only stoppable in current version by define both _MSC_VER and USE_UNSTABLE_GEOS_CPP_API.
But define _MSC_VER  may potentially cause other issues.

In `geos/include/geos/geom/Geometry.h`
```
#ifndef USE_UNSTABLE_GEOS_CPP_API
#ifndef _MSC_VER
# warning "The GEOS C++ API is unstable, please use the C API instead"
# warning "HINT: #include geos_c.h"
#else
#pragma message("The GEOS C++ API is unstable, please use the C API instead")
#pragma message("HINT: #include geos_c.h")
#endif
#endif
```

**Comment by dbaston** [comment]
test.cpp

```
#define USE_UNSTABLE_GEOS_CPP_API
#include <geos/geom/GeometryFactory.h>
#include <iostream>

int main() {
	auto gfact = geos::geom::GeometryFactory::create();
	auto pt = gfact->createPoint();
	std::cout << pt->toString() << std::endl;

	return 0;
}
```

Compiles fine with

`g++ test.cpp -o test -lgeos`

What are you doing differently?

**Comment by Jayyee-HPC** [comment]
Oh, I put #define USE_UNSTABLE_GEOS_CPP_API after #include  Geos headers.
My bad.

But this discribtion in README  is a little misleading. 
"To remove the compiler warning, define USE_UNSTABLE_GEOS_CPP_API **somewhere** in the program."
