### ISSUE TITLE
How to convert between CRSes (using Proj)?

### ISSUE THREAD

**Issue by kad-beekw** [libgeos/geos#435]
I want to read in WKT serialized shapes in one CRS and return the WKT serialization of their corresponding shapes in a different CRS.

I was assuming this was a common operation, but I have not yet been able to get this functionality to work.  I know that there are command-line tools that can do this (ogr2ogr from the GDAL project comes to mind, but I need a low-level function, and could not find this low-level function within the somewhat large and complex GDAL code base).

After some research I have come to the following understanding:

  - Library GEOS is able to read and write WKT serializations of shapes, but is not able to do CRS transformations.
  - Library Proj is able to do CRS transformations, but is not able to read and write WKT serializations for shapes (only WKT serializations for CRSes).

Given that my seemingly simple task is split across two libraries, what is the simplest way to convert datatype `GEOSGeometry` (GEOS) into datatype `PJ_COORD` (Proj), and back again?  Preferably without too much loss of performance.

(I also have the feeling that I am overlooking something: is translating geometries between CRSes really this difficult with modern libraries?  I'm hoping there is a straightforward solution somewhere that I have simply missed in my web searches ;-) )

**Comment by pramsey** [comment]
If you want a single API to to it, then the OGR API in GDAL has one function call for you.

https://gdal.org/api/vector_c_api.html#_CPPv415OGR_G_Transform12OGRGeometryH28OGRCoordinateTransformationH

It's not frankly that hard to combine a GEOS CoordinateFilter with a Proj transformation to carry things out with that pair of libraries. The nature of the libraries will result in a certain about of copying, but that's true of putting ANYTHING into GEOS. If you don't actually need any facilities of GEOS, then you'll find Proj is perfectly happy to transform in-memory buffers.
