### ISSUE TITLE
GEOSLargestEmptyCircle returns circles which partially fall outside the boundary

### ISSUE THREAD

**Issue by nyalldawson** [libgeos/geos#443]
Using the GEOSLargestEmptyCircle_r method with a polygon boundary I frequently see results where the returned linestring center sits right on the boundary line, e.g. in the example below (grey is the boundary, red is the geometry, and blue is the result)

![image](https://user-images.githubusercontent.com/1829991/116511920-8f11af00-a90a-11eb-9c76-91af294a60bc.png)

This seems counter-intuitive to me. If the boundary is specfied then I would expect the returned circle to sit completely within this boundary, instead of the current behaviour which seems to be that the circle **center** has to be inside the boundary.

Possibly this is the intended behaviour, in which case this is a documentation issue.

**Comment by dr-jts** [comment]
This is working as expected (although I agree that the semantics might not be the most intuitive).  In the LargestEmptyCircle algorithm the circle **centre** is constrained to lie inside the convex hull of the input, not the entire circle.

To constrain the entire circle to lie inside the convex hull, include the convex hull boundary as part of the constraints:

LEC of 3 triangles:
```
MULTIPOLYGON (((80 90, 140 130, 140 60, 80 90)), ((240 150, 300 150, 290 210, 240 150)), ((140 300, 214 284, 155 239, 140 300)))
```
![image](https://user-images.githubusercontent.com/3529053/116588219-1d1c7400-a8d0-11eb-8871-b6978fc7fbb8.png)

LEC of 3 triangles plus convex hull boundary
```
GEOMETRYCOLLECTION (LINEARRING (140 60, 80 90, 140 300, 214 284, 290 210, 300 150, 140 60), POLYGON ((80 90, 140 130, 140 60, 80 90)), POLYGON ((240 150, 300 150, 290 210, 240 150)), POLYGON ((140 300, 214 284, 155 239, 140 300)))
```
![image](https://user-images.githubusercontent.com/3529053/116588298-3a514280-a8d0-11eb-89d8-ad23009ee80c.png)

**Comment by nyalldawson** [comment]
@dr-jts ok, that makes sense. I think this is mostly a documentation issue -- the GEOSLargestEmptyCircle mixes up the terms of "obstacle" and "boundary", which makes it confusing to understand. I think the documentation may also be out of date as it explicitly states that "The obstacles are point and line geometries", yet it's working fine with polygon obstacles too...

**Comment by dr-jts** [comment]
>  ok, that makes sense. I think this is mostly a documentation issue 

Agreed, the docs are a bit confusing.  They are just copying the JTS docs, which could do with some improvement.

> -- the GEOSLargestEmptyCircle mixes up the terms of "obstacle" and "boundary", which makes it confusing to understand. 

The boundary is different to the obstacles.  It defaults to the CH of the obstacles, but it can actually be any polygon.

> I think the documentation may also be out of date as it explicitly states that "The obstacles are point and line geometries", yet it's working fine with polygon obstacles too...

Well, not really.  Polygons are accepted as obstacles, but are treated as lines, not areas.  E.g.:
```
MULTIPOLYGON (((90 140, 150 310, 335 92, 150 60, 90 140)), ((280 290, 270 220, 300 250, 280 290)))
```
![image](https://user-images.githubusercontent.com/3529053/116629646-84551b00-a906-11eb-8a6b-a1bd7925373f.png)

It's fairly easy to fix this, and also to add an option to include the CH of the obstacles as a constraint so that the computed circle lies wholly inside it.
