### ISSUE TITLE
Docker image for geosop

### ISSUE THREAD

**Issue by tschaub** [libgeos/geos#449]
Hello!

I read @dr-jts' [post](http://lin-ear-th-inking.blogspot.com/2021/01/introducing-geosop-cli-for-geos.html) on `geosop` and thought it looked handy.  I was wondering if there would be support for maintaining a Docker image that would make it easier for people to make use of it.

Something like the Dockerfile below should do the trick (the default `VERSON` of 47f145e was just to get something going):
```Dockerfile
FROM docker.osgeo.org/geos/build-test:alpine AS base
ARG VERSION=47f145e

WORKDIR /source
RUN wget --quiet https://github.com/libgeos/geos/archive/${VERSION}.tar.gz --output-document - \
  | tar xz --directory=. --strip-components=1

WORKDIR /build
RUN cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_BENCHMARKS=OFF -D BUILD_TESTING=OFF /source \
  && make install \
  && cp bin/geosop /usr/local/bin/geosop

WORKDIR /install/bin
RUN cp --no-dereference /usr/local/bin/geos* . \
  && for i in ./*; do strip -s $i 2>/dev/null || /bin/true; done

WORKDIR /install/lib
RUN cp --no-dereference /usr/local/lib64/libgeos*.so.* . \ 
  && for i in ./*; do strip -s $i 2>/dev/null || /bin/true; done


FROM alpine
RUN apk add --no-cache libstdc++
COPY --from=base /install/bin/geos* /usr/local/bin/
COPY --from=base /install/lib/libgeos* /usr/local/lib/

ENTRYPOINT ["geosop"]
```

If this were tagged & published as `docker.osgeo.org/geos/geosop:alpine`, then people could do this to try out `geosop`:

```bash
docker run --rm docker.osgeo.org/geos/geosop:alpine -a 'POINT(1 2)' --format=wkt buffer 3
```

The resulting image is just under 11 MB - so not great, but also not too bad.

I guess this would be something that might live in https://git.osgeo.org/gitea/geos/geos-docker.  It seems like the same image (without the `geosop` entrypoint) could also be useful for people wanting to start with a geos install (though I'm uncertain if the install above is sufficient for all purposes).  Let me know if this is a better question for [that issue tracker](https://git.osgeo.org/gitea/geos/geos-docker/issues) or someplace else.

**Comment by mwtoews** [comment]
See also #445 to properly install `geosop`

**Comment by tschaub** [comment]
> See also #445 to properly install `geosop`

Nice.  That caught me by surprise too.

**Comment by pramsey** [comment]
OK doke. https://github.com/libgeos/geos/pkgs/container/geosop
