### ISSUE TITLE
Writing WKB GEOMETRY type does not support ISO types in 3D.

### ISSUE THREAD

**Issue by alas2** [libgeos/geos#462]
Can we please have support for writing 3D types complying with ISO WKB GEOMETRY format as the Reader does? 

Probably, can be achieved by adding 1000(0x3E8) to flag3D when dimension is 3D

> `  void WKBWriter::writeGeometryType(int typeId, int SRID)
  {
      int flag3D = (outputDimension == 3) ? int(**0x800003E8**) : 0;
      int typeInt = typeId | flag3D;
  
      if(includeSRID && SRID != 0) {
          typeInt = typeInt | 0x20000000;
      }
  
      writeInt(typeInt);
  }`

**Comment by pramsey** [comment]
It's quite easy to code up, unfortunately just doing it means breaking the WKB for anyone who expects it to use the SFSQL high-bit flagging method. The least intrusive thing is to add an optional parameter set to the old style but with the option for the new style.

**Comment by alas2** [comment]
@Pramsey, Thanks. Would it be possible to populate both bits? Given the fact that m is not supported so 3D (for ISO) is simply adding 1000(0x3E8) to the geometry type and for SFSQL adding the last bit which is 0x80000000. To populate both bits type = type | 0x800003E8. The reader handles both cases. Thanks again

**Comment by pramsey** [comment]
No, going belt-and-suspenders is fine for readers that understand there are two possible flagging methods, but any reader that understands that... would already be capable of handling the old-style method. And any reader that only understands new-style will end up wondering why it is receiving huge type numbers and fail immediately when reading the type number.

**Comment by pramsey** [comment]
Done, with a parameter, turns out the CAPI was happy with a couple more setters/getters so it was all straightforward. Will be in 3.10 release.
