### ISSUE TITLE
Clarification about LGPL license

### ISSUE THREAD

**Issue by molinav** [libgeos/geos#470]
I open this issue because I would like to confirm the LGPL license version(s) that may apply to GEOS.

From the GitHub repository overview, I can see the following:
```
LGPL-2.1 License
```
which is automatically set after parsing the `COPYING` file at the repository root. However, I have seen in a lot of source files the following header snippet in which it states that the software is released under the LGPL without specifying version 2.1:
```
 *
 * This is free software; you can redistribute and/or modify it under
 * the terms of the GNU Lesser General Public Licence as published
 * by the Free Software Foundation.
 * See the COPYING file for more information.
 *
```
According to the [GPL-2.0](https://www.gnu.org/licenses/gpl-2.0.html) Item 9 (and, by extension, the [LGPL-2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html) Item 13):
> Each version is given a distinguishing version number. If the Program specifies a version number of this License which applies to it and "any later version", you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software Foundation. 

Based on this:
* Is the GEOS license LGPLv2.1+ but the information at the repository overview is misleading due to the parsing of the `COPYING` file by GitHub?
* Is the GEOS license LGPLv2.1-only and there is an inconsistency in the source file headers?

**Comment by pramsey** [comment]
The header says "See the COPYING file", which is good enough for me. COPYING file says 2.1 Seems like the answer is pretty clear.

**Comment by molinav** [comment]
The fact that I am asking this may show you that the answer was not that clear, so from your reply I would say that *there may be an inconsistency in the source file headers*.

I understand your point regarding the statement "See the COPYING file", but please think that projects with license LGPLv2.1+ can also place a `COPYING` file with the content of LGPL 2.1, and it would **not** mean LGPLv2.1-only. That was the reason for me opening this issue, because the source file headers do not write "version 2.1" explicitly.

Note that I am not making up this thing regarding the source file headers, I am taking it from the LGPLv2.1 text (and therefore from the [`COPYING`](https://github.com/libgeos/geos/blob/main/COPYING#L418) file from GEOS, I read the license). If you go to the license LGPLv2.1-only as recorded in SPDX (https://spdx.org/licenses/LGPL-2.1-only.html), you can see that after the section "How to Apply These Terms to Your New Libraries", they show the standard license header for LGPLv2.1-only:
> Standard License Header
> Copyright (C) year name of author
> 
> This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; version 2.1.
> 
> This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
> 
> You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

where it is clearly stated `GNU Lesser General Public License as published by the Free Software Foundation; version 2.1`. This is not what appears in the source file headers of GEOS, so I think my doubt was legit.

Thanks anyway for the clarification.
