### ISSUE TITLE
RPM package creation is not documented and is not working

### ISSUE THREAD

**Issue by yscontrol** [libgeos/geos#474]
The documentation does not specify how to create rpm package and build is setting undocumented flag CPACK_INSTALL_PREFIX.
This flag should probably be replaced by CPACK_PACKAGING_INSTALL_PREFIX  
I am building on ubuntu 16.04 cmake 3.17
after make I tun
```make package``` 
but it creates dummy package as rpm -qlp shows just 2 lines:
``` 
Linux.rpm
/
```
The build/_CPack_Packages/Linux/RPM/SPECS/geos.spec an shows blank list 
```
...
%files
%defattr(-,root,root,-)
%dir "/"
```

I tried
1. set cmake variables as the following:
-DCPACK_BINARY_RPM=ON . this will result in settings 

CMakeCache.txt
```
//Enable to build RPM packages
CPACK_BINARY_RPM:BOOL=ON
//ADVANCED property for variable: CPACK_BINARY_RPM
CPACK_BINARY_RPM-ADVANCED:INTERNAL=1
```
Set desired <install> dir e.g.
-DCPACK_INSTALL_PREFIX=../install/.
-DCMAKE_INSTALL_PREFIX=../install/.
-DCPACK_PACKAGING_INSTALL_PREFIX=../install/.
Somehow CPACK_SOURCE_GENERATOR "TBZ2". Shoujld it be "RPM.."?
the CPACK_OUTPUT_CONFIG_FILE is created with default name CPackConfig.cmake
CPACK_PROPERTIES_FILE is created with CPackProperties.cmake name
it has set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
CPackSourceConfig.cmake:60:set(CPACK_RPM_PACKAGE_SOURCES "ON")
However CPACK_RPM_<COMPONENT>_USER_FILELIST is not present ? is this causing problem that components not specified in CMakeLitsts.txt?

Note: make install installs files correctly into custom install dir as per cmake command 
```
cmake -DCMAKE_BUILD_TYPE=Release -DARM_BUILD=ON -DCPACK_BINARY_RPM=ON -DCPACK_INSTALL_PREFIX=../install -DCMAKE_INSTALL_PREFIX=../install -DCPACK_PACKAGING_INSTALL_PREFIX=../install ..

```
 but  rpm file is not placed ther but into .. geos-master/build/GEOS-xxxxx-Linux.rpm  dir and CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX is not set

I also tried
cpack --config CPackSourceConfig.cmake
cpack --config CPackConfig.cmake
but it did not help.

When I enabled set(CPACK_RPM_DEBUGINFO_SINGLE_PACKAGE  1) I got warning during make package : ```CMake Warning (dev) at /opt/cmake/share/cmake-3.17/Modules/Internal/CPack/CPackRPM.cmake:1409 (message):
  CPackRPM:Warning: debuginfo package was requested but will not be generated
  as no source files were found!
  ```

I also tried  "make dist" and that generated another rpm of expected size  8037372 geos-xxxxx.rpm, 
_CPack_Packages/Linux-Source/RPM/SRPMS/geos-xxxxx.rpm which contains 2 files
geos-xxxxx.tar.gz
geos.spec
The spec file does not have %files list, just the Source geos-xxxxx.tar.gz. I'd like to get normal rpm with source files without  being packed to  tar.gz and I dont need source distribution , just the libraries and headers which are bing installed via "make install"

 There should be instruction to set
License:       instead of  unknown
Group:        instead of  unknown

2.   make  or make install
3.  cpack -G "RPM"
Then the dir geos-master/build/_CPack_Packages/Linux/RPM will be created with rpm package and spec file for rpm tools
but rpm has no actual files

**Comment by pramsey** [comment]
Magic RPM building is not something we have ever provided (or, frankly until I read this ticket, not something I ever even knew was possible with cmake). Pull request would be most interesting.
