### ISSUE TITLE
GEOSProjectNormalized_r returns NaN when length of g is 0

### ISSUE THREAD

**Issue by macdrevx** [libgeos/geos#475]
[`GEOSProjectNormalized_r `](https://github.com/libgeos/geos/blob/d635a3fecf586da19889b37ec4aa21b7cda38733/capi/geos_ts_c.cpp#L3325-L3341) returns NaN when length of parameter `g` is 0. I would expect it to fail with -1 and possible some error logged to the context instead.

**Comment by pramsey** [comment]
Fixed in main at 5f4af4116
