### ISSUE TITLE
GEOS_INLINE and geos-config

### ISSUE THREAD

**Issue by danpat** [libgeos/geos#500]
Recently, binary distributions of `geos` 3.10 on macOS via Homebrew seems to have switched back to the default of `DISABLE_GEOS_INLINE=OFF`.

This has lead to compilation issues for projects that are used to linking against system-installed binaries, like this:

https://github.com/valhalla/valhalla/issues/3388#issuecomment-961934388

where the symbols that are hidden inside the `GEOS_INLINE` define are not present in the published binaries at all.  This requires folks trying to compile against `geos` to add `-DGEOS_INLINE` to their build.  If you supply `-DGEOS_INLINE` on a platform where the binaries were built _without_ inlining, then you end up with [ODR](https://en.wikipedia.org/wiki/One_Definition_Rule) errors from the compiler.

It feels like `geos-config` should be emitting `-DGEOS_INLINE` for `geos-config --cflags`, or `pkg-config --cflags` should be doing the same, but I cannot see anywhere in history where they have done so.

I would be happy to PR fixes for `geos-config.in` and `geos.pc.in` if that's appropriate, but as this appears to be a long-standing situation, I want to make sure I'm not missing something dumb.

**Comment by pramsey** [comment]
Hm. So the DISABLE_GEOS_INLINE was originally set to ON for MacOS compilation on the M1. I'm not sure if that problem has gone away yet. In an ideal world we'd figure out how to leave inlines in place on the M1, since there's a *lot* of performance benefit to having them there.

**Comment by danpat** [comment]
Digging through the Debian `rules` files for various versions, it looks like there was also `--disable-inline` for ARM there for multiple versions, both before and after the CMake switchover.  But for x86 variants, Debian+Ubuntu appear to be using the defaults to build binaries.

..which is confusing, because when I use `nm` to look at, say, the binaries on of 3.8.0 on Ubuntu 20.04, I can see:

```
# nm -C -D /usr/lib/x86_64-linux-gnu/libgeos-3.8.0.so | grep ::Coordinate\(
0000000000099740 T geos::geom::Coordinate::Coordinate(double, double, double)
```

which I _don't_ see in the macOS `.dylib` equivalent, despite both versions, as far as I can see, being built with the default of inlining enabled.

This explains why an Ubuntu/Debian build of Valhalla has been working out of the box, despite not supplying `-DGEOS_INLINE`.  What I don't get is why those symbols are in the Ubuntu libraries in the first place.  I feel like I'm missing something important.

**Comment by pramsey** [comment]
This will get addressed in gh-543, I think.

**Comment by woodpeck** [comment]
Just in case someone gets here by way of a search engine, I had the issue today trying to compile something against geos 3.10 which is packaged with Ubuntu 22.04. I managed to solve it without changing the installed geos version by compiling my code with -DGEOS_INLINE and providing the *.inl files in an include path. It didn't feel logical since geos 3.8 on Ubuntu 20.04 already didn't include the *.inl files and everything worked ok there, but hey.
