### ISSUE TITLE
Rotate or tanslate geometry?

### ISSUE THREAD

**Issue by kunlinyu** [libgeos/geos#503]
I'm trying to develop a 2D simulation program with collision detection. I think I can use the overlay(), disjoint() method of libgeos to do the collision detection. But after I read the code, it seems there is no way to transform(rotate and translate, no scale) a geometry?

I want to ask, does libgeos support rotating or translating geometries?
and
Is it a good idea to use libgeos as a fundamental part of 2d simulation?

**Comment by pramsey** [comment]
No, there's no currently any utilities for geometry rotation or translation. You can see #482 for another place where people are asking for that functionality.

I don't think GEOS is necessarily a great fit for simulation, it's not a real-time engine by any stretch. You might find that a real game engine is a better fit.

**Comment by kunlinyu** [comment]
@pramsey Thank you! I decide to use box2d to do my job!
