### ISSUE TITLE
[arm64] libGeos performance degraded due to calls to soft float operations

### ISSUE THREAD

**Issue by sebpop** [libgeos/geos#509]
Running libGeos performance benchmarks show that there is an issue on arm64.
GCC generates calls to the software operation in libgcc instead of using Arm64's FP instruction.

Here are the steps to reproduce the performance issue:
```
git clone https://git.osgeo.org/gitea/geos/geos.git 
mkdir geos/build
cd geos/build
cmake -DBUILD_BENCHMARKS:BOOL=ON ..
make -j10
perf record ./bin/perf_voronoi
perf report
```
On arm64:
```
  55.32%  perf_voronoi  libgcc_s.so.1        [.] __multf3
   9.98%  perf_voronoi  libgcc_s.so.1        [.] __addtf3
   6.88%  perf_voronoi  libgcc_s.so.1        [.] __subtf3
   4.96%  perf_voronoi  libgcc_s.so.1        [.] 0x000000000000689c
   2.32%  perf_voronoi  libgeos.so.3.11.0    [.] geos::triangulate::IncrementalDelaunayTriangulator::insertSite
[...]
```
On x64:
```
   9.29%  perf_voronoi  libgeos.so.3.11.0    [.] geos::triangulate::quadedge::TrianglePredicate::isInCircleNormalized
   8.39%  perf_voronoi  libgeos.so.3.11.0    [.] geos::triangulate::IncrementalDelaunayTriangulator::insertSite
   8.27%  perf_voronoi  libgeos.so.3.11.0    [.] geos::triangulate::quadedge::QuadEdgeSubdivision::fetchTriangleToVisit
[...]
```
A reduced testcase is:
```
long double
foo (long double x)
{
  return x * x;
}
```
On arm64:
```
aarch64 - 16:57:59:~/bugs/long-double$  gcc -O2 -S -o- a.c
foo:
	stp	x29, x30, [sp, -16]!
	mov	v1.16b, v0.16b
	mov	x29, sp
	bl	__multf3
	ldp	x29, x30, [sp], 16
	ret
```
On x64:
```
x86_64 - 16:58:05:~$ gcc -O2 -S -o- a.c 
foo:
	endbr64
	fldt	8(%rsp)
	fmul	%st(0), %st
	ret
```
I will be taking the reduced bug to gcc's bugzilla as well.

**Comment by pramsey** [comment]
I could fix this by converting everything to use DD math instead (all software based) then at least everything would be the same speed and would have the same failure modes.  The use of long double in GEOS is only in this one place.  The implementation of long double seems a bit variable over platforms and compilers, so the implication is we'd get different failure modes on different platforms.

The use of "long double" was a similar attempt to squeeze more robustness out of the system with more precision. I doubt the gcc people failed to use hardware ops for long double by accident, so I'm interested to learn their reasoning for it. Could be cross-platform compatibility, perhaps.

**Comment by sebpop** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103336

**Comment by s8mathur** [comment]
Quick question, is it necessary to set the `Release` build type flag while compiling benchmark tests? 
`cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_BENCHMARKS:BOOL=ON`

I ask because INSTALL.md mentions as follows 
> Setting `CMAKE_BUILD_TYPE` to `Release` is necessary to enable compiler
optimizations.

>

**Comment by pramsey** [comment]
I'm pretty sure we default to Release, but if you build with Debug you'll get no optimizations.

**Comment by apinski-cavium** [comment]
x86_64 uses 80bit FP for long double while aarch64 uses 128bit. This is the main difference here. There is no performance problem with GCC itself.  Does this library really need something more than 64bit IEEE FP? Or was it using long double thinking it will provide the best performance for x86?

**Comment by apinski-cavium** [comment]
If you really need 128bit FP, you might want to switch x86_64 to be using _Float128 instead (see https://gcc.gnu.org/onlinedocs/gcc/Floating-Types.html for more details on that).

**Comment by pramsey** [comment]
Yes, the intent was to actually have more precision that 64 bit FP. (The rest of the library uses a software implementation of doubledouble to obtain platform independent consistent results with high precision, at the expense of being able to use hardware instructions where available.) 

I guess the submitter might ask why, if gcc is generating hardware instructions for both platforms, the aarch64 `long double` performance is worse than the x86_64?

**Comment by apinski-cavium** [comment]
Because there are no 128bit fp instructions on aarch64.

**Comment by pramsey** [comment]
There we go.
