### ISSUE TITLE
UNION :: Debug Assertion failed

### ISSUE THREAD

**Issue by ArturSalamatin** [libgeos/geos#510]
I need to unite two polygons that intersect.
I either use the GEOS library in a wrong way, or there is might be a bug..

This minimal example generates 
"Debug assertion failed"
once compiled in DEBUG mode for x64 system with C++14 as well as C++17 standard.

The commented lines is another way to unite two polygons,
to the best of my knowledge. However, it produces the same error.

`#include   <iostream>
#include <geos/geom.h>
#include <geos/geom/GeometryFactory.h>
#include <geos/algorithm/ConvexHull.h>
#include <geos/operation/union/CascadedPolygonUnion.h>

int main()
{
	auto pm = std::make_unique<geos::geom::PrecisionModel>(geos::geom::PrecisionModel::FLOATING); // creates precision model
	auto global_factory = geos::geom::GeometryFactory::create(pm.get());

	std::vector<geos::geom::Coordinate> c1{ {-1,-1},{-1,2},{2,2},{2,-1},{-1,-1} };
	std::vector<geos::geom::Coordinate> c2{ {1,1},{1,-2},{-2,-2},{-2,1},{1,1} };

	auto poly1 = global_factory->createPolygon(std::move(c1));
	auto poly2 = global_factory->createPolygon(std::move(c2));

	bool is_intersect = poly1->intersects(poly2.get());

	std::cout << "Two polygons intersect: " << is_intersect << std::endl;

	auto shape = poly1->Union(poly2.get());

//std::vector<geos::geom::Polygon*> polys{ poly1.get(), poly2.get() };
	//geos::operation::geounion::CascadedPolygonUnion unite(&polys);
	//auto shape2 = unite.Union();
}`

**Comment by ArturSalamatin** [comment]
The RELEASE version works fine.

**Comment by pramsey** [comment]
I am unable to duplicate this. Built in debug mode or release mode. I added the following test to CascadedPolygonUnionTest.cpp
```c++
// GH-510 
template<>
template<>
void object::test<2> ()
{
    geos::geom::PrecisionModel pm(geos::geom::PrecisionModel::FLOATING);
    auto gf = geos::geom::GeometryFactory::create(&pm);

    std::vector<geos::geom::Coordinate> c1{ {-1,-1},{-1,2},{2,2},{2,-1},{-1,-1} };
    std::vector<geos::geom::Coordinate> c2{ {1,1},{1,-2},{-2,-2},{-2,1},{1,1} };

    auto poly1 = gf->createPolygon(std::move(c1));
    auto poly2 = gf->createPolygon(std::move(c2));

    bool is_intersect = poly1->intersects(poly2.get());

    std::cout << "Two polygons intersect: " << is_intersect << std::endl;

    auto shape = poly1->Union(poly2.get());

    //std::vectorgeos::geom::Polygon* polys{ poly1.get(), poly2.get() };
    //geos::operation::geounion::CascadedPolygonUnion unite(&polys);
    //auto shape2 = unite.Union();
}
```
There is no assertion failure or other runtime problem.

**Comment by StevePER** [comment]
I can reproduce this in my Windows debug build with GEOS 3.10.1. It is the same as #490.

**Comment by pramsey** [comment]
Has 84558712033b2554c2411076ec350e183747c95a fixed the problem?

**Comment by StevePER** [comment]
Yes, that commit fixes the problem for me.
