### ISSUE TITLE
Build errors on 4 android armv7  

### ISSUE THREAD

**Issue by zsr8512** [libgeos/geos#512]
Hello,
I am trying to build geos3.8.2 for android armv7. When I build it,there are errors as below:
ld: error: duplicate symbol: vtable for geos::noding::BasicSegmentString
>>> defined at inlines.cpp
>>>            .libs/inlines.o:(vtable for geos::noding::BasicSegmentString)
>>> defined at BasicSegmentString.cpp
>>>            BasicSegmentString.o:(.data.rel.ro+0x0) in archive noding/.libs/libnoding.a

ld: error: duplicate symbol: typeinfo for geos::noding::BasicSegmentString
>>> defined at inlines.cpp
>>>            .libs/inlines.o:(typeinfo for geos::noding::BasicSegmentString)
>>> defined at BasicSegmentString.cpp
>>>            BasicSegmentString.o:(.data.rel.ro+0x24) in archive noding/.libs/libnoding.a

ld: error: duplicate symbol: typeinfo name for geos::noding::BasicSegmentString
>>> defined at inlines.cpp
>>>            .libs/inlines.o:(typeinfo name for geos::noding::BasicSegmentString)
>>> defined at BasicSegmentString.cpp
>>>            BasicSegmentString.o:(.rodata+0x0) in archive noding/.libs/libnoding.a
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:552: recipe for target 'libgeos.la' failed

Does anyone have any idea for this problem?
Thank you.

**Comment by zsr8512** [comment]
the version of geos is 3.8.2

**Comment by dbaston** [comment]
Yet another manifestation of https://github.com/libgeos/geos/pull/365, I'd say. You can disable inlining, but at significant performance cost.

**Comment by pramsey** [comment]
Unfortunate we don't have easy access to a reproduction. Hope someone comes in with a PR!
