### ISSUE TITLE
Buffer produces slightly incorrect results when mitre limit is triggered

### ISSUE THREAD

**Issue by michaeltandy** [libgeos/geos#531]
If you have a 100 x 100 square and you apply a buffer of 10, then take the bounding box of the buffer, you would expect a bounding box of 120 x 120 regardless of what the corners looked like.

| Join        | Mitre limit           | Works as expected? |
| ------------- |:-------------:| -----:|
| JOIN_ROUND | any | Yes ✅ 120 x 120 |
| JOIN_BEVEL | any      | Yes ✅ 120 x 120 |
| JOIN_MITRE | 5.0      | Yes ✅ 120 x 120 |
| JOIN_MITRE | 1.0      | No ❌ 118.28 x 118.28|

The following test illustrates this:
```cpp
template<>
template<>
void object::test<20>
()
{
    using geos::operation::buffer::BufferOp;
    using geos::operation::buffer::BufferParameters;

    std::string wkt0("POLYGON((0 0, 100 0, 100 100, 0 100, 0 0))");
    GeomPtr g0(wktreader.read(wkt0));
    const double distance = 10.0;
    
    std::string wkt1("POLYGON ((-10 -10, -10 110, 110 110, 110 -10, -10 -10))");
    GeomPtr gexpected(wktreader.read(wkt1));


    BufferParameters params(8, BufferParameters::CAP_SQUARE,
                            BufferParameters::JOIN_MITRE, 1.0);
    BufferOp op(g0.get(), params);
    GeomPtr gresult = op.getResultGeometry(distance);
    

    geos::algorithm::MinimumDiameter m(gresult.get());
    GeomPtr mbr(m.getMinimumRectangle());

    ensure_equals_geometry(mbr.get(), gexpected.get());
}
```
This test fails for me, when run on 3efa5d3b21f. The buffered polygon produced as `gresult` is: `POLYGON ((-9.1421356237309510 -5.0000000000000000, -9.1421356237309510 105.0000000000000000, -4.9999999999999982 109.1421356237309510, 105.0000000000000000 109.1421356237309510, 109.1421356237309510 105.0000000000000000, 109.1421356237309510 -4.9999999999999982, 105.0000000000000000 -9.1421356237309510, -4.9999999999999982 -9.1421356237309510, -9.1421356237309510 -5.0000000000000000))`

I was able to work around this issue, for my purposes, by first applying a JOIN_BEVEL with a distance of 0.00001 then a JOIN_MITRE with a distance of 9.99999 and a big mitre limit.

**Comment by pramsey** [comment]
Use the default mitre_limit instead of setting it to 1.0 and you also get a "good" result.

**Comment by dr-jts** [comment]
This must be a flaw in the math used to compute the mitred join.  I'll investigate.

**Comment by dr-jts** [comment]
This is fixed in JTS by https://github.com/locationtech/jts/pull/818.  Will be ported soon.

**Comment by pramsey** [comment]
Ported at 0c0462385c9c92a7e6761af7c177d61c3498b19e
