### ISSUE TITLE
[Document] Supporting GeoJSON Reader/Writer information is missing in News

### ISSUE THREAD

**Issue by sanak** [libgeos/geos#535]
This is just documentation thing, but I noticed that supporting GeoJSON Reader/Writer information is missing in `NEWS.md` `Changes in 3.10.0` section and new website News `Version 3.10.0` page.
- https://github.com/libgeos/geos/blob/main/NEWS.md#changes-in-3100
- https://libgeos.org/posts/2021-10-01-geos-3-10-released/

New website mentions that it is already supported, and website News `Version 3.10.1` page includes `Fixes GeoJSON crash on invalid input` line, so I think that it's better to add supporting GeoJSON Reader/Writer information to News `3.10.0` section/page.
- https://libgeos.org/specifications/geojson/
- https://libgeos.org/usage/c_api/#readers-and-writers
- https://libgeos.org/posts/2021-11-02-geos-3-10-1-released/

**Comment by pramsey** [comment]
A PR would save me having to figure out exactly what you want changed. The website content is inside the code repo, so this should be easy peasy.

**Comment by sanak** [comment]
@pramsey  
Okay, I just created the PR (#537), so please check it when you have a time. 🙇‍♂️
