### ISSUE TITLE
need insights on the attribution of utils module to geos library

### ISSUE THREAD

**Issue by sahanaRavinder** [libgeos/geos#536]
i m facing the below issue while trying to install basemap

C:\Users\sahana.DESKTOP-VB0949B.000\AppData\Local\Programs\Python\Python310\Lib\site-packages\basemap-1.3.0\packages\basemap\utils>python data_utils.py install

C:\Users\sahana.DESKTOP-VB0949B.000\AppData\Local\Programs\Python\Python310\Lib\site-packages\basemap-1.3.0\packages\basemap\utils>python -c "import utils; utils.GeosLibrary('3.5.1').build(installdir='extern')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'utils' has no attribute 'GeosLibrary'

**Comment by pramsey** [comment]
You'll want to take this up with whomever packaged your python geos build, it's not a problem the upstream project (us) can address.
