### ISSUE TITLE
Example program cpp_read.cpp does not compile

### ISSUE THREAD

**Issue by sjtu-cz** [libgeos/geos#538]
g++ -std=c++11 -I/usr/local/include -D USE_UNSTABLE_GEOS_CPP_API cpp_read.cpp -o cpp_read -L/usr/local/lib -lgeos
/tmp/ccdtSvKl.o: In function `main':
cpp_read.cpp:(.text+0x32): undefined reference to `geos::io::WKTReader::WKTReader(geos::geom::GeometryFactory const&)'
cpp_read.cpp:(.text+0x210): undefined reference to `geos::io::WKTReader::~WKTReader()'
cpp_read.cpp:(.text+0x2b6): undefined reference to `geos::io::WKTReader::~WKTReader()'
collect2: error: ld returned 1 exit status

**Comment by dbaston** [comment]
Should be resolved by https://github.com/libgeos/geos/commit/a434b1fbf6981bd6fd10dee1705fbf66b8e4fc0a

**Comment by sjtu-cz** [comment]
this doesn't work for me

**Comment by yczcc** [comment]
I had the same problem with the latest version 3.10.1. but is ok with 3.9.2.

**Comment by pramsey** [comment]
Man, I have poked this 12 ways from Sunday and nothing gets those symbols into the library...
```
Sparrow:~/Code/geos-git/examples pramsey(main)% nm /usr/local/lib/libgeos.dylib | grep WKTRe
000000000020dba0 T __ZN4geos2io9WKTReader11getNextWordEPNS0_15StringTokenizerE
000000000020db40 T __ZN4geos2io9WKTReader12isNumberNextEPNS0_15StringTokenizerE
000000000020e060 T __ZN4geos2io9WKTReader13getNextCloserEPNS0_15StringTokenizerE
000000000020d560 T __ZN4geos2io9WKTReader13getNextNumberEPNS0_15StringTokenizerE
000000000020d380 T __ZN4geos2io9WKTReader20getNextCloserOrCommaEPNS0_15StringTokenizerE
000000000020cf20 T __ZN4geos2io9WKTReader20getNextEmptyOrOpenerEPNS0_15StringTokenizerERm
000000000020e2a0 T __ZNK4geos2io9WKTReader13readPointTextEPNS0_15StringTokenizerE
000000000020cca0 T __ZNK4geos2io9WKTReader14getCoordinatesEPNS0_15StringTokenizerE
000000000020e630 T __ZNK4geos2io9WKTReader15readPolygonTextEPNS0_15StringTokenizerE
000000000020e430 T __ZNK4geos2io9WKTReader18readLineStringTextEPNS0_15StringTokenizerE
000000000020e530 T __ZNK4geos2io9WKTReader18readLinearRingTextEPNS0_15StringTokenizerE
000000000020e8f0 T __ZNK4geos2io9WKTReader18readMultiPointTextEPNS0_15StringTokenizerE
000000000020d1e0 T __ZNK4geos2io9WKTReader20getPreciseCoordinateEPNS0_15StringTokenizerERNS_4geom10CoordinateERm
000000000020f250 T __ZNK4geos2io9WKTReader20readMultiPolygonTextEPNS0_15StringTokenizerE
000000000020c840 T __ZNK4geos2io9WKTReader22readGeometryTaggedTextEPNS0_15StringTokenizerE
000000000020f040 T __ZNK4geos2io9WKTReader23readMultiLineStringTextEPNS0_15StringTokenizerE
000000000020f460 T __ZNK4geos2io9WKTReader26readGeometryCollectionTextEPNS0_15StringTokenizerE
000000000020c790 T __ZNK4geos2io9WKTReader4readERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
```

**Comment by dbaston** [comment]
Is the client code not defining `GEOS_INLINE` ?

**Comment by pramsey** [comment]
Well, if I remove the inlining, the symbols do show up and the example program links as expected. 

No, the client code does not define GEOS_INLINE. That seems a little yucky doesn't it? Having to get your client code to match up with #defs to the library build. Hm, I didn't realize we had that problem.

**Comment by dbaston** [comment]
> That seems a little yucky doesn't it?

Yes, the whole `GEOS_INLINE` business is terrible. I have never seen that pattern in other code, and nobody seems to know why it's in GEOS, which makes me think it can be removed.

**Comment by pramsey** [comment]
I'm not sure who brought the pattern in, but it may have had to do with mingw build issues if my hazy recollection is right.

**Comment by pramsey** [comment]
What is the right pattern anyways? Just having the inline functions always in the header declared `inline`? No conditionality, the compiler does the right thing?

**Comment by dbaston** [comment]
AFAIK that is equivalent to just defining them in the class definition, as we do all over the place without problem, e.g. https://github.com/libgeos/geos/blob/146ee558a9a1eb7bcb2bbd52eaf92684cceef4cf/include/geos/index/chain/MonotoneChain.h#L115-L118

**Comment by pramsey** [comment]
So the inline keyword goes in the cpp file if desired? Signature in the header, implementation in the cpp, `inline` as a marker to potentially do magic?

**Comment by dbaston** [comment]
I think the full definition needs to be in the header, which is the case when `GEOS_INLINE` is defined. I'm doubtful that there is a use case for `GEOS_INLINE` being disabled.

**Comment by pramsey** [comment]
We did find for a while that the only way to compile on the Apple M1 was with inlining turned off. However, @hobu recently demonstrated that is no longer required.

**Comment by dbaston** [comment]
I think that was a consequence of GEOS' since-removed attempt to have an inlined AND linked copy of all functions.

**Comment by strk** [comment]
I brought the pattern in. Yes, it's yucky, but only for C++ client code, right ? Aren't users of the C++ API already warned about the danger of using it ? The pattern was introduced long ago, as a way to compare performance of inlined and non-inlined versions.

**Comment by hobu** [comment]
> I brought the pattern in. Yes, it's yucky, but only for C++ client code, right ? Aren't users of the C++ API already warned about the danger of using it ? The pattern was introduced long ago, as a way to compare performance of inlined and non-inlined versions.

It's a terrible design, provides two code paths, is fragile, and it breaks in unpredictable ways. GEOS developers themselves are C++ users of the GEOS C++ API and the inline stuff is code smell. The question is whether the project is open to it being made better, or wishes to live with the ugly weeds in the front corner of the garden continually regeneration project churn year after year.

**Comment by strk** [comment]
> It's a terrible design, provides two code paths

Well the idea was it would all be driven by geos_config.h, whereas
flipping a define there would change the inlining. I guess not all
translation units are including that file.

Of course C++ client code would need to use the same geos_config.h
for the switch to work for them.

**Comment by hobu** [comment]
Are we so far down the road that we can't back it out? It doesn't provide any value as far as I can tell and just makes things more complex for development and deployment.

**Comment by strk** [comment]
I've no objection in dropping the GEOS_INLINE macro

**Comment by pramsey** [comment]
Thanks @strk, I think it that time has come too.
