### ISSUE TITLE
VoronoiDiagramBuilder::setSites(const CoordinateSequence&) causes failure if sequence not sorted

### ISSUE THREAD

**Issue by ergpudb** [libgeos/geos#551]
VoronoiDiagramBuilder::setSites(const CoorindateSequence&), and also DelaunayTriangulationBuilder::setSites(const CoordinateSequence&), use RepeatedPointRemover to ensure only unique coordinates are processed. However this approach doesn't work unless the provided sequence is sorted (or any duplicate coordinates are otherwise right next to each other). Thus if the provided sequence is not sorted, and the coordinates are not unique already, triangulation fails.

The overloads of setSites that take a const Geometry* go through DelaunayTriangulationBuilder::unique which does do a sort first and thus they do not have this issue.

In previous versions of geos both forms went through DelaunayTriangulationBuilder::unique and did not have this issue.

**Comment by pramsey** [comment]
Do you have the version at which the change occurred?

**Comment by ergpudb** [comment]
Looks like 3.8?

The commit is here: https://github.com/libgeos/geos/commit/75c286d5b65caf47ffb46e37707568bf4f9cd387

**Comment by dbaston** [comment]
Looks like `DelaunayTriangulationBuilder::setSites(const CoordinateSequence& coords)` should read ` siteCoords = unique(&coords);`

**Comment by pramsey** [comment]
That change seems happy in CI, going to apply it. https://github.com/pramsey/geos/tree/main-551-setsites
