### ISSUE TITLE
error: #error "Could not find isnan function or macro

### ISSUE THREAD

**Issue by xiaochao00** [libgeos/geos#559]
> Description:

    Hi, I got this error when build version 3.5.2 from http://download.osgeo.org/geos/geos-3.5.2.tar.bz2;
    
![image](https://user-images.githubusercontent.com/16160841/152276657-575d03d2-f133-4582-94d4-10dd5fc610ac.png)

    I found some error like this in commit: https://github.com/libgeos/geos/pull/221, but it seem that this commit was not merge into tag:3.5.2 and branch:svn-3.5.2.

    Could I solve this issue by this commit? But could you merge this commit into main branch?

**Comment by pramsey** [comment]
Is there any reason you cannot build a more modern GEOS for your purposes? If you submit a PR against the branch of interest, I will review it.

**Comment by xiaochao00** [comment]
> Solution:
    I solved this issue by added " #define HAVE_IS_NAN=1" into file: [platform.h.cmake](./include/geos/platform.h.cmake), this was not a bug I thought.

> My Purpose:
    I was debugged a question in a older version, when used postgis(version 2.5.2), so I just want to recurring this problem in this version;

    It was a z-axis question when split 3d-polygon(for example A) by some 2d-polygons, used function intersection; The polygon A was split into A1,A2,A3,A4 four parts, here got a same point Pi(same x and y value) in four parts, but the point Pi had different z-axis value; 

    I want to get the a suitable z-axis value for the same point Pi, can you give me some help about this?

![image](https://user-images.githubusercontent.com/16160841/152627882-40bf907b-f68d-4c91-aa75-3291e5c7dab4.png)

**Comment by robe2** [comment]
I think this can be closed right?  I assume the last comment was just to answer @pramsey  question of what you need it for and the original issue you have resolved yourself @xiaochao00 . If you still have an issue you think is a bug feel free to open a different ticket.  If you just have a question about how to do something, use the geos mailing list - 

https://lists.osgeo.org/mailman/listinfo/geos-devel
