### ISSUE TITLE
RFC: Expose coordinate transformation in C API

### ISSUE THREAD

**Issue by brendan-ward** [libgeos/geos#560]
Is there interest in supporting a caller-defined coordinate transformation on geometries in the C API?  Apologies if this has already been discussed and ruled out, I didn't see this in the GH history.

For example, converting between projections or projected / unprojected (geographic) coordinates is a common operation, as well as scaling geometries.  Handling the actual transformation is outside the scope of GEOS, but it would be convenient to be able to mutate coordinates in place.

It is expected that the type / structure of the geometries remain the same in this operation, only that the specific x,y and optionally z coordinates are updated.

One can get part of the way there using `GEOSCoordSeq_getXY` / `GEOSCoordSeq_setXY` on the coordinate sequences of an existing geometry, but this does not update the associated envelope of that geometry - so subsequent operations get a bit awkward.  Exposing a C API to update the envelope of a geometry also seems weird.

In pygeos/shapely2 and elsewhere, we've taken the route of building up brand new geometries as part of applying the transformation, which involves a good bit of logic around the mechanics of different geometry types, creating coordinate sequences, rings, geometries, etc.  Instead, it would be better to clone (if necessary for caller's usage) and then mutate in place, provided the caller can define that as a C callback.

I'm not thinking that this is quite the use case of directly supporting an affine transformation (i.e., where the affine transform is a top-level parameter), like suggested in #482; affine transforms could be added separately.

Instead, I think we want a more general pattern for this that allows the caller to pass in a callback function and optional user data, and this gets applied to all coordinates.  If I follow correctly, this could be done using a `CoordinateFilter`.

The signature could be something similar to `GEOSSTRtree_query` using a callback pattern:

```
int GEOSGeom_applyCoordTransform(GEOSGeometry *geom, GEOSTransformCallback callback, void *userdata)
```
(return 0 on failure, 1 on success)

where the callback takes an x,y,z and sets those to associated `x_out`, etc pointers.
```
typedef int (*GEOSTransformCallback)(double x, double y, double z, double *x_out, double *y_out, double *z_out, void *userdata);
```
(callback returns 0 on failure, 1 on success)

I'm assuming here it is better to handle x,y,z all at once here and let the caller decide they don't want to update z.  (rather than having x,y and x,y,z variants of the above)

The `userdata` could be used to store whatever is needed for the user's specific transformation, be it an affine-like struct or other values necessary for transforming or scaling coordinates.

`GEOSGeom_applyCoordTransform` iterates over geometries and coordinate sequences, calls the callback, and finally updates the associated envelope for the geometry.

Not sure yet if this will work for either the pygeos/shapely2 case, which uses a Python function to do coordinate transformation, but I can see other use cases that stay at the C level using something like the above.

**Comment by dr-jts** [comment]
>  Exposing a C API to update the envelope of a geometry also seems weird.

Not at all.  And there is the existing `Geometry::geometryChanged()` method to do just this.

With this in place, you can build the desired functionality externally.  I think it's better to do that for now, and then *perhaps* in the future GEOS could add a coordinate transform callback something like what is suggested here.

**Comment by brendan-ward** [comment]
Ok, will work on a PR to expose `Geometry::geometryChanged()` in the C API; that should work for the use case here.  I'm struggling a bit with the name for it there though since we're not trying to modfiy the geometry, but rather instruct it to update its internal state.  

Some ideas:

* `void GEOSGeom_update(GEOSGeometry *geom)`
* `void GEOSGeom_updateEnvelope(GEOSGeometry *geom)`
* `void GEOSGeom_updateInternalState(GEOSGeometry *geom)` (a bit verbose but avoids possible future naming collisions)
* `void GEOSGeom_refresh(GEOSGeometry *geom)`
* `void GEOSGeom_notifyCoordsChanged(GEOSGeometry *geom)` (yuck)

**Comment by dr-jts** [comment]
To avoid craziness, please keep the name in synch with the GEOS C++ and JTS API.

Naming is hard.  Different people bring different perspectives and experience to the choice of names.  I chose the name for this method, and I think I was using a pattern that I saw in a different API.  That was 20 years ago...   But change for sake of semantic nuances just leads to verbosity and potential confusion.

**Comment by strk** [comment]
Why do you need to expose geometryChanged to C-API ? GEOSGeom_applyCoordTransform can do that internally, if GEOSTransformCallback returns a value saying if it changed something ?

**Comment by dr-jts** [comment]
> Why do you need to expose geometryChanged to C-API ?

I think it's a simpler design than adding all the machinery required by the proposed design for `GEOSGeom_applyCoordTransform`.

**Comment by brendan-ward** [comment]
So, `void GEOSGeom_geometryChanged(GEOSGeometry *geom)`?   (sorry, didn't think of that the first time!)
Or `void GEOS_geometryChanged(GEOSGeometry *geom)`?

Wasn't trying to criticize prior naming choices nor contribute to craziness, but merely trying to get the semantic right for the difference between a method on an object vs a function that takes an object as input - and for whatever reason didn't even think to suggest existing name as one of the alternatives... (still learning when C API names follow C++ names vs independent...)

**Comment by strk** [comment]
> > Why do you need to expose geometryChanged to C-API ?
> 
> I think it's a simpler design than adding all the machinery required by the proposed design for `GEOSGeom_applyCoordTransform`.

But what's the goal here ? Issue title is `Expose coordinate transormation` which means allow C code to possibly modify a geometry, which is otherwise currently mostly immutable (I think there's a single exception at the moment being GEOSNormalize, which allows modifying a GEOSGeometry, I don't think you can really change a GEOSGeometry using GEOSCoordSeq_setXY on the GEOSCoordSeq).

Having a separate function for ONLY marking a geometry as "changed" sounds like an breakage of "atomicity" of operations.
Any "editing" API should IMHO internallly take care of marking the geometry as changed (or not changed).

**Comment by dbaston** [comment]
> But what's the goal here ? Issue title is Expose coordinate transormation which means allow C code to possibly modify a geometry, which is otherwise currently mostly immutable

I think we should keep things immutable as much as possible. `GEOSNormalize` is an outlier that we can live with, but I'd want to see a really compelling justification before opening up more mutability. What's wrong with

`GEOSGeometry* GEOSGeom_applyCoordTransform(GEOSGeometry *geom, GEOSTransformCallback callback, void *userdata)`?

> Having a separate function for ONLY marking a geometry as "changed" sounds like an breakage of "atomicity" of operations.
Any "editing" API should IMHO internallly take care of marking the geometry as changed (or not changed).

Absolutely. I honestly pretty surprised to see `geometryChanged` wasn't a private method. That seems like mistake.

**Comment by brendan-ward** [comment]
> `GEOSGeometry* GEOSGeom_applyCoordTransform(GEOSGeometry *geom, GEOSTransformCallback callback, void *userdata)`

is just fine too, and likely much cleaner, esp. if the goal is to keep as much of the C API as immutable and atomic as possible.  For at least some of the cases where I was thinking it could be used, we'd clone the geometry immediately before mutating it so this handles that case better.

**Comment by dr-jts** [comment]
> Having a separate function for ONLY marking a geometry as "changed" sounds like an breakage of "atomicity" of operations. Any "editing" API should IMHO internallly take care of marking the geometry as changed (or not changed).

I agree, if the coordinate transform idea is implemented.  I was originally suggesting *not* to do this, to avoid complicating the API.  But given that it helps clients avoid the complexity of iterating through geometry structure, I'm now more in favour of the transform callback idea.

The current C++ API mirrors the JTS design.  This provides the `CoordinateSequenceFilter. isGeometryChanged` method to indicate geometry state has been mutated.

It's always nice to reflect C++ API terminology in the C API.  So I wonder if the new API could use the term `Filter` in some way?  But maybe  `GEOSGeom_applyCoordTransformFilter` is a bit of a mouthful, so I guess just introducing the concept of a `CoordTransform` is fine.   Should probably be called `GEOSCoordTransformCallback` though, so it matches.

**Comment by dr-jts** [comment]
I don't see why the `userData` has to be involved?

**Comment by dr-jts** [comment]
Is it possible to pass a `Coordinate` to the callback instead?  In case we say add an M ordinate to it?

**Comment by dbaston** [comment]
> I don't see why the userData has to be involved?

It provides external data to the filter. So if the filter is `translate` then `userData` could be the offset, for example.

> Is it possible to pass a Coordinate to the callback instead? In case we say add an M ordinate to it?

GEOS lacks a Coordinate type.

**Comment by strk** [comment]
A GEOSCoordinate opaque type wouldn't be bad to add

**Comment by dr-jts** [comment]
> > I don't see why the userData has to be involved?
> 
> It provides external data to the filter. So if the filter is `translate` then `userData` could be the offset, for example.

Can't this be passed into the supplied function externally?  

In any case, I don't think it should be called `userData`, since it's different to the Geometry `userData`.

**Comment by dbaston** [comment]
> A GEOSCoordinate opaque type wouldn't be bad to add

The problem is that it's either opaque (high-overhead) or stable (can't add M to it)

**Comment by dbaston** [comment]
> Can't this be passed into the supplied function externally?

Possible to do using global variables, but hackish and unconventional.

> In any case, I don't think it should be called userData, since it's different to the Geometry userData.

Please see prior usage in GEOS, such as the GEOSSTRtree_query.

**Comment by dr-jts** [comment]
> > A GEOSCoordinate opaque type wouldn't be bad to add
> 
> The problem is that it's either opaque (high-overhead) or stable (can't add M to it)

Agreed.  But this proposed transform function signature boxes the API in as well (maybe not as badly...)

**Comment by dbaston** [comment]
| Agreed. But this proposed transform function signature boxes the API in as well (maybe not as badly...)

Except that you can add more transform functions in the future.

**Comment by dr-jts** [comment]
> > Agreed. But this proposed transform function signature boxes the API in as well (maybe not as badly...)
> 
> Except that you can add more transform functions in the future.

By duplicating the entire new API?

**Comment by strk** [comment]
What's GEOSTransformCallback expected to receive and return ?

**Comment by dr-jts** [comment]
> What's GEOSTransformCallback expected to receive and return ?

See above:
```
typedef int (*GEOSTransformCallback)(double x, double y, double z, double *x_out, double *y_out, double *z_out, void *userdata);
```

**Comment by dbaston** [comment]
> By duplicating the entire new API?

I don't think having XY, XYZ, XYZM transforms is crazy, if that's what you mean.

**Comment by dr-jts** [comment]
> > By duplicating the entire new API?
> 
> I don't think having XY, XYZ, XYZM transforms is crazy, if that's what you mean.

Yep, I was assuming that would have to happen.  Along with these, right?
```
GEOSGeom_applyCoordTransformXY
GEOSGeom_applyCoordTransformXYZ
GEOSGeom_applyCoordTransformXYZM
```

**Comment by dr-jts** [comment]
> > > By duplicating the entire new API?
> > 
> > 
> > I don't think having XY, XYZ, XYZM transforms is crazy, if that's what you mean.
> 
> Yep, I was assuming that would have to happen. Along with these, right?
> 
> ```
> GEOSGeom_applyCoordTransformXY
> GEOSGeom_applyCoordTransformXYZ
> GEOSGeom_applyCoordTransformXYZM
> ```

I guess YAGNI says just assume XYZ for now...

**Comment by strk** [comment]
Ok, so same as a stable Coordinate, basically.
It looks like the naming should be more specific to a "Coordinate", because if I'm not wrong there are other kind of iterative functions into goemetries (ie: components?)

How slow would an opaque Coordinate object, with Coordinate_getX() getY() getZ() - and one day getM() ?

**Comment by dr-jts** [comment]
> How slow would an opaque Coordinate object, with Coordinate_getX() getY() getZ() - and one day getM() ?

Wouldn't that need to be heap-allocated?  So, slow...

**Comment by dbaston** [comment]
> How slow would an opaque Coordinate object, with Coordinate_getX() getY() getZ() - and one day getM() ?

Since nothing in the C CAPI can be inlined, pretty slow. The speedups from adding silly things like setXY instead of setX and setY are substantial.

> Wouldn't that need to be heap-allocated? So, slow...

I think you could be opaque and avoid heap allocation here as long as you don't give the client the ability to create coordinates. But the function calls for access would make it slow.

**Comment by dr-jts** [comment]
> > In any case, I don't think it should be called userData, since it's different to the Geometry userData.
> 
> Please see prior usage in GEOS, such as the GEOSSTRtree_query.

Can always fix that too. :). I think a name like `context` would indicate the role of that pointer better.  (It has a different lifecycle than the Geometry userData)

**Comment by dr-jts** [comment]
I wonder if the following callback signature would be more general, flexible and more powerful?
```
typedef int (*GEOSCoordinateSeqCallback)(GEOSCoordSequence* seq, int index, void *userdata);
```
* This provides the index of the point in the sequence, which can be useful.  
* It will work for both read-only and mutating callbacks.  
* It sidesteps the issue of how many ordinates to provide.
* It follows the underlying GEOS more closely

**Comment by dbaston** [comment]
> I think a name like context would indicate the role of that pointer better. (It has a different lifecycle than the Geometry userData)

I agree, but that ship sailed back in 2009. The purpose of the C API is stability; renaming things because we would do it differently now seems counterproductive.

> I wonder if the following callback signature would be more general, flexible and more powerful?

Definitely more general, though you're now incurring the overhead of two function calls per coordinate to read/set each coordinate value. I guess it depends how much value you place on minimizing the number of callback signatures.

**Comment by dr-jts** [comment]
> > I think a name like context would indicate the role of that pointer better. (It has a different lifecycle than the Geometry userData)
> 
> I agree, but that ship sailed back in 2009. The purpose of the C API is stability; renaming things because we would do it differently now seems counterproductive.

The parameter name is not part of the ABI though right?  But no matter...

> > I wonder if the following callback signature would be more general, flexible and more powerful?
> Definitely more general, though you're now incurring the overhead of two function calls per coordinate to read/set each coordinate value. I guess it depends how much value you place on minimizing the number of callback signatures.

Aren't accessor calls still required to fetch and store the ordinates with the other signature?  Or is the compiler optimization different?

**Comment by dbaston** [comment]
> Aren't accessor calls still required to fetch and store the ordinates with the other signature? Or is the compiler optimization different?

The difference is that coordinate access is happening on the C++ side where we can hook into something more efficient like `CoordinateFilter`. Here is an example implementation that might make it more clear (haven't tried to compile)

```
    typedef Geometry* (*GEOSTransformXYCallback)(double* x, double* y, void* userdata);

    Geometry*
    GEOSGeom_transformXY(GEOSContextHandle_t extHandle,
                         GEOSTransformXYCallback callback,
                         const Geometry* g,
                         void* userdata) {

        struct TransformFilter : public geos::geom::CoordinateFilter {
            TransformFilter(GEOSTransformXYCallback p_callback,
                            void* p_userdata) :
                            m_callback(p_callback),
                            m_userdata(p_userdata) {}

            void filter_rw(geos::geom::Coordinate* c) const final {
                m_callback(&(c->x), &(c->y), m_userdata);
            }

            GEOSTransformXYCallback m_callback;
            void* m_userdata;
        };

        return execute(extHandle, [&]() {
            TransformFilter filter(callback, userdata);
            auto ret = g->clone();
            ret->apply_rw(&filter);
            ret->geometryChanged();
            return ret.release();
        });
        }
    }
```

**Comment by dr-jts** [comment]
Hmm, well, maybe.  The calling path is so convoluted it seems it would really need profiling to see what the difference is.

Now that I think about it, perhaps `CoordinateSequenceFilter` could have just been called once per sequence, rather than n times. The client could just as easily iterate over the sequence itself.    That would be more efficient, right?

**Comment by dbaston** [comment]
>  it would really need profiling to see what the difference is.

That's what the benchmark I shared does! It shows the difference between calling `GEOSCoordSeq_getXY` for each coordinate, vs. iterating over the values on the C++ side using a `CoordinateFilter` like the one in my example.

This has become a long thread and I don't think I have more to contribute, so I'll summarize my comments on Brendan's proposal to:

- I think it's a good idea
- I would make XY and XYZ variants of it, for caller simplicity and future-proofing
- I would consider simplifying the signature to what I used in my example instead of having "in" and "out" arguments
- I would expose an immutable version only without hearing more about why this is a bad idea

**Comment by dr-jts** [comment]
> > it would really need profiling to see what the difference is.
> 
> That's what the benchmark I shared does! It shows the difference between calling `GEOSCoordSeq_getXY` for each coordinate, vs. iterating over the values on the C++ side using a `CoordinateFilter` like the one in my example.

Well, there is one difference in that in this case there has to be at least one function call for each coordinate (to the transform function).  Not sure how much that would reduce the difference in relative time.

**Comment by dr-jts** [comment]
I'll summarize my comments on Brendan's proposal to:
> 
> * I think it's a good idea
> * I would make XY and XYZ variants of it, for caller simplicity and future-proofing
> * I would consider simplifying the signature to what I used in my example instead of having "in" and "out" arguments
> * I would expose an immutable version only without hearing more about why this is a bad idea

How about start by implementing the XY case, and call it `GEOSGeom_transform` and `GEOSTransformCallback`. If and when needed can add a `GEOSGeom_transformXYZ` and `GEOSTransformXYZCallback`.  

Also if needed in the future there could be a variant that provides the entire CoordinateSequence and the index (to allow logic based on coordinate position, and possibly other coordinate values).
