### ISSUE TITLE
Exception: found two shells in EdgeRing list

### ISSUE THREAD

**Issue by fanvanzh** [libgeos/geos#567]
I got an exception:  "found two shells in EdgeRing list"

I want know which scenario when this error reported? And what it means? 

Thank you very much!

**Comment by pramsey** [comment]
Something in your workload has managed to trip a condition that "should never happen", 

https://github.com/libgeos/geos/blob/0d9bdb0e33333d0a025874c9f257dee1c760ef25/src/operation/overlayng/PolygonBuilder.cpp#L150

Was the input to your operation valid? If not, use makevalid to repair it and then try again. If it was valid input, can you isolate the operation and the data you were processing?

**Comment by pasquierjb** [comment]
I face the same issue when using the Python pygeos library with union_all and the following polygons:

`
import pygeos as pg

poly1 = pg.Geometry("POLYGON ((-3.3739513500645426 12.319170988964565, -4.369809126119213 13.154794881557066, -12.589262156305985 20.05173488766576, -11.593404380251314 19.216110995073258, -3.3739513500645426 12.319170988964565))")

poly2 = pg.Geometry("POLYGON ((-5.365666902173885 13.990418774149568, -4.369809126119214 13.154794881557066, -12.589262156305987 20.05173488766576, -13.585119932360659 20.88735878025826, -14.580977708415329 21.722982672850762, -15.576835484470001 22.558606565443263, -7.357382454283228 15.66166655933457, -6.361524678228557 14.826042666742069, -6.10115856517759 14.60756955730994, -5.365666902173885 13.990418774149568))")

pg.union_all([poly1, poly2])

>> GEOSException: AssertionFailedException: found two shells in EdgeRing list
` 

However, the GEOS exception disappears when I lower the resolution of my polygons

**Comment by pasquierjb** [comment]
3.9.1

**Comment by dr-jts** [comment]
JTS fails on this as well.  I'll investigate it there.

**Comment by pramsey** [comment]
This is gone in 3.12? Just ran test on my dev machine and got, 
```sql
SELECT st_union(
  'POLYGON ((-5.365666902173885 13.990418774149568, -4.369809126119214 13.154794881557066, -12.589262156305987 20.05173488766576, -13.585119932360659 20.88735878025826, -14.580977708415329 21.722982672850762, -15.576835484470001 22.558606565443263, -7.357382454283228 15.66166655933457, -6.361524678228557 14.826042666742069, -6.10115856517759 14.60756955730994, -5.365666902173885 13.990418774149568))'::geometry, 
  'POLYGON ((-3.3739513500645426 12.319170988964565, -4.369809126119213 13.154794881557066, -12.589262156305985 20.05173488766576, -11.593404380251314 19.216110995073258, -3.3739513500645426 12.319170988964565))'::geometry
);
```
```
      st_union      
--------------------
 010300000000000000
```

**Comment by dr-jts** [comment]
It's order-dependent.  Try reversing the operands:
```
bin/geosop -a "POLYGON ((-3.3739513500645426 12.319170988964565, -4.369809126119213 13.154794881557066, -12.589262156305985 20.05173488766576, -11.593404380251314 19.216110995073258, -3.3739513500645426 12.319170988964565))" 
-b "POLYGON ((-5.365666902173885 13.990418774149568, -4.369809126119214 13.154794881557066, -12.589262156305987 20.05173488766576, -13.585119932360659 20.88735878025826, -14.580977708415329 21.722982672850762, -15.576835484470001 22.558606565443263, -7.357382454283228 15.66166655933457, -6.361524678228557 14.826042666742069, -6.10115856517759 14.60756955730994, -5.365666902173885 13.990418774149568))" 
union

>>>> Run-time exception: AssertionFailedException: found two shells in EdgeRing list
```

**Comment by pramsey** [comment]
Yep that did it :(

**Comment by pramsey** [comment]
In main (3.13) I am seeing POLYGON EMPTY as the return now, regardless or ordering.
