### ISSUE TITLE
ARM64, ARM, and ppc64le regress failures on unit-shape-fractal-HilbertCode 

### ISSUE THREAD

**Issue by robe2** [libgeos/geos#579]
Our rasberry pi ARM bots have been failing on master recently.

https://debbie.postgis.net/view/GEOS/job/GEOS_Worker_Run/label=berrie/1557/consoleFull

```
17:54:42 The following tests did not run:
17:54:42 	329 - issue-issue-geos-837 (Disabled)
17:54:42 
17:54:42 The following tests FAILED:
17:54:42 	240 - unit-shape-fractal-HilbertEncoder (Failed)
17:54:42 Errors while running CTest
17:54:42 gmake[4]: *** [Makefile:125: test] Error 8
17:54:42 make[3]: *** [CMakeFiles/check.dir/build.make:76: CMakeFiles/check] Error 2
17:54:42 make[2]: *** [CMakeFiles/Makefile2:612: CMakeFiles/check.dir/all] Error 2
17:54:42 make[1]: *** [CMakeFiles/Makefile2:619: CMakeFiles/check.dir/rule] Error 2
17:54:42 make: *** [Makefile:320: check] Error 2
17:54:42 Build step 'Execute shell' marked build as failure
```

The issue has been happening at least since Feb 24th.  Unfortunately looks like I didn't keep the old logs.

**Comment by pramsey** [comment]
Cannot replicate on AWS ARM64, so don't really have a path forward to address this.
```
100% tests passed, 0 tests failed out of 418

Total Test time (real) =  11.39 sec
```

**Comment by robe2** [comment]
> Cannot replicate on AWS ARM64, so don't really have a path forward to address this.
> 
> ```
> 100% tests passed, 0 tests failed out of 418
> 
> Total Test time (real) =  11.39 sec
> ```

What OS is that, I thought AWS is CentOS based or are you using a different distro?  FWIW the berries are running Debian 11 and GCC 10.2.1

**Comment by robe2** [comment]
I just tested on Ubuntu Jammy running ARM64 and was able to replicate it using cmake version 3.22.1

I built like this:

```
cd geos
mkdir _build
cd _build
cmake    -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=/usr/local     ..
ctest
```
Output is
```
The following tests FAILED:
        243 - unit-shape-fractal-HilbertEncoder (Failed)
Errors while running CTest
Output from these tests are in: /home/robe/projects/geos/_build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

Then running
```
ctest --return-failed --output-on-failure
```

I get

```
Test project /home/robe/projects/geos/_build
    Start 243: unit-shape-fractal-HilbertEncoder
1/1 Test #243: unit-shape-fractal-HilbertEncoder ...***Failed    0.01 sec
===============================
  GEOS Unit Test Suite
===============================

geos::shape::fractal::HilbertEncoder: .[2=F].

---> group: geos::shape::fractal::HilbertEncoder, test: test<2>
     problem: assertion failed
     failed assertion: `Values are not equal: expected `0` actual `10``

tests summary: failures:1 ok:2


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.02 sec

The following tests FAILED:
        243 - unit-shape-fractal-HilbertEncoder (Failed)
Errors while running CTest

```

**Comment by pramsey** [comment]
Can you make it go boom in a Debug build?

**Comment by robe2** [comment]
Yes fails on Debug too:

```
rm -rf __build
cd __buld
cmake     -DCMAKE_BUILD_TYPE=Debug     -DCMAKE_INSTALL_PREFIX=/usr/local     ..
ctest
 ctest --rerun-failed --output-on-failure
```

Yields what looks to be the same to me.
```

    Start 243: unit-shape-fractal-HilbertEncoder
1/1 Test #243: unit-shape-fractal-HilbertEncoder ...***Failed    0.02 sec
===============================
  GEOS Unit Test Suite
===============================

geos::shape::fractal::HilbertEncoder: .[2=F].

---> group: geos::shape::fractal::HilbertEncoder, test: test<2>
     problem: assertion failed
     failed assertion: `Values are not equal: expected `0` actual `10``

tests summary: failures:1 ok:2


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.03 sec

The following tests FAILED:
        243 - unit-shape-fractal-HilbertEncoder (Failed)
Errors while running CTest
```

I do have GEOS 3.10.2 installed from system packages, and it's possible the berries have that too.

Let me uninstall that to make sure it's not trying to use that one

**Comment by robe2** [comment]
I uninstalled GEOS 3.10.2 (which forced uninstall of GDAL). I still get the same error.  Anything else you want me to try?

**Comment by robe2** [comment]
This one might be related - https://github.com/cockroachdb/cockroach/issues/81290

The person complaining on that ticket is running IBM power ppc64le

**Comment by pramsey** [comment]
For amusement, the HilbertEncoder was, in the case when handed a zero-size envelope, creating a situation where a divide-by-zero was happening. The x64 platform said the answer was `+Inf` and the ARM platform said it was just `inf`. The fun came when that signed integer result was cast into a `uint32`, at which point the x64 thought it was `0` and the ARM said it was `4294967295`. The two answers necessarily diverged from there.

**Comment by prashantkhoje** [comment]
> This one might be related - [cockroachdb/cockroach#81290](https://github.com/cockroachdb/cockroach/issues/81290)
> 
> The person complaining on that ticket is running IBM power ppc64le

All the tests now pass on ppc64le.

Thank you!
