### ISSUE TITLE
C API: GEOSInterpolate does not produce point that intersects line

### ISSUE THREAD

**Issue by brendan-ward** [libgeos/geos#585]
Reported in [geopandas #2363](https://github.com/geopandas/geopandas/pull/2363#issuecomment-1061962104).

Given a line `'LINESTRING (969013.331604 150484.314209, 969014.981995 150571.094788)'` and an interpolate distance of `76.506`, `GEOSInterpolate` produces a point `'POINT (969014.78633 150560.806377)'` that does not intersect the original line.   The interpolated point is very very close (`4.3142111939433005e-11` units away).  Testing a variety of other points along the line produces the same result; the only interpolated points that intersect the line are at the endpoints (distance = 0 or distance = length of line).

It seems like `GEOSInterpolate` _should_ always produce a point that intersects the input line.

**Comment by pramsey** [comment]
![screenshot_850](https://user-images.githubusercontent.com/113883/157304747-d620470b-a3e0-4c7b-abed-731eba26254c.png)

**Comment by pramsey** [comment]
[IEEE double](https://en.wikipedia.org/wiki/Double-precision_floating-point_format) has a 52 bit mantissa, which is a lot of precision, but it is not infinite precision.

**Comment by brendan-ward** [comment]
Naive question: is it possible for `GEOSInterpolate` to use a similar internal tolerance as what is used within the `intersects` predicate in this case?  

Mathematically, it seems reasonable that two arbitrary and independent geometries would not intersect at full float precision, but in this case since one is derived from the other, it would be nice to preserve that symmetry (if one is derived from the other, it should intersect).

If it is expected that interpolated points do not intersect due to floating point precision issues, we should probably note that in the docstring for `GEOSInterpolate`.

A couple other potential solutions came to mind, but not sure if they are suitable in this case for callers of this function (to be done by caller, not within GEOS):
1. use `GEOSDistanceWithin` predicate instead of `GEOSIntersects`
2. add a new vertex into the line at the interpolated point; this should better ensure that the point intersects the line (but some overhead to doing this, and it may not be appropriate to modify the input line)

**Comment by pramsey** [comment]
Well, modifying the input is definitely out, in my mind.

More docs are always appreciated.

A tolerance model for predicates is something that's been on the plate of possibility for a long time, but wouldn't really "solve" the issue of surprise for users new to this behavior (intersection(A, B) might not intersect A or B) and globally applying a minimum tolerance on all operations would a different kind of surprise that would cause different kinds of annoyance. It's all very Solomonic.

**Comment by dr-jts** [comment]
> Naive question: is it possible for `GEOSInterpolate` to use a similar internal tolerance as what is used within the `intersects` predicate in this case?

No.  It's computationally impossible to produce floating-point numbers that all lie exactly on an arbitrary line.

> A couple other potential solutions came to mind, but not sure if they are suitable in this case for callers of this function (to be done by caller, not within GEOS):
> 
> 1. use `GEOSDistanceWithin` predicate instead of `GEOSIntersects`

This is the recommended approach, until such time as the spatial predicates gain the capabiltiy to use a distance tolerance

> 2. add a new vertex into the line at the interpolated point; this should better ensure that the point intersects the line (but some overhead to doing this, and it may not be appropriate to modify the input line)

In general this is not possible, because:
* as you say, usually it's not possible to modify the input data
* even if possible to modify the input, this doesn't scale to an arbitrary number of queries
