### ISSUE TITLE
Remove RETURN_UNIQUE_PTR

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#589]
This shim to get around warnings for GCC <= 4.9 may have outlived its day. Certainly we have no shortage of unshimmed returns of std::unique_ptr at this point.

**Comment by dbaston** [comment]
What gcc 4.9 does not deal with is returning a value of type `std::unique_ptr<CoordinateArraySequence>` from a function with return type `std::unique_ptr<CoordinateSequence>`. Dropping support for an 8-year old compiler seems reasonable, though.
