### ISSUE TITLE
GEOSOffsetCurve no longer raises for non-linestring inputs

### ISSUE THREAD

**Issue by jorisvandenbossche** [libgeos/geos#592]
Triggered by the refactor in https://github.com/libgeos/geos/pull/530 (`GEOSOffsetCurve_r` now uses the new `OffsetCurve::getCurve()` instead of `BufferBuilder::bufferLineSingleSided()`), the function no longer raises an error for non-linestring geometries.

Using Shapely built against main:

```python
>>> import shapely                                                                                                                                                                                             
>>> shapely.offset_curve(shapely.Point(1, 1), 0.0)                                                                                                                                                             
<shapely.geometry.LineString LINESTRING Z EMPTY>
```

while before this gave

```python
>>> shapely.offset_curve(shapely.Point(1, 1), 0.0)
...
GEOSException: IllegalArgumentException: BufferBuilder::bufferLineSingleSided only accept linestrings
```

The doc comment for GEOSOffsetCurve also still indicates that this is the expected behaviour:

https://github.com/libgeos/geos/blob/f2784527e9b397817ccdcba207bc17b21ea0c976/capi/geos_c.h.in#L2323-L2324

(I personally don't have a strong opinion on whether the above is "wrong", we can also update our tests on the Shapely side)

The previous behaviour comes from:

https://github.com/libgeos/geos/blob/f2784527e9b397817ccdcba207bc17b21ea0c976/src/operation/buffer/BufferBuilder.cpp#L134-L139

**Comment by pramsey** [comment]
I can't remember now if we try to have a return value for every input type in the new code. I wonder if feeding it a polygon also works.

**Comment by dr-jts** [comment]
> I wonder if feeding it a polygon also works.

Yep - OffsetCurve for polygons is basically the buffer boundary line.  Tests are [here](https://github.com/libgeos/geos/blob/46f61f525ce8b392b2676cadcdb2268ef3b0a9ed/tests/unit/operation/buffer/OffsetCurveTest.cpp#L222).

**Comment by jorisvandenbossche** [comment]
Thanks for the feedback and doc update!

**Comment by jorisvandenbossche** [comment]
Continuing our conversation at https://github.com/libgeos/geos/commit/723fe859418708784ae43275ff5e5ebf8a83e4fb#r73465596 here:

> Actually the result for polygons is not the same as the result for "the linestring of their boundary", because the offset curve of a polygon is a closed ring.

Triggered by your comment I was wondering what this exactly means in practice (i.e. what the difference is of an offset curve of a linestring vs a ring). So for a `box(0, 0, 2, 2)`, the left is the box and its offset curve of 1.0, and the right is the box' boundary and its offset curve:

![Figure_2](https://user-images.githubusercontent.com/1020496/168276262-e328c57d-86a3-4831-b318-810954bf1965.png)

One thing I noted, though, is that to achieve the result above, I needed to use a different sign for the offset distance (to get a left or right offset) in both cases:

```
>>> import shapely
>>> poly = shapely.box(0, 0, 2, 2)                                                                                                                                                                             
>>> poly                                                                                                                                                                                                       
<shapely.Polygon POLYGON ((2 0, 2 2, 0 2, 0 0, 2 0))>
>>> poly.boundary                                                                                                                                                                                              
<shapely.LineString LINESTRING (2 0, 2 2, 0 2, 0 0, 2 0)>

>>> shapely.offset_curve(poly.boundary, 1.0) 
<shapely.LineString LINESTRING Z EMPTY>
>>> shapely.offset_curve(poly.boundary, -1.0)
<shapely.LineString LINESTRING (3 0, 3 2, 2.981 2.195, 2.924 2.383, 2.831 2....>
```

So for the linestring I need a negative value (for getting an offset on the right side). But for the polygon, I need the opposite:

```
>>> shapely.offset_curve(poly, -1.0)                                                                                                                                                                          
<shapely.LineString LINESTRING Z EMPTY>
>>> shapely.offset_curve(poly, 1.0)                                                                                                                                                                           
<shapely.LineString LINESTRING (2 -1, 0 -1, -0.195 -0.981, -0.383 -0.924, -0...>
```

while the orientation of the polygon ring and the linestring is the same? (so I expected to need to the same sign)
