### ISSUE TITLE
Request to add GEOSRemoveRepeatedPoints to CAPI

### ISSUE THREAD

**Issue by mwtoews** [libgeos/geos#599]
The idea is to add `GEOSRemoveRepeatedPoints` to the CAPI based on [`src/operation/valid/RepeatedPointRemover.cpp`](https://github.com/libgeos/geos/blob/7736b8710ab18db759790283054b96d3893b2c5d/src/operation/valid/RepeatedPointRemover.cpp)

Note that PostGIS has [`ST_RemoveRepeatedPoints`](https://postgis.net/docs/ST_RemoveRepeatedPoints.html) (based on [`postgis/lwgeom_functions_basic.c`](https://github.com/postgis/postgis/blob/781a40f92ffce904272f2e50f7911b0a4af95969/postgis/lwgeom_functions_basic.c#L2889-L2919) and various `lwgeom_remove_repeated_*` functions in [`liblwgeom/lwgeom.c`](https://github.com/postgis/postgis/blob/master/liblwgeom/lwgeom.c))

One limitation that I can see from GEOS' `RepeatedPointRemover.cpp` is that there is no tolerance parameter, like there is with PostGIS. It might be necessary to also enhance `RepeatedPointRemover` to enable a tolerance parameter.

**Comment by pramsey** [comment]
The tolerance aspect of repeated points removal can actually be pretty important for speeding up more intense algorithms like DP simplification. Running a gentle repeated points removal with a small tolerance can drop a bunch of useless points and made subsequent more intense DP simplification go faster (was a part of MVT generation for a while).

**Comment by mwtoews** [comment]
So that really means `tolerance` will need to be part of the expected CAPI signature:
```
extern GEOSGeometry GEOS_DLL *GEOSRemoveRepeatedPoints(
    const GEOSGeometry* g,
    double tolerance);
```
which means an enhancement to the C++ side would need to take precedence.

**Comment by dr-jts** [comment]
Or add the C API, but only support `tolerance = 0` for now.

**Comment by dr-jts** [comment]
One note: removing points with a tolerance can produce invalid polygonal geometry.  Worth a note in the doco, at least (with a link to `GeometryFixer` perhaps).
