### ISSUE TITLE
ios geos 3.10.2 build geostest.c failing

### ISSUE THREAD

**Issue by iulian0512** [libgeos/geos#600]
I successfully built geos for ios (simulator  x86_64) with the following [makefile](https://gist.github.com/iulian0512/b16377ebbb99184db2d7fb6e9fc2fc88#file-makefile)
and produced the following [build output](https://gist.github.com/iulian0512/b16377ebbb99184db2d7fb6e9fc2fc88#file-build-output)

I made a minimal reproducible example that tries to run /geos/tests/geostest/geostest.c from the geos source package and it fails at line 176 when trying to create a GEOSGeom from wkb (stderr message 'Round WKB conversion failed').
[ios minimal example](https://gist.github.com/iulian0512/b16377ebbb99184db2d7fb6e9fc2fc88#file-ios-application-entry-point-main-m)

I have no ideea why basic operations fail and i got no indication like an error,warning,etc that something is wrong or i am doing something wrong. I have no clue how to debug this issue.

[iosgeostest.zip complete xcode project for minimal example](https://github.com/libgeos/geos/files/8604187/iosgeostest.zip)
[entire gist](https://gist.github.com/iulian0512/b16377ebbb99184db2d7fb6e9fc2fc88)

**Comment by pramsey** [comment]
Well the failing test is attempting to round-trip data through WKB, so the first thing I would do is (a) set up the same test but with a much smaller geometry and then (b) see if I can see where there are differences between the expected and generated output.

**Comment by iulian0512** [comment]
> Well the failing test is attempting to round-trip data through WKB, so the first thing I would do is (a) set up the same test but with a much smaller geometry and then (b) see if I can see where there are differences between the expected and generated output.

i tried with a simple polygon 6 vertices, same error. 
i also tried the following using the reentrant api 

```
   GEOSContextHandle_t ghandle=initGEOS_r(geos_msg_handler, geos_msg_handler);
    GEOSContext_setErrorHandler_r(ghandle, geos_msg_handler);
    GEOSContext_setNoticeHandler_r(ghandle, geos_msg_handler);

      /* Read WKT into geometry object */
    
      GEOSWKTReader* reader = GEOSWKTReader_create_r(ghandle);
    
      GEOSGeometry* g1 = GEOSWKTReader_read_r(ghandle,reader, "POLYGON((30.87911367416382 43.72344388187324,31.764607429504395 44.07602448331505,31.451218128204346 43.34428112059268,30.87911367416382 43.72344388187324))");
      GEOSGeometry* g2 = GEOSWKTReader_read_r(ghandle,reader, "POINT(31.36577367782593 43.72420372616932)");

    int res= GEOSContains_r(ghandle,g1, g2);
    printf("\n geos contains res: %x",res);
```

and it returns 0 invariably however in postgis same polygon and point returns true

```  SELECT ST_Contains(ST_GeomFromText('POLYGON((30.87911367416382 43.72344388187324,31.764607429504395 44.07602448331505,31.451218128204346 43.34428112059268,30.87911367416382 43.72344388187324))'),ST_GeomFromText('POINT(31.36577367782593 43.72420372616932)')); ```
polygon and point used for testing
![image](https://user-images.githubusercontent.com/16035099/166422364-be2407ec-0738-45e8-a0c1-28f9e21d4cd4.png)


again no errors or warnings of any kind it just does not work.

**Comment by pramsey** [comment]
After you read them in, print them back out as wkt. I wonder if you have an honest-to-goodness endian thing going on.

**Comment by iulian0512** [comment]
The problem was the toolchain file https://github.com/leetal/ios-cmake without it everything works as expected, i am leaving here the makefile that produces a geos 3.10.2 working static lib for ios simulator just in case.

https://gist.github.com/iulian0512/9e523c14d72a7dfc3adc9f35b1a1de5e
