### ISSUE TITLE
libgeos++-dev for release 3.10.2 seems to break Debian package rules

### ISSUE THREAD

**Issue by michael-downey** [libgeos/geos#602]
I really mean for this to be a question or comment since I realize this has to do with a Packaging system.  The current 3.10.2 Debian package for libgeos++ looks to be compiling with GEOS_INLINE set, which I assume is the default setting, and because of policies that Debian has, they explicitly remove the .inl files when setting up the package.  This basically makes the package unusable as anyone using it needs to also define GEOS_INLINE otherwise you get unresolved external symbols for things like Coordinate(x, y,z) since those things are built at compile time not link time.

I realize there is much debate on C++ interfaces and the use of a C++ library, but I really like using the C++ API and GEOS library in general, and would like to know if there is anything that can be done to make setting up the libgeos++ package simpler for developers.  Do we have a plan for 3.11.0 release soon?  I am currently downloading the 3.10.2 release tar.gz and copying in the .inl files into the /usr/include/geos paths.  I am also aware that I can fully compile GEOS but I really would prefer not to need to do that.  Or is there someone who could persuade the Debian maintainers to either recompile libgeos++ to not use GEOS_INLINE or to include the .inl files?

Here is also the Debian bug report for this problem that some other developer submitted: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010002

**Comment by pramsey** [comment]
Well, the inl files have been removed now, for whatever that is worth. So next release won't have that issue. Whether the full include set is packaged is up to the package maintainer. You might find that just checking out and building GEOS isn't all that hard. It really only depends on having cmake and a c++ compiler.

**Comment by michael-downey** [comment]
ok.  I have built GEOS many times and we have both Linux and Windows versions we maintain.  The hope was that for Linux we didn't need to maintain our own builds and would use the official distro packages as that is what our customers would be using, just not the -dev versions.  It makes packaging a bit more expensive for us for both supporting developers to install workable systems on both Windows and Linux and for supporting different versions of Ubuntu or whatever Linux distro our customers wish to use.  And if it is an official distro build it has been "tested" by the distribution and officially supported.

Also since GEOS is LGPL this would also mean we'd need to provide full source code access since it is possible we would build it different than the default.

What is the plan for the rext release date?

**Comment by pramsey** [comment]
Early fall of this year would be typical.

**Comment by michael-downey** [comment]
ok, thank you.  I will plan accordingly.
