### ISSUE TITLE
Generic GEOSParameter type in CAPI

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#627]
The CAPI already has two parameter types `GEOSBufferParams` and `GEOSMakeValidParams` along with a small herd of setters and getters for those types. As more GEOS functions with fun collections of optional parameters show up (the hull functions had more than we exposed) it feels like it would be cleaner to have a single `GEOSParams` to handle all those cases.

```
GEOSParams_create();
GEOSParams_getDouble(const char* paramName, &double value);
GEOSParams_getInteger(const char* paramName, &int value);
GEOSParams_setDouble(const char* paramName, double value);
GEOSParams_setInteger(const char* paramName, int value);
GEOSParams_destroy();
```

**Comment by pramsey** [comment]
As applied to the new polygon hull function, for example, see https://github.com/pramsey/geos/blob/main-params/capi/geos_c.h.in#L3669-L3671

**Comment by dr-jts** [comment]
Another concern I have is verbose code for the client.  Instead of a one-line call the caller will have to:

- create a param object
- populate it
- call the operation with it
- free the param object

See `GEOSBufferParams` test for an [example](https://github.com/libgeos/geos/blob/main/tests/unit/capi/GEOSBufferTest.cpp#L502-L506) (which doesn't include the free).

**Comment by dbaston** [comment]
>  Instead of a one-line call 

I don't think it has to be an either/or - you can cover common cases with functions like `GEOSBuffer` and use a params object for more esoteric configuration.

**Comment by dr-jts** [comment]
> I don't think it has to be an either/or - you can cover common cases with functions like `GEOSBuffer` and use a params object for more esoteric configuration.

For sure.  But that raises the question of when should a generic parameter block be introduced?  The reason it is used in `buffer` is that there are effectively several different signatures depending on which which combination of styles is desired.  Also, there is a definite possibility that more style parameters will be introduced (in fact, I have a nascent PR to add some!)

For `GEOSPolygonHullSimplifier` (to use a current case) the situation is simpler.  All uses can be covered by 3 parameters:
* `isOuter` boolean to indicate hull type
* a code to indicate which kind of control parameter is being provided (currently vertex count fraction or area delta ratio - but conceivably some more will be added, such as absolute target vertex count or area delta)
* the control parameter value

So this can be handled by a single signature.  (@pramsey: perhaps we should change to having a single signature, and add an integer `controlParamType` code, with constants provided for the supported values?)

**Comment by pramsey** [comment]
I don't think we managed to convince ourselves this juice was worth the squeeze.
