### ISSUE TITLE
Port JTS BoundaryChainNoder to make CoverageUnion faster

### ISSUE THREAD

**Issue by dr-jts** [libgeos/geos#638]
See https://github.com/locationtech/jts/pull/891.  The JTS `BoundaryChainNoder` makes polygon coverage union faster, by reducing memory allocation and topology graph complexity.  

This can be ported as-is, to work with OverlayNG `CoverageUnion`.  

The technique could also be used in the Polygonizer-based [CoverageUnion](https://github.com/libgeos/geos/blob/main/src/operation/union/CoverageUnion.cpp) (by @dbaston)

It is worth exploring if the approach to detecting duplicate segments can be optimized further, perhaps by:
* use a `SegmentView`-style facade class, to avoid copying coordinates
* use a vector-based  "sort/remove dups", rather than using a `unordered_set`.

**Comment by pramsey** [comment]
This happened in #655
