### ISSUE TITLE
can we compare two float number like following?

### ISSUE THREAD

**Issue by rhengzi** [libgeos/geos#649]
![image](https://user-images.githubusercontent.com/15956175/177282397-ff0958b0-944b-49e3-bc1f-642874112dbc.png)

**Comment by pramsey** [comment]
I do not understand the question. Yes and also no? For some use cases a tolerance might make more sense. For others, identity within the constraints of IEEE representation is fine.

**Comment by rhengzi** [comment]
you're right. I have a question. if given two same double numbers, we can compare with "==".  may we sometime get True, some other time get False?

**Comment by rhengzi** [comment]
got it. thx
