### ISSUE TITLE
GEOS C Error when creating a geometry on an M1 Mac

### ISSUE THREAD

**Issue by arielkaluzhny** [libgeos/geos#651]
Getting different flavors of a GEOS C Error whenever I try to create a geometry. `Point` & `LineString` work fine, but `Polygon`, `MultiPoint`, `MultiLineString`, and `MultiPolygon` all fail. 

I know the geometry is valid because it can be created via `GEOSGeometry`. Example:

```
from django.contrib.gis.geos import Point, Polygon, MultiPoint, MultiPolygon, MultiLineString, LineString
from django.contrib.gis.geos.geometry import GEOSGeometry

poly = GEOSGeometry('POLYGON((4 4, 4 4, 4 4, 4 4))')
poly.coords()
>>> (((4.0, 4.0), (4.0, 4.0), (4.0, 4.0), (4.0, 4.0)),)

poly2 = Polygon(((4, 4), (4, 4), (4, 4), (4, 4)))
>>> GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSGeom_createPolygon_r".

ls1 = LineString((0, 0), (1, 1))
ls2 = LineString((2, 2), (3, 3))
mls = MultiLineString(ls1, ls2)
>>> GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSGeom_createCollection_r".

 MultiPoint(Point(0, 0), Point(1, 1))
>>> GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSGeom_createCollection_r".
```

Operating System & other info:

- MacOS Monterey, M1 chip
- gdal installed via homebrew (3.5.1)
- Python 3.8.12, Django 3.2
- also have geos and proj installed previously as dependencies via homebrew
- Have set:
    ```
    GDAL_LIBRARY_PATH="/opt/homebrew/lib/libgdal.dylib"`
    GEOS_LIBRARY_PATH="/opt/homebrew/lib/libgeos_c.dylib"
    ```

Exact same code is working on an older Mac setup w/ the same environment just fine.

Have also now tried Python 3.9 and reinstalling all related brew packages.

--- 

> I think this is the right place for this, please let me know if not or if you need any other information! Thank you.

**Comment by pramsey** [comment]
Going to need a fix for this. Until one of the dev team gets an M1 or M2, we've got no way to reproduce.

**Comment by arielkaluzhny** [comment]
> Going to need a fix for this. Until one of the dev team gets an M1 or M2, we've got no way to reproduce.

Turns out it was an issue with the Django version we were using. Upgrading to Django 4.0.1 or higher after they fixed the bug will take care of it: https://github.com/django/django/blob/4f284115a9181990f713d5167b25628fa171a5e4/docs/releases/4.0.1.txt#L67-L70

Feel free to close or do whatever you see fit with this.
