### ISSUE TITLE
GEOSGeom_setPrecision flattens multi-geometries

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#662]
So no-op precision reductions end up having a spurious type change as well:
```
geosop -a "MULTILINESTRING((0 0,10 10))" -f wkt reducePrecision 1

LINESTRING (0 0, 10 10)
```

**Comment by pramsey** [comment]
@dr-jts thoughts?

**Comment by pramsey** [comment]
Reported in https://trac.osgeo.org/postgis/ticket/5208

**Comment by dr-jts** [comment]
It seems reasonable to preserve the collection type of the input.
