### ISSUE TITLE
SingleSided buffer shows artifacts

### ISSUE THREAD

**Issue by hmundle** [libgeos/geos#665]
When I want to create a single sided buffer, GEOS shows strange result even for easy line inputs.

This is my input (`geom`): `LINESTRING (50 50, 150 150, 150 100, 150 0)`
![image](https://user-images.githubusercontent.com/1384773/185927212-6d55d89b-0c46-43fa-ac47-f72f4bffc950.png)

This is my implementation:
``` c++
geos::operation::buffer::BufferParameters bp;
bp.setSingleSided(true);
geos::operation::buffer::BufferOp ob(geom.get(), bp);
std::unique_ptr<Geometry> g3 = ob.getResultGeometry(d);
```
with `d = -21.0`

The resulting output shows artifacts from the seconds line segment:
`POLYGON ((50 50, 129 129, 129 150, 129.25925925925927 150, 143.92517768386912 143.92517768386912, 150 150, 150 141.408903891521, 164.66591842460988 135.33408157539012, 164.8492424049175 135.1507575950825, 150 120.30151519016499, 150 100, 150 0, 129 0, 129 99.30151519016499, 64.8492424049175 35.1507575950825, 50 50))`
![image](https://user-images.githubusercontent.com/1384773/185927459-c6ec5f98-3c74-4f8c-a784-62afcd287961.png)

If I am removing the vertex in the vertical line (`geom` = `LINESTRING (50 50,150 150, 150 0)`) the output is valid:
`POLYGON ((50 50, 150 150, 150 0, 129 0, 129 99.30151519016499, 64.8492424049175 35.1507575950825, 50 50))`
![image](https://user-images.githubusercontent.com/1384773/185927687-3ce481d7-4d6b-44f7-b1f0-49d7d98193c9.png)

If I am changing to `d = -20.0`, the output is valid as well:
POLYGON ((50 50, 150 150, 150 100, 150 0, 130 0, 130 101.7157287525381, 64.14213562373095 35.85786437626905, 50 50))
![image](https://user-images.githubusercontent.com/1384773/185928236-4ee3a93e-49ea-4557-bd02-5fe34692b285.png)

I am using GEOS 3.11.0.

Why do tiny changes result in a big change in the output?
I can imagine, that it is difficult to implement a single sided buffer algorithm for any strange input line. But this one is not strange, is it?

Some reference I found on the Internet:
https://trac.osgeo.org/geos/ticket/712 (closed with wontfix)
https://trac.osgeo.org/geos/ticket/810 (still open)
http://lin-ear-th-inking.blogspot.com/2010/11/single-sided-buffers-in-jts.html (from Dr JTS)

I was thinking of fixing this issue, with the following approach:
* Splitting the resulting polygon at the input line.
* From that result only keeping the biggest polygon

Unfortunately I do not know, how to implement the polygon split in GEOS. 
But doing this QGIS or OpenJump result in much better single-sided buffer (even if still not perfect). I tested this with a 50.000 buffer on the coastline from 
https://trac.osgeo.org/geos/ticket/810
With cleanup approach:
![image](https://user-images.githubusercontent.com/1384773/185931785-d8ddc74b-e053-4850-907a-3dc61e34c21f.png)
vs. raw single-sided buffer output
![image](https://user-images.githubusercontent.com/1384773/185937190-334bb680-d9dd-4712-9f1c-bee704d3e407.png)

**Comment by pramsey** [comment]
Please check out the OffsetCurve functionality in the current main, the SingleSidedBuffer is deprecated and will disappear at some point in the future.

**Comment by strk** [comment]
For the record: deprecation of SingleSidedBuffer happened in 2011:  https://github.com/libgeos/geos/commit/d48b19a944437ac04175b01887c770341aa05a1c

**Comment by strk** [comment]
This is a picture of how OffsetCurve (in green) compares with SingleSidedBuffer (in pink) for a distance of 21 on the original input (arrowed line):

![image](https://user-images.githubusercontent.com/289678/233985356-af75af51-7a36-4e11-8d5d-ef37eda014be.png)

In this case connecting the endpoints of offset curve to the endpoints of the input line would give what we're after, but I'm afraid an offset curve is not always a single line then the input line is complex, so the goal of a "single sided buffer" is probably still one that would be good to aim at with a specific API.

**Comment by strk** [comment]
It looks like the BufferBuilder::bufferLineSingleSided contained an heuristic code that would fix this case, namely it would drop from the edge list those edges that would not intersect with the edges of a full buffer, effectively removing those forming the artifacts. The current code is NOT using that method, which first appeared in GEOS, but is instead using code being a port of code subsequently added in JTS.

**Comment by strk** [comment]
I've just realized that the deprecated GEOSSingleSidedBuffer C-API function never returned an area, but was really just always returning effectively an offset curve, which explains the deprecation hint (and the confusion). What is referred to by "Single-Sided buffer" was never implemented natively in GEOS.

**Comment by strk** [comment]
Port of the heuristic in BufferBuilder::bufferSingleSidedBuffer was ported to the current code with https://github.com/libgeos/geos/pull/891 -- fixing the small case in the original description of this code. It should be tested against a wider set of cases.

**Comment by strk** [comment]
@dr-jts here's a view of a  PostGIS topology built from the input line and its right buffer:

![image](https://user-images.githubusercontent.com/289678/236621290-6d17633a-ccfb-42e3-8252-f5c14ffb09d5.png)

Here's a detail:

![image](https://user-images.githubusercontent.com/289678/236621192-619436aa-c074-4be8-8623-c8751942ddbb.png)

In the detail you can see that by removing faces that are on the left side instead of the right side of the edges forming the input line we should be able (in this case) to obtain what the user wants.
