### ISSUE TITLE
Union has incorrect results for some GeometryCollection inputs

### ISSUE THREAD

**Issue by ergpudb** [libgeos/geos#696]
Taking the union (using Geometry::Union) of `POLYGON ((0 0, 0 1, 1 1, 0 0))` and `MULTIPOINT (0 0, 99 99)` produces `GEOMETRYCOLLECTION (POLYGON ((0 1, 1 1, 0 0, 0 1)), POINT (99 99))`, which is correct (albeit with the polygon in the result starting at a different vertex).

However, taking the union of `POLYGON ((0 0, 0 1, 1 1, 0 0))` and `GEOMETRYCOLLECTION (MULTIPOINT (0 0, 99 99))` produces `POLYGON ((0 1, 1 1, 0 0, 0 1))`, which has lost the point `(99 99)`.

**Comment by robe2** [comment]
Yap the GEOMETRYCOLLECTION part is tripping it up.

I see the same issue on GEOS main and my production GEOS 3.10.2

**Comment by dr-jts** [comment]
JTS has added OverlayNG support for **simple** `GeometryCollections` in https://github.com/locationtech/jts/pull/915.

**Comment by dbaston** [comment]
Interesting that these cases were supported by GEOS but removing that support apparently produced no test failures in GEOS or PostGIS?

**Comment by pramsey** [comment]
I'd have to go back and dig, but any tests we may have had (and maybe we had none) would have come out / been turned off at OverlayNG switchover. I think it's possible we just didn't have any, I have no recollection of taking them out.
