### ISSUE TITLE
MSVC build broken

### ISSUE THREAD

**Issue by dbaston** [libgeos/geos#703]
The unit tests are currently failing because of a MSVC assertion failure. Unfortunately GitHub Actions does not provide the error message in this case, so I installed MSVC on a Windows machine to reproduce. The error is that the `DepthSegmentLessThen` comparator is invalid. It appears this was introduced by 70c0aa3db451af229c57f545045f25343570e0bf.

**Comment by dr-jts** [comment]
That commit does not reference `DepthSegmentLessThan`, so puzzled why it would cause this error?

Is there more information about the error in the build log from your MSVC build chain?

**Comment by dbaston** [comment]
`DepthSegmentLessThen` is implemented using `LineSegment::orientationIndex`. I don't have any other information, though I'd guess by "invalid" they mean that a < b and b < a according to the comparator.

**Comment by dr-jts** [comment]
Was there an err code?  Exact text of error message?

**Comment by dbaston** [comment]
The error message is "Invalid comparator."

You can provoke the same failure by adding this assert:

```
struct DepthSegmentLessThen {
    bool
    operator()(const DepthSegment* first, const DepthSegment* second)
    {
        assert(first);
        assert(second);
        if(first->compareTo(*second) < 0) {
            assert(!(second->compareTo(*first) < 0));  // make sure comparator is valid
            return true;
        }
        else {
            return false;
        }
    }
};
```
