### ISSUE TITLE
Implement LineSubstring

### ISSUE THREAD

**Issue by caspervdw** [libgeos/geos#706]
At shapely we would like to have a "LineSubstring" method. We now have a Python-implemented one, but an implementation by GEOS would be more efficient.

See also:
https://shapely.readthedocs.io/en/stable/manual.html#shapely.ops.substring

Related work:
- https://postgis.net/docs/manual-1.5/ST_Line_Substring.html
- https://github.com/pygeos/pygeos/issues/352

@jorisvandenbossche

**Comment by dbaston** [comment]
It sounds like exposing `LengthIndexedLine::extractLine` in the C API would meet this need?

https://github.com/libgeos/geos/blob/cc667261086d8e5f9906b69f4feaea5112221e92/include/geos/linearref/LengthIndexedLine.h#L96-L107
