### ISSUE TITLE
Segfault in `GEOSCoordSeq_create_r`

### ISSUE THREAD

**Issue by css-optivoy** [libgeos/geos#713]
I don't know if this is a fault in GEOS or Cartopy doing something sketchy, but this appears to only trigger on `geos=3.11.0` and not `geos=3.10.3` with everything else staying the same.

```
#0  0x00007fff8d57be3e in GEOSCoordSeq_create_r ()
    from /home/.../lib/libgeos_c.so.1
#1  0x00007fff8d5b3ad2 in __pyx_f_7cartopy_5trace_15LineAccumulator_as_geom(__pyx_obj_7cartopy_5trace_LineAccumulator*, GEOSContextHandle_HS*) ()
    from /home/.../lib/python3.10/site-packages/cartopy/trace.cpython-310-x86_64-linux-gnu.so
#2  0x00007fff8d5b4ea0 in __pyx_pw_7cartopy_5trace_3project_linear(_object*, _object*, _object*) ()
    from /home/.../lib/python3.10/site-packages/cartopy/trace.cpython-310-x86_64-linux-gnu.so
```

I unfortunately do have a minimal repro. as this comes from a big, private app.

**Comment by pramsey** [comment]
Without a repro, it's not actionable, unless you can get a stack trace into GEOS itself, preferably a Debug build so there are line numbers and so on. Even then, without knowing the inputs, the trace probably won't be actionable either.
