### ISSUE TITLE
should this be check_symbol_exists instead of check_prototype_exists?

### ISSUE THREAD

**Issue by yurikoif** [libgeos/geos#732]
https://github.com/libgeos/geos/blob/b602db59b5c5d0ddce1cee7dbe19d920a3359c8f/CMakeLists.txt#L196
should we use in this line check_symbol_exists instead of check_prototype_exists since we are searching in C headers instead of in c++ headers, just like searching for isfinite in line 207?

**Comment by yurikoif** [comment]
created pull request https://github.com/libgeos/geos/pull/742

**Comment by yurikoif** [comment]
> 

Oh sry I got you wrong in the first place. What I intended to say is, like in https://github.com/libgeos/geos/blob/b602db59b5c5d0ddce1cee7dbe19d920a3359c8f/CMakeLists.txt#L207

isn't it looking for a symbol in a header?

**Comment by pramsey** [comment]
Yes, that one seems odd.

**Comment by pramsey** [comment]
History seems to have caught up with this issue, I see neither test in the code base anywhere anymore.
