### ISSUE TITLE
github action fail with   sudo apt install libgeos++-dev

### ISSUE THREAD

**Issue by JunoWang** [libgeos/geos#744]
I run "`   sudo apt install libgeos++-dev"`  to install the libgeos in my GitHub action. The action shows installation is successful, but it cannot find the function during compilation with the following error. 
` error: ‘class geos::geom::Envelope’ has no member named ‘disjoint’`

Does anyone have a better solution for installing libgeos during GitHub action?

**Comment by dbaston** [comment]
It looks like this method was introduced in GEOS 3.9. Is an older version being installed?

**Comment by JunoWang** [comment]
> 

I was able to manually install the geos 3.9 with wget but the link is not available anymore. That is why I switch to this command. There is no older version installed during the GitHub action workflow.

**Comment by JunoWang** [comment]
> It looks like this method was introduced in GEOS 3.9. Is an older version being installed?

btw, it works fine when i install on a local ubuntu 20.04 with `sudo apt install libgeos++-dev`

**Comment by pramsey** [comment]
Sorry this seems out of our bailiwick being some kind of packaging issue.
