### ISSUE TITLE
CoverageValidator throws exception with empty input

### ISSUE THREAD

**Issue by dbaston** [libgeos/geos#750]
If an empty geometry is among the inputs to `CoverageValidator`, the following exception will be thrown:

```
'geos::util::IllegalArgumentException'
  what():  IllegalArgumentException: Ring has fewer than 4 points, so orientation cannot be determined
```

The exception be avoided by skipping empty geometries in `CoverageRing::createRing`. But I'm not sure that behavior is desirable. Is a completely empty coverage valid? (Maybe?) Is a coverage with a mixture of empty and non-empty polygons valid? (Maybe not?).

I came across this by feeding `geosop` help back into `geosop`:

```
geosop -h | grep "A  " | grep -v " N " | awk '{print $2}' | xargs -I{} bash -c 'echo -n "{}: " && geosop -a "POLYGON EMPTY" {}' || true
```

**Comment by dr-jts** [comment]
I would say:
* an empty coverage is valid
* a valid coverage should not contain empty polygons (although I'm less sure about this - perhaps they can be allowed, and simply ignored during coverage operations)
