### ISSUE TITLE
GEOSRemoveRepeatedPoints intermittent failure when collapsing a Polygon

### ISSUE THREAD

**Issue by jorisvandenbossche** [libgeos/geos#759]
When passing `POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))` (small rectangle) to `GEOSRemoveRepeatedPoints` with a tolerance of 2, all points would be filtered out, and so you end up with an invalid linearring (*"Invalid number of points in LinearRing found 2 - must be 0 or >= 4"*). 

However, in Shapely's CI we see an intermittent (seemingly random) failure where it fails to raise this error, but instead returns `POLYGON ((0 0, 0 0, 0 0))`.  
I don't understand why this doesn't raise the error when creating the linearring from those coordinates, because 3 is also less than 4. But I also don't see how the repeated points algorithm would result in three points instead of just the start and end point of the ring (resulting in 2 points, matching the error we typically get as mentioned above). 

---
Shapely code:

```
>>> shapely.remove_repeated_points(shapely.from_wkt("POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))"), tolerance=2)
...
GEOSException: IllegalArgumentException: Invalid number of points in LinearRing found 2 - must be 0 or >= 4
```

**Comment by jorisvandenbossche** [comment]
Something else related to the repeated point remove and small polygons. Because of the min length of 4 for LinearRings:

https://github.com/libgeos/geos/blob/9af60773c94f3829a9c63208cb7eaf07f9d104d3/src/operation/valid/RepeatedPointRemover.cpp#L192-L202

this also creates the inconsistency that `POLYGON ((0 0, 1 0, 1 1, 0 0))` (triangle) gets returned as is, while `POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))` (rectangle) raises an error

**Comment by dbaston** [comment]
Thanks for another nice report.

**Comment by jorisvandenbossche** [comment]
And thanks for the quick fix!
