### ISSUE TITLE
`GEOS_PATCH_WORD` is not available from `geos_c.h`

### ISSUE THREAD

**Issue by idanmiara** [libgeos/geos#798]
I am trying to get `GEOS_PATCH_WORD` (https://github.com/libgeos/geos/blob/main/Version.txt) via the C API, but I can't find it in https://github.com/libgeos/geos/blob/main/capi/geos_c.h.in

Is it missing from the C API?
If it is missing - maybe consider adding it?

Specifically I needed it for skipping a failing test in Shapely due to a GEOS master bug and I wanted to skip the test only in `3.12.0dev`
https://github.com/shapely/shapely/pull/1715

**Comment by pramsey** [comment]
3.12 is the version of the current master branch and eventual release this fall, if you want to skip a test on master, just skipping on 3.12 will do the trick.

**Comment by idanmiara** [comment]
@pramsey thanks for looking into this!
Say I wanted to skip a test on master because of some bug. 
I still wanted to fail if it the issue still present when its officially release - thus my suggestion for including this flag
But anyway - that's not a big issue.
