### ISSUE TITLE
documentation for previous releases

### ISSUE THREAD

**Issue by ahmednofal** [libgeos/geos#807]
Thank you for the work on this project.

I was reading through the documentation and the goes::geom::Polygon::clone member function returns a std::unique_ptr<geos::geom::Polygon> in latest version 3.12.0dev but returns std::unique_ptr<geos::geom::Geometry> is a previous release (3.8.0) which I can't find the documentation for.

Can you please help me in viewing the documentation of 3.8.0 or assisting in how I can convert one type to the other.

**Comment by pramsey** [comment]
Best bet is just to pull the 3.8 source code and read the headers for Geometry.h and Polygon.h.
