### ISSUE TITLE
Geometry created as 3D with NaN as z coordinate is 3D but WKT shows it as 2D

### ISSUE THREAD

**Issue by jorisvandenbossche** [libgeos/geos#808]
With the latest refactors of CoordinateSequence to better support different dimensionalities (https://github.com/libgeos/geos/pull/721 et al), the CoordinateSequence now better keeps track of its dimension (how it was created), and so is this `m_hasdim`/`m_hasz` bits are set, it no longer relies on checking if the z coordinate is NaN to determine if it is a 2D or 3D geometry (since 2D coords are still stored as XYZ physically). 

But that seems to create some corner cases if you happen to explicitly create a 3D geometry but where the z coordinate is NaN .. Using shapely (built with GEOS main) here as I didn't have time to create a C reproducer, but mentioned the C APIs that it corresponds to:

```python
>>> import shapely
>>> from numpy import NaN
# creating a Point with `GEOSCoordSeq_create_r` passing dims=3 -> `CoordinateSequence(1, 3)`
>>> p = shapely.Point(1, 2, NaN)
# this now knows it is 3D using `GEOSHasZ_r` 
>>> p.has_z 
True
# or using `GEOSGeom_getCoordinateDimension_r`
>>> shapely.get_coordinate_dimension(p)
3
# but printing it with WKT shows it as 2D (with `GEOSWKTWriter_setOutputDimension_r` set to 3)
>>> p
<POINT (1 2)>
```

So the geometry now keeps track of that it is 3D, but the WKT shows it as 2D (probably still checking if the z-coordinate is Nan?).

While WKB seems to follow the dimension and return 3D:

```python
>>> shapely.Point(1, 2).wkb.hex()
'0101000000000000000000f03f0000000000000040'
>>> shapely.Point(1, 2, NaN).wkb.hex()
'0101000080000000000000f03f0000000000000040000000000000f87f'
```

cc @dbaston

**Comment by dbaston** [comment]
This is intended behavior for the `WKTWriter`, though I'm not sure what the motivation for that behavior is. It omits Z and M if they do not have at least one non-NaN value.

We could remove this behavior (I'm not opposed, but others might be) or add a flag to disable it.

**Comment by dbaston** [comment]
> But that might also be from the time that checking for NaN was the only way to check if a geometry was 2D or 3D? (so not necessarily "intended" for removing that for "actual" 3D geometries).

I'm not sure. If I go back about 5 years in JTS I see that even when a `CoordinateSequence` claims to have a dimension >= 3, Z values are not written if they are NaN. https://github.com/locationtech/jts/blob/7f8cde4a5c0d7132e50dbed9ffad832683bb2e99/modules/core/src/main/java/org/locationtech/jts/io/WKTWriter.java#L510

I don't know how important it is to match JTS behavior in this regard.

> I suppose there are still ways that CoordinateSequences are created without explicit dims on construction? (and thus rely on checking for NaN to determine the dimension)

Yes. I'd like to get remove these usages, but it'll be a long process.

**Comment by pramsey** [comment]
I don't think there's any benefit to matching JTS on format reader/writers. The best implementation will probably be language specific, and there's no extra layers on top of the reader/writers that become hard to maintain if we have some C++ or implementation specificity in ours.

**Comment by dbaston** [comment]
So, OK to write `POINT Z (1 2 NaN)` for a geometry declared to be 3D where JTS would write `POINT (1 2)` ?

**Comment by rouault** [comment]
> POINT Z (1 2 NaN)

That would likely violate the WKT spec, which only allows <signed numeric literal> for x,y,z,m values. GDAL WKT reader currently rejects such WKT. PostGIS as well

**Comment by jorisvandenbossche** [comment]
Yes, but that is no different for x or y values:

```
>>> shapely.Point(1, np.nan)
<POINT (1 NaN)>
```

I think this was only recently changed, and on older GEOS NaNs were replaced with 0 in the WKT repr.
