### ISSUE TITLE
EqualsExact only checks for X and Y coordinates?

### ISSUE THREAD

**Issue by jorisvandenbossche** [libgeos/geos#809]
In https://github.com/libgeos/geos/issues/808, I wanted to mention that also `GEOSEqualsExact` ignores the dimensionality of the geometries when using that to compare a 2D and 3D Point with explicit NaN z value. But it seems that `GEOSEqualsExact` generally ignores the z (or m) dimension. 

Is this the intended behaviour? If so, that should maybe be documented, as I don't see this mentioned at

https://github.com/libgeos/geos/blob/c5c626127246adfed191bf4be6c9be1f3bc4c066/capi/geos_c.h.in#L4225-L4241

It might be assumed that since the other spatial predicates (based on DE-9IM) also ignore the z values, this is also the case for `EqualsExact`? (but since that's really a different model and is "just" checking coordinates, I would have assumed it didn't ignore z values like the others)

Example from Shapely:
```
>>> shapely.equals_exact(shapely.from_wkt("POINT (1 2 3)"), shapely.from_wkt("POINT (1 2 4)"))
True
```

And the Point::equalsExact is pretty explicit about using XY:

https://github.com/libgeos/geos/blob/c5c626127246adfed191bf4be6c9be1f3bc4c066/src/geom/Point.cpp#L276-L282

**Comment by dbaston** [comment]
I'm not sure what the motivation for ignoring Z/M is, but since it's longstanding behavior I'd probably get in trouble for changing it. I was thinking of adding a `GEOSEqualsExactFull` that checks all dimensions (better name ideas welcome!)

**Comment by jorisvandenbossche** [comment]
Or a parameter, but that also requires a new function, so then a new function that just uses the full dimensionality of the geometry (without options) seems indeed as a good solution.
