### ISSUE TITLE
BUG: GEOSSnap creates invalid MultiPolygons

### ISSUE THREAD

**Issue by brendan-ward** [libgeos/geos#814]
Detected using Shapely 2 / GEOS 3.12.0dev.

Snapping a very simple MultiPolygon of 2 boxes which are originally valid, to a line within tolerance between them, results in an invalid MultiPolygon because the polygons now share an edge:

```Python
>>> import shapely
>>> boxes = shapely.MultiPolygon([box(0, 0, 1, 1), box(3, 0, 4, 1)])
>>> boxes
<MULTIPOLYGON (((1 0, 1 1, 0 1, 0 0, 1 0)), ((4 0, 4 1, 3 1, 3 0, 4 0)))>
>>> shapely.is_valid(boxes)
True
>>> snapped = shapely.snap(boxes, LineString([(2, 0), (2, 1)]), tolerance=2)
>>> snapped
<MULTIPOLYGON (((2 1, 1 1, 0 1, 0 0, 2 0, 2 1)), ((4 0, 4 1, 2 1, 2 0, 4 0)))>
>>> shapely.is_valid(snapped)
False
```

Based on the description of GEOSSnap, I couldn't tell if this was expected behavior.  It doesn't look like MultiPolygons are covered in the existing test cases.

I'm also not sure what is correct behavior here: should it snap only the first and not the second?  Should it union the touching MultiPolygons into a single Polygon?  Should it do what it is doing now, in which case we should note that it may produce invalid geometries in some cases?

**Comment by pramsey** [comment]
The underlying code does not try to keep things valid, nor does it post-test on validity. I guess the simplest fix is just to document that. The alternative would be to do a cleanup call with an isvalid/makevalid run through on all the outputs.

**Comment by brendan-ward** [comment]
Documenting seems reasonable; I think we were a bit confused about the implications in the [docstring](https://github.com/libgeos/geos/blob/3.11.1/include/geos/operation/overlay/snap/GeometrySnapper.h#L42-L55) re: validity:

```
 * A snap distance tolerance is used to control where snapping is performed.
 * Snapping one geometry to another can improve
 * robustness for overlay operations by eliminating
 * nearly-coincident edges
 * (which cause problems during noding and intersection calculation).
 * Too much snapping can result in invalid topology
 * being created, so the number and location of snapped vertices
 * is decided using heuristics to determine when it
 * is safe to snap.
 * This can result in some potential snaps being omitted, however.
```

Would it be fair to say something like 

```
Where possible, this operation tries to avoid creating invalid geometries; however, 
it does not guarantee that output geometries will be valid.  It is the responsibility
of the caller to check for and handle invalid geometries.
```



In this case, automatically making it valid would produce unexpected results (at least to me):

```python
>>> shapely.make_valid(snapped).wkt
'GEOMETRYCOLLECTION (POLYGON ((0 1, 1 1, 2 1, 4 1, 4 0, 2 0, 0 0, 0 1)), LINESTRING (2 0, 2 1))'
```

**Comment by pramsey** [comment]
Want to turn into a PR? Your suggestion looks fine to me.

P
