### ISSUE TITLE
C API - Allow ownership of geometries to be taken from GeometryCollection types

### ISSUE THREAD

**Issue by tonywob** [libgeos/geos#848]
The C++ API offers a handy method that lets users take control of a collection type (GeometryCollection/MultiPolygon, etc) so that ownership of the geometries inside are passed back to the user using the **GeometryCollection::releaseGeometries()** method and the subsequent container can be thrown away.

The C API doesn't seem to offer this functionality (or I was unable to see the option in the docs), so in order to take objects out of the collection, they need to be wastefully copied again to prevent double deallocation and other hard to find bugs.

Case example

I need to clip geometries to a bounding box. The clipping operation will produce a GeometryCollection. I then would like to walk through the collection and pull out valid geometries and pass them to other functions for further processing. At present, using the C API, if I do this and then destroy the collection as I don't need it anymore, it'll also destroy the geometries inside it that I may have passed to another function. The workaround is to copy the object.. The C++ API lets me release the geometries and works as expected

**Comment by pramsey** [comment]
So this exists in C++ land. I shouldn't in practice be impossible in CAPI land, and seems like a reasonable inverse to collection creation, which takes ownership of the input geometries.

https://github.com/libgeos/geos/blob/a36676e3a0467dc6bdbfb426a4d369ded8f677d4/include/geos/geom/GeometryCollection.h#L174-L181
