### ISSUE TITLE
Add \since information to CAPI doxygen functions

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#854]
The first release of all CAPI functions is in the attached file.
[output.txt](https://github.com/libgeos/geos/files/11066472/output.txt)

**Comment by rouault** [comment]
For antiquated versions (let's say those released more than 5 years ago), adding a since tag is probably more noise than signal. Typically, for GDAL, from time to time, I remove @since tags (or similar mentions in .rst doc) for versions that are ridiculously outdated.
