### ISSUE TITLE
Assert extHandle exists?

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#873]
https://github.com/libgeos/geos/blob/f526c4f972f9a0caeecbf282698184933b2c42e4/capi/geos_ts_c.cpp#L416

@dbaston, I just got burned by this, and spent a lot of time trying to figure out what I was doing wrong. The problem was that I failed to initGeos. Would it make more sense to assert this, as it's more likely to be a development-time error than a run-time error?

**Comment by dbaston** [comment]
Agreed, I don't like propagating the null here...it just increases distance between where the error was introduced and where it breaks. (I have also wasted time with this)

An assert would be helpful but not for users of a debug build. I would be fine with removing the check and letting it crash, but maybe that's unpopular.

Could we not make the default context statically initialized and remove the need for `initGEOS` altogether?

**Comment by pramsey** [comment]
Maybe throw an informative exception?

**Comment by strk** [comment]
On Wed, Apr 26, 2023 at 01:34:07PM -0700, Paul Ramsey wrote:
> Maybe throw an informative exception?

+1 for informative exception
