### ISSUE TITLE
Why only one context per thread (capi)?

### ISSUE THREAD

**Issue by macdrevx** [libgeos/geos#876]
Hi all, I'm trying to understand which part of the design requires one context per thread:

```
/**
* Type returned by GEOS_init_r(), for use in multi-threaded
* applications.
*
* There should be only one GEOSContextHandle_t per thread.
*/
typedef struct GEOSContextHandle_HS *GEOSContextHandle_t;
```

I'm looking through the codebase (at 3.11.2), and I haven't yet located anything that is thread-aware. I also saw the note [here](https://libgeos.org/usage/c_api/#reentrantthreadsafe-api) about thread-local state, but I didn't find any references to `thread_local` or similar.

Thanks in advance for your guidance!

**Comment by dbaston** [comment]
I can't think of a problem that would be caused by multiple contexts in a single thread.
