### ISSUE TITLE
CoverageUnion sometimes returns invalid results for unnoded inputs

### ISSUE THREAD

**Issue by peterstace** [libgeos/geos#889]
I've noticed that for some inputs that are **not correctly noded**, coverage union will succeed but return an invalid geometry result. I'd instead expect the coverage union function to return an error (i.e. for `GEOSCoverageUnion` to return `NULL`). A minimum reproduction is:

```
#include <stdio.h>
#include <geos_c.h>

int main() {
	initGEOS(NULL, NULL);
	GEOSWKTReader *reader = GEOSWKTReader_create();
	GEOSWKTWriter *writer = GEOSWKTWriter_create();
	GEOSWKTWriter_setTrim(writer, 1);

	char *inputWKT = "GEOMETRYCOLLECTION (POLYGON ((0 0, 0 1, 1 0, 0 0)), POLYGON ((0 0, 2 0, 0 -2, 0 0)))";
	GEOSGeometry *input = GEOSWKTReader_read(reader, inputWKT);

	GEOSGeometry *output = GEOSCoverageUnion(input);
	char *outputWKT = GEOSWKTWriter_write(writer, output);

	char isValid = GEOSisValid(output);

	printf("input:  %s\n", inputWKT);
	printf("output: %s\n", outputWKT);
	printf("valid:  %d\n", isValid);

	GEOSGeom_destroy(input);
	GEOSGeom_destroy(output);
	GEOSWKTWriter_destroy(writer);
	GEOSWKTReader_destroy(reader);
	finishGEOS();
}
```

```
$ gcc -lgeos_c main.c && ./a.out
input:  GEOMETRYCOLLECTION (POLYGON ((0 0, 0 1, 1 0, 0 0)), POLYGON ((0 0, 2 0, 0 -2, 0 0)))
output: MULTIPOLYGON (((0 -2, 0 0, 2 0, 0 -2)), ((0 1, 1 0, 0 0, 0 1)))
valid:  0
```

The GEOS version I'm using is:
```
$ geos-config --version
3.11.2
```

**Comment by dr-jts** [comment]
It's (much) more expensive to check coverage validity than it is to compute the union of a valid coverage.   So this is deliberately not made part of the union algorithm to avoid incurring a performance penalty for every coverage (even valid ones).

Instead, if it is not known if the input is coverage-valid, this must be explicitly checked by the client prior to performing the union.

This is the same as the policy for other operations which require input geometry to be valid. It's expensive to check validity, and only the client knows whether the check is needed or not.

**Comment by peterstace** [comment]
Thanks for the quick response! Yes, that all makes sense. It's up to the user to either validate the coverage themselves (using `GEOSCoverageIsValid` or some other means, e.g. via construction).

I think the documentation in the C header could be improved because it currently states that it _will_ generate an error if the constraints aren't met. I've [raised a PR](https://github.com/libgeos/geos/pull/890) that tweaks the wording to make this a bit clearer.
