### ISSUE TITLE
MultiPoint WKT with EMPTY parts does not round-trip

### ISSUE THREAD

**Issue by mwtoews** [libgeos/geos#902]
MultiPoint geometries may contain EMPTY parts, however it is only preserved in the bracketed multipoint form. In the coordinate-sequence form it raises a ParseException:
```bash
$ ./bin/geosop -a "MULTIPOINT (EMPTY, (1 2))" -f wkt
MULTIPOINT (EMPTY, 1 2)
$ ./bin/geosop -a "MULTIPOINT (EMPTY, 1 2)" -f wkt
ParseException: Expected word but encountered number: '1'
$ ./bin/geosop -a "MULTIPOINT (EMPTY, (1 2))" -f wkt | ./bin/geosop -a stdin -f wkt
ParseException: Expected word but encountered number: '1'
```

There is no issue with WKB:
```bash
$ ./bin/geosop -a "MULTIPOINT (EMPTY, (1 2))" -f wkb | ./bin/geosop -a stdin.wkb -f wkt
MULTIPOINT (EMPTY, 1 2)
```
PostGIS is able to round-trip these WKT experiments.

**Comment by dr-jts** [comment]
It might be nice to fix this, but since this bug hasn't been reported before it's probably not essential.  #903 will mean that standard GEOS output does round-trip.

**Comment by mwtoews** [comment]
Closing as not planned, since `MULTIPOINT (EMPTY, 1 2)` is using a deprecated form for MultiPoint -- see #903
