### ISSUE TITLE
geos-3.11.2 cmake build doesn't produce geos_c.lib on Win-10

### ISSUE THREAD

**Issue by DarkSky7** [libgeos/geos#916]
I am trying to pip install cartopy which depends on geos.  I can cmake _build/capi/geos_c.h (which I manually copied to $PYTHONHOME/Include/) and seven more header files in geos-3.11.2/include/geos/ (which I have been manually copying into $PYTHONHOME/Include/geos), but cmake doesn't produce a geos_c.lib,  Here's where things go south...

 "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:. /LIBPATH:C:\Programs\Python311\libs /LIBPATH:C:\Programs\Python311 /LIBPATH:C:\Programs\Python311\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" geos_c.lib /EXPORT:PyInit_trace build\temp.win-amd64-cpython-311\Release\lib/cartopy/trace.obj /OUT:build\lib.win-amd64-cpython-311\cartopy\trace.cp311-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-311\Release\lib/cartopy\trace.cp311-win_amd64.lib
      LINK : fatal error LNK1181: cannot open input file 'geos_c.lib'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

Suggestions?

**Comment by pramsey** [comment]
No sorry.
