### ISSUE TITLE
Compute min/max scale from input in HeuristicOverlay

### ISSUE THREAD

**Issue by strk** [libgeos/geos#924]
This is to avoid over-simplifiying inputs, see https://trac.osgeo.org/postgis/ticket/5401 and https://github.com/libgeos/geos/issues/797

**Comment by pramsey** [comment]
Is this meant to be a PR? Any simplified example of the PostGIS case that we can employ as a unit test here?

**Comment by strk** [comment]
It was meant as a "task ticket". No simplified test yet

**Comment by dbaston** [comment]
Is this referring to simplification done within `HeuristicOverlay` (since removed), or snap-rounding happening inside `OverlayNG` ?

**Comment by strk** [comment]
This refers to HeuristicOverlay, which seems to still be used and kicks in IFF OverlayNG fails for any reason. In this case it was failing due to invalid argument being a collection, see https://trac.osgeo.org/postgis/ticket/5401#comment:16 -

Since which version was HeuristicOverlay removed ?

**Comment by pramsey** [comment]
It was effectively turned off with OverlayNG, although the code still remained, it was vastly less likely to be used, because OverlayNG has its own set of fallbacks as Dan notes, in gradually increasing the snaprounding tolerance in the event of overlay failure. So 3.10 is when it stopped working the way you might have a mental model of.

**Comment by strk** [comment]
Here are full debug logs of HeuristicOverlay for the case at hand with GEOS tag 3.10.1:
```
Trying with OverlayNGRobust
OverlayNGRobust: IllegalArgumentException: Argument must be Polygonal or LinearRing
Trying with original input.
Original exception: TopologyException: no outgoing dirEdge found at 10.907027451935953 64.968978126148144
Trying with Common Bits Remover (CBR)
CBR: TopologyException: no outgoing dirEdge found at 0.90702745193595213 0.96897812614814161
Trying with snapping 
Computed snap tolerance: 7.5270739785750608223e-11
Computed common bits: 10 64
SNAP: TopologyException: no outgoing dirEdge found at 0.90702745193595213 0.96897812614814161
Original input scales are: 0 and 0
Trying with scale 10000000000000000
Reduced with scale (10000000000000000): TopologyException: no outgoing dirEdge found at 10.907027451935953 64.968978126148144
Trying with scale 1000000000000000
PR: geom 1 (after precision reduction) is INVALID: Self-intersection at or near point 10.915059871883736 64.981718196166625 (10.915059871883736164 64.981718196166625034)
Reduced with scale (1000000000000000): TopologyException: found non-noded intersection between LINESTRING (10.9155 64.9797, 10.915 64.9816) and LINESTRING (10.9151 64.9812, 10.9153 64.9798) at 10.915109958441581 64.981228951342288
Trying with scale 100000000000000
Reduced with scale (100000000000000): TopologyException: no outgoing dirEdge found at 10.907027451935949 64.968978126148144
Trying with scale 10000000000000
Reduced with scale (10000000000000): TopologyException: no outgoing dirEdge found at 10.9070274519359 64.968978126148201
Trying with scale 1000000000000
Reduced with scale (1000000000000): TopologyException: no outgoing dirEdge found at 10.906466108059 64.969091584984
Trying with scale 100000000000
Reduced with scale (100000000000): TopologyException: no outgoing dirEdge found at 10.907027451939999 64.968978126150006
Trying with scale 10000000000
Reduced with scale (10000000000): TopologyException: no outgoing dirEdge found at 10.907027451799999 64.968978126099998
Trying with scale 1000000000
Reduced with scale (1000000000): TopologyException: no outgoing dirEdge found at 10.907027451999999 64.968978125999996
Trying with scale 100000000
Reduced with scale (100000000): TopologyException: no outgoing dirEdge found at 10.906172959999999 64.969628009999994
Trying with scale 10000000
Reduced with scale (10000000): TopologyException: no outgoing dirEdge found at 10.906173000000001 64.969628
Trying with scale 1000000
Reduced with scale (1000000): TopologyException: no outgoing dirEdge found at 10.906172 64.969628
Trying with scale 100000
Reduced with scale (100000): TopologyException: found non-noded intersection between LINESTRING (10.9108 64.9693, 10.9108 64.9694) and LINESTRING (10.9108 64.9694, 10.9107 64.9693) at 10.91079 64.969355000000007
Trying with scale 10000
Reduced with scale (10000): TopologyException: found non-noded intersection between LINESTRING (10.9114 64.9703, 10.9115 64.9704) and LINESTRING (10.9116 64.9705, 10.9114 64.9703) at 10.9114 64.970299999999995
Trying with scale 1000
Reduced with scale (1000): TopologyException: found non-noded intersection between LINESTRING (10.907 64.982, 10.907 64.981) and LINESTRING (10.905 64.981, 10.908 64.981) at 10.907 64.980999999999995
Trying with scale 100
Attempt with scale 100 succeeded
```

**Comment by strk** [comment]
Exactly, so the problem is basically in the catch which is too wide. HeuristicOverlay used to ONLY catch TopologyException while the code added to do OverlayNG is catching ANY exception

**Comment by pramsey** [comment]
I'm not sure I follow, but if you have a narrow patch for 3.10 / 3.11 I'm all ears. I don't necessarily think my 3.12 work is suitable to bring back into the older branches, as it's a definite behaviour change.

**Comment by dbaston** [comment]
https://github.com/libgeos/geos/commit/c4aebbbc048618e75b39f6c8d85dce8e8216cf9f changed from catching a `TopologyException` to catching any exception. That probably wasn't intentional.

**Comment by strk** [comment]
Aaaand, the commit turning from TopologyException to std::exception is your c4aebbbc048618e75b39f6c8d85dce8e8216cf9f -- specifically in https://github.com/libgeos/geos/commit/c4aebbbc048618e75b39f6c8d85dce8e8216cf9f#diff-fe4091b0d1cbe6972cabc0f5daba8f737ba035a9bb569055a16a3700987b9565L424 and looks like an unnoticed change

**Comment by strk** [comment]
3.9 3.10 and 3.11 are all affected, maybe this would need a separate ticket as this one is specifically about bailing out earlier instead of keep reducing precision

**Comment by strk** [comment]
@pramsey I'd still recommend being more specific in that case as std::exception would also be an out-of-memory condition or who knows what else and we don't want to keep banging head against that wall by various heuristics, right ?

**Comment by pramsey** [comment]
Oh, don't get me wrong, I'm in favour of flipping it back, I'm just curious if it'll break other behaviour.

**Comment by dbaston** [comment]
We didn't have any tests that were throwing an exception from OverlayNG, which is why I removed the fallbacks. And I figured if there were failures in OverlayNG we would want to hear about them instead of silently applying the heuristics.

**Comment by strk** [comment]
Reading the NEWS file I also see that 3.11.1 (patch-level) added support for GeometryCollection in OverlayNG which further complicates the matter (behavioural change in patch-level). The comments in the Geometry.h file are still saying an exception would be thrown if any input is a non-empty GeometryCollection.

**Comment by strk** [comment]
Well I've reverted that change in catching exception in all affected branches (3.9, 3.10 and 3.11).
This ticket may remain open in case any TopologyException is thrown by OverlayNG but at this moment we have no evidence of any such exception being thrown ?

**Comment by pramsey** [comment]
We might hear from downstream projects like R-sf, who (based on the 3.12beta feedback) do have at least a few cases in their test chain that exercise heterogeneous collections.

**Comment by pramsey** [comment]
Yeah, adding this test to OverlayNGTest.cpp
```cc
template<>
template<>
void object::test<46> ()
{
    WKTReader r;
    WKTWriter w;
    w.setTrim(true);
    std::string a = "GEOMETRYCOLLECTION(POLYGON((0 0, 10 0, 10 10, 0 10, 0 0)), LINESTRING(20 20, 30 30))";
    std::string b = "GEOMETRYCOLLECTION(POLYGON((9 9, 21 9, 21 21, 9 21, 9 9)), POINT(5 5))";
    std::string exp = "GEOMETRYCOLLECTION (LINESTRING (21 21, 30 30), POLYGON ((10 0, 0 0, 0 10, 9 10, 9 9, 10 9, 10 0)))";
    std::unique_ptr<Geometry> geom_a = r.read(a);
    std::unique_ptr<Geometry> geom_b = r.read(b);
    std::unique_ptr<Geometry> geom_rslt = geom_a->difference(geom_b.get());
    std::unique_ptr<Geometry> geom_exp = r.read(b);
    // std::cout << w.write(geom_rslt.get()) << std::endl;
    ensure_equals_geometry(geom_exp.get(), geom_rslt.get());
}
```
Results in a failure with the new (`catch TopologyException`) fixed code
```
---> group: geos::operation::overlayng::OverlayNG, test: test<46>
     problem: unexpected exception
     exception typeid: N4geos4util24IllegalArgumentExceptionE
     message: `IllegalArgumentException: Overlay input is mixed-dimension`
```
And with the old (`catch std::exception`) code, outputs a (correct) result. So this fix will result in behaviour regressions.

I think at a minimum that means maybe testing to see if @dbaston's idea of explicitly handing heterogenous collections to the old engine works better, but I fear that there's no reason to expect it wouldn't still get stuck into an occasional precision ultra-reduction, that's just the nature of the old fall-backs sometimes (there's lots of old trac tickets to that effect).

**Comment by pramsey** [comment]
Actually reading through @strk's log and the HeuristicOverlay code, ISTM that the effect of catching `std::exception` is the same as if we pre-caught mixed dimension GeometryCollection and went straight into the old overlay engine. And that old engine caused the extreme precision reduction. Except it didn't cause extreme reduction in 3.9? So what about the **old engine** changed between 3.9 and 3.10?

**Comment by strk** [comment]
On Thu, Jun 15, 2023 at 07:38:29PM +0000, Paul Ramsey wrote:
> Actually reading through @strk's log and the HeuristicOverlay code, ISTM that the effect of catching `std::exception` is the same as if we pre-caught mixed dimension GeometryCollection and went straight into the old overlay engine. And that old engine caused the extreme precision reduction. Except it didn't cause extreme reduction in 3.9? So what about the **old engine** changed between 3.9 and 3.10?

The catching of std::exception slipped in patch-level releases so
comparing 3.9 and 3.10 is not feasible. You should compare specific
(3 number) versions and you'll find differences in both 3.9 and 3.10
releases (depending on patch-level number).

**Comment by pramsey** [comment]
Not something I can do, since I cannot replicate the precision reduction bug in any version. The "fix" currently in 3.11/3.10 breaks other things as we thought it might: https://lists.osgeo.org/pipermail/geos-devel/2023-June/010948.html

**Comment by pramsey** [comment]
The problem that was actually reported in PostGIS didn't have to do with exception catching, it had to do with over-quantization, the solution to which is alluded to in this ticket title (compute min/max scale) and would apply to the code in the old HeuristicOverlay that is still around pre-3.12. I'd rather revert the change to the exception catching and see the min/max code dropped in, since that is what the PostGIS user was actually complaining about.

**Comment by dr-jts** [comment]
PostGIS issue [4711](https://trac.osgeo.org/postgis/ticket/4711) (also posted as GEOS [1034](https://trac.osgeo.org/geos/ticket/1034)) has a case which loses a lot of precision due to the precision-reduction heuristic.

**Comment by pramsey** [comment]
Can we close this out? 3.12 is out, which handles mixed collections fine using OverlayNG, and for the older branches, the user who originally posted this issue has a workaround.

**Comment by strk** [comment]
Fine with me, closing
