### ISSUE TITLE
HeuristicOverlay is failing to stop on IllegalArgumentException

### ISSUE THREAD

**Issue by strk** [libgeos/geos#925]
See https://github.com/libgeos/geos/issues/924#issuecomment-1593160531

**Comment by pramsey** [comment]
Stable branches are now explicitly catching the exception coming out of OverlayNG (`geos::util::IllegalArgumentException`) and allowing control to flow into the HeuristicOverlay, which retains old behaviour downstream will expect, so closing this out.
