### ISSUE TITLE
ST_TriangulatePolygon causes an IllegalStateException: Unable to find a convex corner

### ISSUE THREAD

**Issue by doskabouter** [libgeos/geos#935]
Executing
`select ST_TriangulatePolygon('SRID=3857;POLYGON((-19425239.38808801 9756954.96240437, -19425229.8368757 9756943.017144179, -19425229.8368757 9756931.071904326, -19425234.612481855 9756923.915531669, -19425234.612481855 9756909.575904647, -19425222.667900495 9756900.025137486, -19425220.274531443 9756888.079970947, -19425219.08341289 9756886.896216804, -19425216.69004384 9756891.658138067, -19425213.105556235 9756885.68555938, -19425217.892294336 9756883.291148638, -19425215.498925284 9756868.978508217, -19425222.667900495 9756859.400892986, -19425222.667900495 9756842.693904508, -19425225.050137594 9756840.299508449, -19425222.667900495 9756830.7488357, -19425227.443506647 9756818.803787274, -19425227.443506647 9756785.363140663, -19425222.667900495 9756773.418169618, -19425208.32995008 9756759.078850642, -19425198.77873777 9756739.977739615, -19425192.812013064 9756734.005290234, -19425182.058550254 9756730.427203637, -19425168.922850337 9756724.454762405, -19425161.753875133 9756717.298600772, -19425160.56275658 9756718.48232626, -19425160.56275658 9756730.427203637, -19425158.169387527 9756732.821562137, -19425155.787150428 9756754.317019496, -19425139.066962905 9756773.418169618, -19425134.280224804 9756790.151896028, -19425119.953406338 9756811.647529284, -19425119.953406338 9756818.803787274, -19425115.177800182 9756825.960052576, -19425115.177800182 9756833.143228492, -19425112.78443113 9756835.537622096, -19425112.78443113 9756847.482699057, -19425105.62658787 9756864.189698964, -19425105.62658787 9756876.134824766, -19425103.233218823 9756878.529233053, -19425105.62658787 9756883.291148638, -19425105.62658787 9756900.025137486, -19425110.402194027 9756902.419553943, -19425115.177800182 9756911.970324393, -19425115.177800182 9756919.126684852, -19425112.78443113 9756921.521107841, -19425112.78443113 9756945.411575329, -19425110.402194027 9756947.806007296, -19425110.402194027 9756957.356839618, -19425108.008824978 9756959.724371893, -19425105.62658787 9756988.40386053, -19425102.04210027 9756991.982078895, -19425096.064243615 9756993.165850792, -19425096.064243615 9757002.743648864, -19425103.233218823 9757009.900102075, -19425100.83984977 9757021.84547631, -19425105.62658787 9757031.396409573, -19425112.78443113 9757038.552892031, -19425119.953406338 9757052.892783014, -19425125.920131043 9757056.471034324, -19425145.033687614 9757056.471034324, -19425149.80929377 9757051.70900104, -19425164.147244185 9757049.31453355, -19425173.698456492 9757039.76357587, -19425178.474062648 9757039.76357587, -19425194.003131613 9757021.84547631, -19425194.003131613 9757017.05656257, -19425201.17210682 9757007.505648872, -19425217.892294336 9756993.165850792, -19425217.892294336 9756988.40386053, -19425229.8368757 9756976.458543304, -19425239.38808801 9756962.118808769, -19425239.38808801 9756954.96240437), (-19425217.892294336 9756914.364744933, -19425217.892294336 9756919.126684852, -19425214.307806734 9756922.704867823, -19425208.32995008 9756919.126684852, -19425205.947712976 9756914.364744933, -19425209.53220058 9756910.759662619, -19425214.307806734 9756910.759662619, -19425217.892294336 9756914.364744933), (-19425210.723319136 9756940.622713843, -19425208.32995008 9756943.017144179, -19425205.947712976 9756954.96240437, -19425196.38536872 9756964.513246462, -19425196.38536872 9756971.6696606, -19425192.812013064 9756975.274774248, -19425190.41864401 9756975.274774248, -19425186.834156405 9756969.30212427, -19425184.451919306 9756964.513246462, -19425196.38536872 9756950.173536366, -19425196.38536872 9756938.228284314, -19425198.77873777 9756933.466331398, -19425204.745462473 9756927.493717078, -19425209.53220058 9756927.493717078, -19425210.723319136 9756940.622713843), (-19425172.507337943 9756995.560299082, -19425170.11396889 9757024.239934416, -19425167.731731787 9757029.001949012, -19425158.169387527 9757036.18533312, -19425158.169387527 9757040.947355855, -19425154.584899925 9757044.525601024, -19425149.80929377 9757044.525601024, -19425140.25808146 9757051.70900104, -19425128.3135001 9757051.70900104, -19425122.34677539 9757045.736285899, -19425119.953406338 9757038.552892031, -19425123.537893943 9757034.974649886, -19425131.897987697 9757033.790870924, -19425134.280224804 9757021.84547631, -19425143.842569064 9757014.689010927, -19425148.61817522 9757002.743648864, -19425159.36050608 9756991.982078895, -19425168.922850337 9756991.982078895, -19425172.507337943 9756995.560299082))'::geometry)`
Gives the IllegalStateException.

Polygon itself doesn't seem to be very complex, only a couple of holes.
It has some thing todo with the south-most (first in the wkt) hole, removing that does give a correct triangulation.

![image](https://github.com/libgeos/geos/assets/2719782/be65d188-d685-4cb4-bf4d-a98585bb8b6a)

This is all done with:
PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
POSTGIS="3.3.3 2355e8e" [EXTENSION] PGSQL="150" GEOS="3.11.1-CAPI-1.17.1" PROJ="9.1.1" LIBXML="2.9.14" LIBJSON="0.16" LIBPROTOBUF="1.4.1" WAGYU="0.5.0 (Internal)"

**Comment by dr-jts** [comment]
This is fixed in 3.11.2 by https://github.com/libgeos/geos/commit/c5c626127246adfed191bf4be6c9be1f3bc4c066.

**Comment by doskabouter** [comment]
thanks!
