### ISSUE TITLE
Convert POLYGON to GEOSCoordSequence

### ISSUE THREAD

**Issue by ZMAlt** [libgeos/geos#938]
Hi, everyone.

It might not be good to ask usages here, but I didn't find a forum.

I get a buffer using `GEOSBuffer_r` function, and I want to convert it to GEOSCoordSequence. `GEOSGeom_getCoordSeq()` doesn't work. The C API says,
> Return the coordinate sequence underlying the given geometry (Must be a LineString, LinearRing or Point)

**Comment by pramsey** [comment]
You will want to start with [GEOSGetExteriorRing](http://libgeos.org/doxygen/geos__c_8h.html#afc5d54a2905996833747c2d566da2af3) and then move on to getting the CoordinateSequence. If you have a MultiPolygon, you'll start with GetGeometryN then GetExteriorRing and then the coordinates.

**Comment by ZMAlt** [comment]
Hi, Parmsey. 

I am little confused about the `GEOSGetExteriorRing` function. I get a buffer (red) of the curve(green) as follows. I do convert buffer POLYGON to  CoordinateSequence using  `GEOSGetExteriorRing` function. As you can see, the buffer is not correct. It should be like the black curve. I think the problem is with the  `GEOSGetExteriorRing` function, because I got correct result in LibGEOS.jl.
![image](https://github.com/libgeos/geos/assets/35285040/2cb93abf-8f43-405f-b4eb-e5e7b6596d81)
