### ISSUE TITLE
No Method to call MinimumAreaRectangle with isConvex flag

### ISSUE THREAD

**Issue by ghanta1996** [libgeos/geos#941]
The `MiimmumAreaRectangle` class has only one public static member that calls the `getMinimumRectangle`. There's no public method to make use of the constructor  
``` 
    MinimumAreaRectangle(const Geometry* inputGeom, bool isConvex)
        : m_inputGeom(inputGeom)
        , m_isConvex(isConvex)
        {};
```

Even when the `MinimumAreaRectangle` object is constructed with the above constructor, the flag is not considered in the static method

```
/* public static */
std::unique_ptr<Geometry>
MinimumAreaRectangle::getMinimumRectangle(const Geometry* geom)
{
    MinimumAreaRectangle mar(geom);
    return mar.getMinimumRectangle();
}
```

**Comment by dr-jts** [comment]
That is a very minor optimization, so we just didn't bother exposing it in the C-API. And hence there was no reason to make a static function exposing it.

**Comment by ghanta1996** [comment]
Thanks for your reply. Noted that.
